// SPDX-License-Identifier: MIT
/**
 * Visual verification for the Phase-4 tokens engine/brand split.
 *
 * The geneWeave design tokens are now generated by the app's OWN brand (apps/geneweave-ui/src/brand/)
 * composed on the brand-neutral @weaveintel/tokens ENGINE. The generated CSS is byte-identical to before
 * the split (proven at build time), so this test confirms end-to-end that the brand tokens are LIVE in a
 * real browser — the emerald accent, the canvas surface, and the fonts — and captures a screenshot to
 * review against the design (dc.html).
 */
import { test, expect } from '@playwright/test';

test('geneWeave brand tokens are live in the browser after the engine/brand split', async ({ page }) => {
  await page.goto('/');
  await page.waitForLoadState('networkidle');

  // The `--gw-*` custom properties are emitted by the app brand → the engine transform. Read them back
  // from the live document to prove the brand survived the split intact.
  const tokens = await page.evaluate(() => {
    const s = getComputedStyle(document.documentElement);
    return {
      accent: s.getPropertyValue('--gw-color-accent').trim(),
      background: s.getPropertyValue('--gw-color-background').trim(),
      mint: s.getPropertyValue('--gw-color-mint').trim(),
      fontDisplay: s.getPropertyValue('--gw-font-display').trim(),
      aiSurface: s.getPropertyValue('--gw-ai-surface').trim(),
    };
  });

  expect(tokens.accent).toBe('#0E9A6E');          // emerald — the geneWeave identity
  expect(tokens.background).toBe('#F6F8F7');       // light canvas
  expect(tokens.mint).toBe('#E8F5EE');             // AI-agency surface
  expect(tokens.fontDisplay).toContain('Plus Jakarta Sans');
  expect(tokens.aiSurface).toBe('#E8F5EE'); // agency token composed in the app → resolves to mint

  await page.screenshot({ path: 'test-results/tokens-split-landing.png', fullPage: true });
});
