#!/usr/bin/env bash
# Phase 8 — deprecate the 44 retired @weaveintel/* names (nothing is unpublished; existing installs keep working).
# REVIEW before running. Each message names the replacement.
set -euo pipefail

npm deprecate "@weaveintel/coedit@*" "Merged into @weaveintel/collab as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/collaboration@*" "Merged into @weaveintel/collab as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/reliability@*" "Merged into @weaveintel/resilience as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/durability@*" "Merged into @weaveintel/resilience as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/redaction@*" "Merged into @weaveintel/guardrails/redaction as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/compliance@*" "Merged into @weaveintel/guardrails/compliance as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/oauth@*" "Merged into @weaveintel/identity/oauth as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tenancy@*" "Merged into @weaveintel/identity/tenancy as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/scope@*" "Merged into @weaveintel/identity/scope as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/models@*" "Merged into @weaveintel/core/models as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/contracts@*" "Merged into @weaveintel/core/contracts as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/plugins@*" "Merged into @weaveintel/core/plugins as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/capability-packs@*" "Merged into @weaveintel/core/capability-packs as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/i18n@*" "Merged into @weaveintel/core/i18n as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/evals@*" "Merged into @weaveintel/testing/evals as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/replay@*" "Merged into @weaveintel/observability/replay as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/graph@*" "Merged into @weaveintel/memory as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/recipes@*" "Merged into @weaveintel/agents/recipes as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/react-client@*" "Merged into @weaveintel/client/react as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/live-agents-trace-tools@*" "Merged into @weaveintel/live-agents/trace-tools as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tool-schema@*" "Merged into @weaveintel/tools/schema as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-http@*" "Merged into @weaveintel/tools/http as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-time@*" "Merged into @weaveintel/tools/time as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-search@*" "Merged into @weaveintel/tools/search as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-gmail@*" "Merged into @weaveintel/tools/gmail as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-gcal@*" "Merged into @weaveintel/tools/gcal as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-gdrive@*" "Merged into @weaveintel/tools/gdrive as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-imap@*" "Merged into @weaveintel/tools/imap as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-outlook@*" "Merged into @weaveintel/tools/outlook as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-outlook-cal@*" "Merged into @weaveintel/tools/outlook-cal as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-onedrive@*" "Merged into @weaveintel/tools/onedrive as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-dropbox@*" "Merged into @weaveintel/tools/dropbox as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-slack@*" "Merged into @weaveintel/tools/slack as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-webhook@*" "Merged into @weaveintel/tools/webhook as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-filewatch@*" "Merged into @weaveintel/tools/filewatch as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-news@*" "Merged into @weaveintel/tools/news as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-social@*" "Merged into @weaveintel/tools/social as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-marketdata@*" "Merged into @weaveintel/tools/marketdata as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-altdata@*" "Merged into @weaveintel/tools/altdata as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-broker@*" "Merged into @weaveintel/tools/broker as of 0.1.1 — see MIGRATION.md (https://github.com/gibyvarghese/weaveintel/blob/main/MIGRATION.md)."
npm deprecate "@weaveintel/tools-kaggle@*" "Retired in 0.1.1 — now the geneWeave app (now app-owned; no published replacement). See MIGRATION.md."
npm deprecate "@weaveintel/mcp-statsnz@*" "Retired in 0.1.1 — now examples/verticals/statsnz (unpublished reference example). See MIGRATION.md."
npm deprecate "@weaveintel/equity-scoring@*" "Retired in 0.1.1 — now examples/verticals/equity-scoring (unpublished reference example). See MIGRATION.md."
npm deprecate "@weaveintel/social-growth@*" "Retired in 0.1.1 — now examples/verticals/social-growth (unpublished reference example). See MIGRATION.md."

echo "✅ deprecated 44 retired names"
