#!/usr/bin/env bash
# Phase 8 — publish all 46 surviving @weaveintel/* packages at 0.1.1 to the PUBLIC npm registry.
# REVIEW before running. Requires: npm whoami = an owner of @weaveintel/*; a clean build (npm run build).
set -euo pipefail
cd "$(dirname "$0")/../.."

( cd packages/core && echo "→ publishing @weaveintel/core@0.1.1" && npm publish --access public )
( cd clients/tokens && echo "→ publishing @weaveintel/tokens@0.1.1" && npm publish --access public )
( cd packages/persistence && echo "→ publishing @weaveintel/persistence@0.1.1" && npm publish --access public )
( cd packages/testing && echo "→ publishing @weaveintel/testing@0.1.1" && npm publish --access public )
( cd packages/resilience && echo "→ publishing @weaveintel/resilience@0.1.1" && npm publish --access public )
( cd packages/observability && echo "→ publishing @weaveintel/observability@0.1.1" && npm publish --access public )
( cd packages/prompts && echo "→ publishing @weaveintel/prompts@0.1.1" && npm publish --access public )
( cd packages/guardrails && echo "→ publishing @weaveintel/guardrails@0.1.1" && npm publish --access public )
( cd packages/identity && echo "→ publishing @weaveintel/identity@0.1.1" && npm publish --access public )
( cd packages/encryption && echo "→ publishing @weaveintel/encryption@0.1.1" && npm publish --access public )
( cd packages/cost-governor && echo "→ publishing @weaveintel/cost-governor@0.1.1" && npm publish --access public )
( cd packages/memory && echo "→ publishing @weaveintel/memory@0.1.1" && npm publish --access public )
( cd packages/retrieval && echo "→ publishing @weaveintel/retrieval@0.1.1" && npm publish --access public )
( cd packages/cache && echo "→ publishing @weaveintel/cache@0.1.1" && npm publish --access public )
( cd packages/artifacts && echo "→ publishing @weaveintel/artifacts@0.1.1" && npm publish --access public )
( cd packages/extraction && echo "→ publishing @weaveintel/extraction@0.1.1" && npm publish --access public )
( cd packages/notifications && echo "→ publishing @weaveintel/notifications@0.1.1" && npm publish --access public )
( cd packages/sandbox && echo "→ publishing @weaveintel/sandbox@0.1.1" && npm publish --access public )
( cd packages/human-tasks && echo "→ publishing @weaveintel/human-tasks@0.1.1" && npm publish --access public )
( cd packages/mcp-client && echo "→ publishing @weaveintel/mcp-client@0.1.1" && npm publish --access public )
( cd packages/mcp-server && echo "→ publishing @weaveintel/mcp-server@0.1.1" && npm publish --access public )
( cd packages/tools && echo "→ publishing @weaveintel/tools@0.1.1" && npm publish --access public )
( cd packages/routing && echo "→ publishing @weaveintel/routing@0.1.1" && npm publish --access public )
( cd packages/agents && echo "→ publishing @weaveintel/agents@0.1.1" && npm publish --access public )
( cd packages/skills && echo "→ publishing @weaveintel/skills@0.1.1" && npm publish --access public )
( cd packages/workflows && echo "→ publishing @weaveintel/workflows@0.1.1" && npm publish --access public )
( cd packages/triggers && echo "→ publishing @weaveintel/triggers@0.1.1" && npm publish --access public )
( cd packages/a2a && echo "→ publishing @weaveintel/a2a@0.1.1" && npm publish --access public )
( cd packages/live-agents && echo "→ publishing @weaveintel/live-agents@0.1.1" && npm publish --access public )
( cd packages/live-agents-runtime && echo "→ publishing @weaveintel/live-agents-runtime@0.1.1" && npm publish --access public )
( cd packages/collab && echo "→ publishing @weaveintel/collab@0.1.1" && npm publish --access public )
( cd packages/voice && echo "→ publishing @weaveintel/voice@0.1.1" && npm publish --access public )
( cd packages/notes && echo "→ publishing @weaveintel/notes@0.1.1" && npm publish --access public )
( cd packages/ui-primitives && echo "→ publishing @weaveintel/ui-primitives@0.1.1" && npm publish --access public )
( cd packages/client && echo "→ publishing @weaveintel/client@0.1.1" && npm publish --access public )
( cd packages/tools-browser && echo "→ publishing @weaveintel/tools-browser@0.1.1" && npm publish --access public )
( cd packages/tools-enterprise && echo "→ publishing @weaveintel/tools-enterprise@0.1.1" && npm publish --access public )
( cd packages/provider-openai && echo "→ publishing @weaveintel/provider-openai@0.1.1" && npm publish --access public )
( cd packages/provider-anthropic && echo "→ publishing @weaveintel/provider-anthropic@0.1.1" && npm publish --access public )
( cd packages/provider-google && echo "→ publishing @weaveintel/provider-google@0.1.1" && npm publish --access public )
( cd packages/provider-ollama && echo "→ publishing @weaveintel/provider-ollama@0.1.1" && npm publish --access public )
( cd packages/provider-llamacpp && echo "→ publishing @weaveintel/provider-llamacpp@0.1.1" && npm publish --access public )
( cd packages/devtools && echo "→ publishing @weaveintel/devtools@0.1.1" && npm publish --access public )
( cd packages/a11y && echo "→ publishing @weaveintel/a11y@0.1.1" && npm publish --access public )
( cd clients/api-client && echo "→ publishing @weaveintel/api-client@0.1.1" && npm publish --access public )
( cd packages/weaveintel && echo "→ publishing @weaveintel/weaveintel@0.1.1" && npm publish --access public )

echo "✅ published 46 packages at 0.1.1"
