/**
 * Example 87 — Phase 5 generic mesh provisioner + heartbeat supervisor.
 *
 * Demonstrates the DB-driven runtime path that replaces hand-rolled
 * `bootKaggleMesh()` / `startKaggleHeartbeat()` style code:
 *
 *   1. Seed a tiny `live_mesh_definitions` blueprint with two agents
 *      (`triager` and `responder`) wired to the built-in `agentic.react`
 *      handler kind.
 *   2. Call `provisionMesh()` to materialize a tenant-scoped runtime mesh:
 *         live_meshes
 *         live_agents (one per agent definition)
 *         live_agent_handler_bindings (one per agent, default_handler_kind)
 *      The same call mirrors the topology into the live-agents StateStore so
 *      a supervisor can pick up work immediately.
 *   3. Start `createHeartbeatSupervisor()` with a NOOP model factory.
 *   4. Wait 6 seconds so the supervisor logs at least one schedule + tick
 *      cycle, then stop.
 *
 * Notes:
 *   • Kaggle remains untouched — its hand-tuned heartbeat keeps running in
 *     production. The generic supervisor is opt-in via
 *     `LIVE_AGENTS_GENERIC_RUNTIME=1` in `apps/geneweave`.
 *   • This example uses an isolated SQLite file to avoid colliding with
 *     `./geneweave.db` and seeds `LIVE_AGENTS_DB_PATH` accordingly so the
 *     StateStore writes into the same file.
 *
 * Run:
 *   npx tsx examples/87-mesh-provisioner.ts
 */

import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const tmp = mkdtempSync(join(tmpdir(), 'gw-phase5-'));
const dbPath = join(tmp, 'phase5.db');
process.env['DATABASE_PATH'] = dbPath;
process.env['LIVE_AGENTS_DB_PATH'] = dbPath;

const { createDatabaseAdapter } = await import('../apps/geneweave/src/db.js');
const { newUUIDv7 } = await import('../apps/geneweave/src/lib/uuid.js');
const {
  provisionMesh,
  createHeartbeatSupervisor,
  createDefaultHandlerRegistry,
} = await import('@weaveintel/live-agents-runtime');
const { weaveSqliteStateStore } = await import('@weaveintel/live-agents');

async function main() {
  console.log('=== Example 87 — Phase 5 generic mesh provisioner ===\n');

  // 1. Spin up the canonical SQLite adapter (runs all migrations including
  //    the live_agent_definitions Phase 5 default columns).
  const db = await createDatabaseAdapter({ type: 'sqlite', path: dbPath });

  // 2. Seed a minimal blueprint: one mesh, two agents.
  const meshDefId = newUUIDv7();
  await db.createLiveMeshDefinition({
    id: meshDefId,
    mesh_key: `phase5-demo-${Date.now()}`,
    name: 'Phase 5 Demo Mesh',
    charter_prose:
      'Two-agent demo: triager classifies inbound work, responder drafts the reply.',
    dual_control_required_for: '[]',
    enabled: 1,
    description: 'Generated by examples/87-mesh-provisioner.ts',
  });

  const triagerId = newUUIDv7();
  await db.createLiveAgentDefinition({
    id: triagerId,
    mesh_def_id: meshDefId,
    role_key: 'triager',
    name: 'Triager',
    role_label: 'Inbound Triager',
    persona: 'You categorize incoming requests and decide who should handle them.',
    objectives: 'Categorize each new message and forward it to the responder.',
    success_indicators: 'Every inbound message has been classified within one tick.',
    ordering: 0,
    enabled: 1,
    // Phase 5 defaults — what `provisionMesh` will use to seed bindings.
    default_handler_kind: 'agentic.react',
    default_handler_config_json: JSON.stringify({ maxSteps: 3 }),
    default_attention_policy_key: 'heuristic.inbox-first',
  });

  const responderId = newUUIDv7();
  await db.createLiveAgentDefinition({
    id: responderId,
    mesh_def_id: meshDefId,
    role_key: 'responder',
    name: 'Responder',
    role_label: 'Reply Drafter',
    persona: 'You draft polite, accurate replies based on the triager classification.',
    objectives: 'Produce a draft reply for every classified message.',
    success_indicators: 'Replies are grounded in the original message and sent.',
    ordering: 1,
    enabled: 1,
    default_handler_kind: 'agentic.react',
    default_handler_config_json: JSON.stringify({ maxSteps: 5 }),
    default_attention_policy_key: 'heuristic.inbox-first',
  });

  console.log(`✓ Seeded mesh def ${meshDefId} with 2 agent defs\n`);

  // 3. Provision a runtime mesh from the blueprint. This writes to:
  //      live_meshes, live_agents, live_agent_handler_bindings,
  //      live_agent_tool_bindings (none here — empty default_tool_catalog_keys),
  //    and mirrors mesh + agents into the StateStore.
  const store = await weaveSqliteStateStore({ path: dbPath });
  const result = await provisionMesh(
    db,
    {
      meshDefId,
      tenantId: 'demo-tenant',
      ownerHumanId: 'human:demo',
      name: 'Phase 5 Demo Runtime',
      status: 'ACTIVE',
      store,
    },
    newUUIDv7,
  );

  console.log('✓ provisionMesh result:');
  console.log(JSON.stringify(result, null, 2));
  console.log();

  // 4. Boot the generic supervisor. NOOP model factory keeps the demo
  //    deterministic; real deployments would inject getOrCreateModel().
  const handlerRegistry = createDefaultHandlerRegistry();
  const supervisor = await createHeartbeatSupervisor({
    db,
    store,
    handlerRegistry,
    intervalMs: 1500,    // tick fast for the demo
    refreshMs: 10_000,
    workers: 2,
    logger: (m) => console.log(`  [sup] ${m}`),
  });

  console.log('\n✓ Supervisor running for 6s — watch for schedule + tick logs:\n');
  await new Promise((r) => setTimeout(r, 6000));
  await supervisor.stop();
  console.log('\n✓ Supervisor stopped cleanly');

  await db.close();
  rmSync(tmp, { recursive: true, force: true });
  console.log('\n=== Example 87 complete ===');
}

main().catch((err) => {
  console.error('Example 87 failed:', err);
  process.exit(1);
});
