#!/usr/bin/env bash
# pin-digests.sh — Pull the three scientific sandbox images and write their
# sha256 digests to digests.json in the tools directory.
#
# Usage:
#   REGISTRY=ghcr.io/weaveintel bash pin-digests.sh
#
# Outputs:
#   apps/geneweave/src/features/scientific-validation/tools/digests.json
#
# Requires: docker (logged into GHCR), jq

set -euo pipefail

REGISTRY="${REGISTRY:-ghcr.io/weaveintel}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$TOOLS_DIR/digests.json"

get_digest() {
  local image="$1"
  docker pull "$image" --quiet >/dev/null 2>&1
  docker inspect --format='{{index .RepoDigests 0}}' "$image" 2>/dev/null \
    | grep -oE 'sha256:[a-f0-9]{64}' \
    || echo "sha256:0000000000000000000000000000000000000000000000000000000000000000"
}

echo "Pinning image digests..."

SYM_TAG="${REGISTRY}/sandbox-sym:latest"
NUM_TAG="${REGISTRY}/sandbox-num:latest"
DOM_TAG="${REGISTRY}/sandbox-dom:latest"

SYM_DIGEST=$(get_digest "$SYM_TAG")
NUM_DIGEST=$(get_digest "$NUM_TAG")
DOM_DIGEST=$(get_digest "$DOM_TAG")

jq -n \
  --arg sym "$SYM_DIGEST" \
  --arg num "$NUM_DIGEST" \
  --arg dom "$DOM_DIGEST" \
  '{
    "sandbox-sym": $sym,
    "sandbox-num": $num,
    "sandbox-dom": $dom,
    "_note": "Generated by pin-digests.sh — do not edit manually",
    "_updated": (now | todate)
  }' > "$OUTPUT"

echo "Written: $OUTPUT"
cat "$OUTPUT"
