// SPDX-License-Identifier: MIT
import { describe, it, expect } from 'vitest';
import {
  buildImageProvenance, provenanceCreditLine, provenanceToXmp, embedXmpInSvg, parseProvenanceFromSvg,
} from './provenance.js';

describe('image provenance — build manifest', () => {
  it('builds a web manifest with licence + attribution', () => {
    const p = buildImageProvenance({ kind: 'web', title: 'Heart diagram', license: 'cc-by-sa', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/', author: 'Wapcaplet', sourceUrl: 'https://commons.wikimedia.org/x', provider: 'wikimedia' });
    expect(p.kind).toBe('web');
    expect(p.license).toBe('cc-by-sa');
    expect(p.author).toBe('Wapcaplet');
    expect(p.attribution).toMatch(/Wapcaplet/);
    expect(p.attribution).toMatch(/CC-BY-SA/i);
  });

  it('builds an AI manifest with generator/model/prompt', () => {
    const p = buildImageProvenance({ kind: 'ai-generated', title: 'A red fox', generator: 'geneWeave AI', model: 'gpt-image-1', prompt: 'a red fox in snow' });
    expect(p.kind).toBe('ai-generated');
    expect(p.model).toBe('gpt-image-1');
    expect(p.prompt).toBe('a red fox in snow');
    expect(p.attribution).toMatch(/Generated by geneWeave AI/);
    expect(p.attribution).toMatch(/gpt-image-1/);
    expect(p.license).toBeUndefined();   // web-only field absent
  });

  it('prefers a precomputed attribution line + clamps confidence', () => {
    const p = buildImageProvenance({ kind: 'web', title: 'x', attribution: 'My custom credit', verified: true, verifyConfidence: 1.4 });
    expect(p.attribution).toBe('My custom credit');
    expect(p.verifyConfidence).toBe(1);
  });

  it('credit line differs by kind', () => {
    expect(provenanceCreditLine({ kind: 'web', title: 'T', author: 'A', license: 'cc0', attribution: '' })).toMatch(/by A/);
    expect(provenanceCreditLine({ kind: 'ai-illustration', generator: 'geneWeave AI', attribution: '' })).toMatch(/Generated by/);
  });
});

describe('image provenance — XMP + SVG embed/round-trip', () => {
  it('renders an XMP packet with dc:rights + a JSON channel', () => {
    const p = buildImageProvenance({ kind: 'web', title: 'Heart', author: 'X', license: 'cc-by', licenseUrl: 'https://l' });
    const xmp = provenanceToXmp(p);
    expect(xmp).toMatch(/x:xmpmeta/);
    expect(xmp).toMatch(/dc:rights/);
    expect(xmp).toMatch(/WebStatement/);
    expect(xmp).toContain('gw-provenance:');
  });

  it('escapes XML special characters (no injection into the SVG)', () => {
    const p = buildImageProvenance({ kind: 'web', title: 'a <b> & "c"', author: 'x' });
    const xmp = provenanceToXmp(p);
    expect(xmp).toContain('&lt;b&gt;');
    expect(xmp).not.toMatch(/<dc:title>a <b>/); // raw angle brackets not injected
  });

  it('embeds into an SVG and round-trips the exact manifest', () => {
    const svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><rect/></svg>';
    const p = buildImageProvenance({ kind: 'ai-illustration', title: 'fox', generator: 'geneWeave AI', model: 'svg-author', prompt: 'a fox' });
    const out = embedXmpInSvg(svg, p);
    expect(out).toContain('<metadata id="gw-provenance">');
    expect(out).toContain('<rect/>');                    // original content preserved
    const parsed = parseProvenanceFromSvg(out);
    expect(parsed).not.toBeNull();
    expect(parsed!.kind).toBe('ai-illustration');
    expect(parsed!.prompt).toBe('a fox');
    expect(parsed!.attribution).toBe(p.attribution);
  });

  it('replaces a prior gw metadata block instead of stacking', () => {
    const svg = '<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>';
    const once = embedXmpInSvg(svg, buildImageProvenance({ kind: 'web', title: 'one' }));
    const twice = embedXmpInSvg(once, buildImageProvenance({ kind: 'web', title: 'two' }));
    expect((twice.match(/id="gw-provenance"/g) ?? []).length).toBe(1);
    expect(parseProvenanceFromSvg(twice)!.title).toBe('two');
  });

  it('is robust: non-SVG returned unchanged, missing manifest → null', () => {
    expect(embedXmpInSvg('not an svg', buildImageProvenance({ kind: 'web' }))).toBe('not an svg');
    expect(parseProvenanceFromSvg('<svg></svg>')).toBeNull();
    expect(parseProvenanceFromSvg('garbage')).toBeNull();
  });
});
