// SPDX-License-Identifier: MIT
/**
 * @weaveintel/notes — IMAGE PROVENANCE & licence credentials.
 *
 * When the assistant adds a picture — sourced from the web or drawn/generated by AI — the image
 * should carry WHERE IT CAME FROM with it: the licence + attribution for a web image, and the
 * "made by AI" lineage (generator, model, the prompt) for a generated one. That is the 2026 norm
 * (C2PA "Content Credentials"): provenance travels WITH the asset, not in a sidecar that gets lost
 * on export. This module is the pure core:
 *   • `buildImageProvenance` normalises web/AI inputs into one typed manifest + a human credit line;
 *   • `provenanceToXmp` renders a small XMP/Dublin-Core packet (licence, creator, AI assertion);
 *   • `embedXmpInSvg` GENUINELY embeds that packet (+ a machine-readable JSON) into an SVG's bytes,
 *     and `parseProvenanceFromSvg` reads it back — so an exported SVG is self-describing;
 *   • for raster images the app stores the same manifest WITH the asset (it can't rewrite PNG bytes
 *     without a signing lib — we don't fake C2PA signing) and serves it as content credentials.
 *
 * Pure + zero-dependency.
 */

/** How an image entered the note. */
export type ImageSourceKind = 'web' | 'ai-generated' | 'ai-illustration';

export interface ImageProvenance {
  kind: ImageSourceKind;
  /** A short title/subject. */
  title?: string;
  /** Web image: licence id (e.g. 'cc-by-sa'), a licence URL, the creator, the source page + provider. */
  license?: string;
  licenseUrl?: string;
  author?: string;
  sourceUrl?: string;
  provider?: string;
  /** AI image: who/what generated it, the model, and the prompt that produced it. */
  generator?: string;
  model?: string;
  prompt?: string;
  /** Whether a vision check confirmed the image matches its intent (+ the confidence). */
  verified?: boolean;
  verifyConfidence?: number;
  /** A ready human credit line, e.g. "‘Heart’ by X — CC BY-SA (via Wikimedia)". */
  attribution: string;
}

function clip(s: unknown, n: number): string { return (typeof s === 'string' ? s : '').trim().slice(0, n); }

/** Build a normalised provenance manifest (+ a human credit line) from web/AI inputs. */
export function buildImageProvenance(input: {
  kind: ImageSourceKind;
  title?: string;
  // web
  license?: string; licenseUrl?: string; author?: string; sourceUrl?: string; provider?: string;
  // ai
  generator?: string; model?: string; prompt?: string;
  // common
  verified?: boolean; verifyConfidence?: number;
  /** An optional precomputed attribution line (e.g. from buildAttribution) to prefer. */
  attribution?: string;
}): ImageProvenance {
  const p: ImageProvenance = { kind: input.kind, attribution: '' };
  if (input.title) p.title = clip(input.title, 200);
  if (input.kind === 'web') {
    if (input.license) p.license = clip(input.license, 60);
    if (input.licenseUrl) p.licenseUrl = clip(input.licenseUrl, 500);
    if (input.author) p.author = clip(input.author, 120);
    if (input.sourceUrl) p.sourceUrl = clip(input.sourceUrl, 500);
    if (input.provider) p.provider = clip(input.provider, 40);
  } else {
    // Brand-neutral default; a consuming app passes its own product name as `generator`.
    p.generator = clip(input.generator || 'weaveintel', 60);
    if (input.model) p.model = clip(input.model, 80);
    if (input.prompt) p.prompt = clip(input.prompt, 1000);
  }
  if (typeof input.verified === 'boolean') p.verified = input.verified;
  if (typeof input.verifyConfidence === 'number') p.verifyConfidence = Math.max(0, Math.min(1, input.verifyConfidence));
  p.attribution = input.attribution?.trim() || provenanceCreditLine(p);
  return p;
}

/** A human credit/credentials line for a provenance manifest. */
export function provenanceCreditLine(p: ImageProvenance): string {
  if (p.kind === 'web') {
    const bits = [`‘${p.title || 'Image'}’`];
    if (p.author) bits.push(`by ${p.author}`);
    if (p.license) bits.push(`— ${p.license.toUpperCase()}`);
    if (p.provider) bits.push(`(via ${p.provider})`);
    return bits.join(' ');
  }
  const who = p.generator || 'AI';
  const model = p.model ? ` (${p.model})` : '';
  return `Generated by ${who}${model}`;
}

function xmlEscape(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c]!));
}

const PROV_JSON_OPEN = '<!--gw-provenance:';
const PROV_JSON_CLOSE = '-->';

/**
 * Render a small XMP/Dublin-Core packet for the manifest: dc:title/creator/rights, the licence URL
 * (xmpRights:WebStatement) and an explicit AI-generated assertion for AI images. Also appends a
 * machine-readable JSON comment so we can round-trip the exact manifest.
 */
export function provenanceToXmp(p: ImageProvenance): string {
  const rights = p.kind === 'web'
    ? `${p.license ? p.license.toUpperCase() + ' ' : ''}${p.author ? '© ' + p.author : ''}`.trim()
    : `Generated by ${p.generator || 'AI'}${p.model ? ' / ' + p.model : ''}`;
  const lines = [
    `<x:xmpmeta xmlns:x="adobe:ns:meta/">`,
    ` <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xmpRights="http://ns.adobe.com/xap/1.0/rights/">`,
    `  <rdf:Description>`,
    p.title ? `   <dc:title>${xmlEscape(p.title)}</dc:title>` : '',
    p.author ? `   <dc:creator>${xmlEscape(p.author)}</dc:creator>` : '',
    rights ? `   <dc:rights>${xmlEscape(rights)}</dc:rights>` : '',
    p.licenseUrl ? `   <xmpRights:WebStatement>${xmlEscape(p.licenseUrl)}</xmpRights:WebStatement>` : '',
    p.kind !== 'web' ? `   <dc:description>AI-generated image (Content Credentials)</dc:description>` : '',
    `  </rdf:Description>`,
    ` </rdf:RDF>`,
    `</x:xmpmeta>`,
  ].filter(Boolean);
  // The JSON comment is the load-bearing round-trip channel (XMP is for external tools).
  return `${lines.join('\n')}\n${PROV_JSON_OPEN}${JSON.stringify(p)}${PROV_JSON_CLOSE}`;
}

/**
 * Embed the provenance manifest INTO an SVG's bytes as a `<metadata>` element (valid SVG; ignored by
 * renderers, read by tools + by `parseProvenanceFromSvg`). Idempotent-ish: a prior gw metadata block
 * is replaced. Returns the SVG unchanged if it has no `<svg …>` root.
 */
export function embedXmpInSvg(svg: string, p: ImageProvenance): string {
  if (typeof svg !== 'string' || !/<svg[\s>]/i.test(svg)) return svg;
  const stripped = svg.replace(/<metadata id="gw-provenance">[\s\S]{0,50000}?<\/metadata>/i, '');
  const block = `<metadata id="gw-provenance">\n${provenanceToXmp(p)}\n</metadata>`;
  // Insert right after the opening <svg ...> tag.
  return stripped.replace(/(<svg[^>]*>)/i, `$1${block}`);
}

/** Read the embedded provenance manifest back out of an SVG (from the JSON comment). Null if absent. */
export function parseProvenanceFromSvg(svg: string): ImageProvenance | null {
  if (typeof svg !== 'string') return null;
  const start = svg.indexOf(PROV_JSON_OPEN);
  if (start === -1) return null;
  const from = start + PROV_JSON_OPEN.length;
  const end = svg.indexOf(PROV_JSON_CLOSE, from);
  if (end === -1) return null;
  try {
    const obj = JSON.parse(svg.slice(from, end)) as ImageProvenance;
    return obj && typeof obj === 'object' && typeof obj.kind === 'string' ? obj : null;
  } catch { return null; }
}
