import { defineSkill, type SkillDefinition } from './types.js';

export const BUILT_IN_SKILLS: SkillDefinition[] = [
  defineSkill({
    id: 'skill-investigation-brief',
    name: 'Investigation Briefing',
    version: '2.0',
    category: 'analysis',
    summary: 'Turn a complex problem into a concise diagnostic brief with hypotheses, evidence, and clear next checks.',
    purpose: 'Help models reason transparently when debugging incidents, regressions, and architecture tradeoffs.',
    whenToUse: 'Use for bug triage, architecture reviews, and failure analysis where evidence and uncertainty should both be explicit.',
    whenNotToUse: 'Avoid for trivial factual requests where no multi-step reasoning is needed.',
    requiredContext: 'Include observed behavior, expected behavior, constraints, and known signals from logs/tests.',
    reasoningGuidance: 'Generate plausible hypotheses, rank by likelihood, gather confirming/disconfirming evidence, then converge.',
    executionGuidance: 'Keep analysis grounded in observed artifacts. Do not claim certainty without concrete evidence.',
    outputGuidance: 'Return: findings, confidence per finding, gaps, and immediate next actions.',
    completionGuidance: 'Done means top issues are identified, evidence is cited, and ambiguity is explicitly surfaced.',
    ambiguityGuidance: 'If evidence conflicts, mark ambiguous and request additional validation.',
    failureGuidance: 'If blocked, state what data is missing and how to collect it.',
    toolNames: ['text_analysis', 'json_format'],
    policy: {
      allowedTools: ['text_analysis', 'json_format'],
      sideEffectsAllowed: false,
      requiresApproval: false,
      sensitivityHandling: 'Avoid exposing secrets in summaries.',
    },
    completionContract: {
      narrative: 'Identify probable root causes, confidence, and explicit evidence before recommending actions.',
      requiredEvidence: ['evidence', 'confidence'],
      humanReviewWhen: 'When the recommendation could change production behavior.',
    },
    tags: ['debugging', 'investigation', 'analysis'],
    triggerPatterns: [],
    examples: [
      {
        input: 'API suddenly returns 401 in compliance routes after refactor.',
        output: 'Finding: auth middleware path mismatch likely introduced. Evidence: auth tests pass, compliance suite fails with 401. Confidence: medium. Next check: compare route registration + permission guard wiring.',
      },
    ],
  }),
  defineSkill({
    id: 'skill-structured-extraction',
    name: 'Structured Evidence Extraction',
    version: '2.0',
    category: 'extraction',
    summary: 'Extract required entities and evidence from noisy text into a deterministic schema while preserving ambiguity.',
    purpose: 'Support workflows that need machine-consumable outputs and confidence-aware extraction behavior.',
    whenToUse: 'Use for compliance checks, data normalization, and pipeline handoffs that require explicit fields.',
    whenNotToUse: 'Avoid when user only needs conversational summaries.',
    requiredContext: 'Provide schema goals, constraints, and examples of valid outputs.',
    executionGuidance: 'Prefer faithful extraction over inference; if uncertain, flag ambiguity instead of fabricating data.',
    outputGuidance: 'Return structured JSON with extracted values, confidence, and evidence spans.',
    completionGuidance: 'Complete only when required fields are populated or explicitly marked missing with reasons.',
    ambiguityGuidance: 'Use `ambiguous` state when evidence is conflicting or missing.',
    failureGuidance: 'Return blocked state and missing context checklist if input is insufficient.',
    toolNames: ['json_format'],
    policy: {
      allowedTools: ['json_format'],
      sideEffectsAllowed: false,
    },
    completionContract: {
      narrative: 'Populate required fields, include confidence, and cite evidence for each extracted claim.',
      requiredEvidence: ['confidence', 'evidence'],
    },
    triggerPatterns: [],
  }),
  defineSkill({
    id: 'skill-data-analysis-execution',
    name: 'Data Analysis Execution',
    version: '1.0',
    category: 'analysis',
    summary: 'Run dataset analysis and charting workflows in a dedicated Python sandbox with preloaded analytics libraries.',
    purpose: 'Route file analysis, charting, and dataframe-heavy tasks to an execution surface that already has the right libraries installed.',
    whenToUse: 'Use for CSV, Excel, JSON, Parquet, dataframe analysis, chart generation, exploratory statistics, and code-backed data insights.',
    whenNotToUse: 'Avoid for plain prose summaries, lightweight arithmetic, or generic non-analysis scripting.',
    requiredContext: 'Include dataset filenames, expected metrics or chart types, and any output constraints such as grouping, date windows, or dimensions.',
    reasoningGuidance: 'Inspect the available data first, choose the smallest correct analysis plan, then execute and verify with concrete outputs.',
    executionGuidance: 'Use `cse_run_data_analysis` for analysis execution. Reuse the same session when iterating on the script, and only fall back to `cse_run_code` if the task is clearly not a data-analysis workflow.',
    outputGuidance: 'Return executed-code evidence, computed metrics, and concise insights grounded in stdout or structured results.',
    completionGuidance: 'Done means the code ran successfully, requested metrics were computed, and the answer includes concrete analysis or chart-ready data.',
    ambiguityGuidance: 'If required columns, files, or business definitions are missing, state the gap and either inspect the data shape or ask for the exact missing detail.',
    failureGuidance: 'If execution fails, correct the script and rerun. Only stop when the blocker is environmental or the input data is insufficient.',
    toolNames: ['cse_run_data_analysis', 'cse_session_status', 'cse_end_session', 'json_format', 'text_analysis'],
    policy: {
      allowedTools: ['cse_run_data_analysis', 'cse_session_status', 'cse_end_session', 'json_format', 'text_analysis'],
      disallowedTools: ['cse_run_code'],
      sideEffectsAllowed: false,
      requiresApproval: false,
    },
    completionContract: {
      narrative: 'Produce evidence-backed analysis from executed code and include explicit limitations when the data does not support a stronger conclusion.',
      requiredEvidence: ['evidence', 'confidence'],
    },
    // This skill executes data analysis directly via `cse_run_data_analysis`
    // (it does NOT require delegating to the `code_executor` worker). Declaring
    // an executionContract — even an empty one — is what signals to
    // `buildSupervisorInstructions` to suppress the generic
    // FORCED_WORKER_REQUIREMENT (2-step code_executor→analyst flow), which
    // otherwise conflicts with this skill's direct-execution plan.
    executionContract: {
      minDelegations: 0,
    },
    tags: ['analysis', 'data', 'charting', 'sandbox', 'auto-on-tabular'],
    triggerPatterns: ['analyze this csv', 'analyze this xlsx', 'analyze this spreadsheet', 'plot this data', 'chart this data', 'dataframe analysis', 'exploratory data analysis'],
  }),
  defineSkill({
    id: 'skill-tool-orchestrated-analysis',
    name: 'Tool-Orchestrated Analysis',
    version: '2.0',
    category: 'planning',
    summary: 'Plan and execute multi-step analysis that combines reasoning with governed tool usage.',
    purpose: 'Guide the model to choose tools deliberately, verify outputs, and report completion states safely.',
    whenToUse: 'Use when direct model reasoning is insufficient and tool outputs are required as evidence.',
    whenNotToUse: 'Avoid when policy forbids tool usage for the current context or tenant scope.',
    requiredContext: 'Provide task objective, tool availability, runtime budgets, and sensitivity constraints.',
    reasoningGuidance: 'Decide if tools are needed, sequence calls, verify outputs, then synthesize conclusions.',
    executionGuidance: 'Use the minimum required tool set and retry only with clear corrective intent.',
    outputGuidance: 'Report tool evidence, latency-sensitive caveats, and completion status.',
    completionGuidance: 'Done means output includes evidence-backed conclusion and explicit unresolved gaps.',
    failureGuidance: 'If a required tool is blocked, return blocked_by_policy with exact guard reason.',
    toolNames: ['web_search', 'calculator', 'json_format'],
    policy: {
      allowedTools: ['web_search', 'calculator', 'json_format'],
      disallowedTools: ['cse_run_code'],
      sideEffectsAllowed: false,
      requiresApproval: true,
      runtimeBudgetMs: 20000,
    },
    completionContract: {
      narrative: 'Evidence-backed answer with declared confidence and unresolved unknowns.',
      requiredEvidence: ['evidence', 'confidence'],
      humanReviewWhen: 'Recommendations involve external actions or policy exceptions.',
    },
    triggerPatterns: [],
  }),
];
