import type { AdminTabDef } from '@weaveintel/core';

/**
 * Shared callable capability tabs (tools/skills/worker-agents) are isolated so
 * multiple app surfaces can reuse consistent LLM-facing metadata fields.
 */
export const CALLABLE_CAPABILITY_ADMIN_TABS: Record<string, AdminTabDef> = {
  'tool-catalog': {
    singular: 'Tool', apiPath: 'admin/tool-catalog', listKey: 'tools',
    cols: ['name', 'tool_key', 'category', 'risk_level', 'source', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Detailed Description (model-facing)' },
      { key: 'tool_key', label: 'Tool Key (unique, read-only for builtins)' },
      { key: 'category', label: 'Category' },
      { key: 'risk_level', label: 'Risk Level', options: ['read-only', 'write', 'destructive', 'privileged', 'financial', 'external-side-effect'], default: 'read-only' },
      { key: 'side_effects', label: 'Has Side Effects', type: 'checkbox', save: 'bool' },
      { key: 'requires_approval', label: 'Requires Approval', type: 'checkbox', save: 'bool' },
      { key: 'version', label: 'Version', default: '1.0' },
      { key: 'source', label: 'Source', options: ['builtin', 'custom', 'mcp', 'plugin'], default: 'custom' },
      { key: 'tags', label: 'Tags (JSON array, optional)', textarea: true, rows: 2, save: 'json' },
      { key: 'max_execution_ms', label: 'Max Execution (ms)', type: 'number', save: 'int' },
      { key: 'rate_limit_per_min', label: 'Rate Limit/min', type: 'number', save: 'int' },
      { key: 'credential_id', label: 'Credential ID (optional)' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'tool-policies': {
    singular: 'Tool Policy', apiPath: 'admin/tool-policies', listKey: 'policies',
    cols: ['key', 'name', 'approval_required', 'rate_limit_per_minute', 'enabled'],
    fields: [
      { key: 'key', label: 'Policy Key (unique identifier, used in skill tool_policy_key)' },
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description (when to apply this policy)', textarea: true, rows: 3 },
      { key: 'applies_to', label: 'Applies To (JSON array of tool names / wildcards)', textarea: true, rows: 2, save: 'json' },
      { key: 'applies_to_risk_levels', label: 'Applies To Risk Levels (JSON array)', textarea: true, rows: 2, save: 'json' },
      { key: 'allowed_risk_levels', label: 'Allowed Risk Levels (JSON array)', textarea: true, rows: 2, save: 'json' },
      { key: 'approval_required', label: 'Approval Required', type: 'checkbox', save: 'bool' },
      { key: 'rate_limit_per_minute', label: 'Rate Limit / min', type: 'number', save: 'int' },
      { key: 'max_execution_ms', label: 'Max Execution (ms)', type: 'number', save: 'int' },
      { key: 'max_concurrent', label: 'Max Concurrent', type: 'number', save: 'int' },
      { key: 'require_dry_run', label: 'Require Dry Run', type: 'checkbox', save: 'bool' },
      { key: 'log_input_output', label: 'Log I/O', type: 'checkbox', save: 'bool', default: true },
      { key: 'persona_scope', label: 'Persona Scope (JSON array of persona strings)', textarea: true, rows: 2, save: 'json' },
      { key: 'active_hours_utc', label: 'Active Hours UTC (JSON { "start":"HH:MM","end":"HH:MM" })', textarea: true, rows: 2, save: 'json' },
      { key: 'expires_at', label: 'Expires At (ISO datetime, optional)' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'tool-audit': {
    singular: 'Tool Audit Event', apiPath: 'admin/tool-audit', listKey: 'events',
    readOnly: true,
    cols: ['tool_name', 'outcome', 'duration_ms', 'chat_id', 'created_at'],
    fields: [
      { key: 'id', label: 'Event ID', readonly: true },
      { key: 'tool_name', label: 'Tool Name', readonly: true },
      { key: 'outcome', label: 'Outcome', readonly: true },
      { key: 'violation_reason', label: 'Violation Reason', readonly: true },
      { key: 'duration_ms', label: 'Duration (ms)', readonly: true },
      { key: 'chat_id', label: 'Chat ID', readonly: true },
      { key: 'user_id', label: 'User ID', readonly: true },
      { key: 'agent_persona', label: 'Agent Persona', readonly: true },
      { key: 'skill_key', label: 'Skill Key', readonly: true },
      { key: 'policy_id', label: 'Policy ID', readonly: true },
      { key: 'input_preview', label: 'Input Preview', readonly: true, textarea: true, rows: 3 },
      { key: 'output_preview', label: 'Output Preview', readonly: true, textarea: true, rows: 3 },
      { key: 'error_message', label: 'Error Message', readonly: true },
      { key: 'created_at', label: 'Created At', readonly: true },
    ],
  },
  'tool-health': {
    singular: 'Tool Health', apiPath: 'admin/tool-health', listKey: 'summary',
    readOnly: true,
    cols: ['tool_name', 'total_invocations', 'availability', 'error_rate', 'avg_duration_ms', 'last_invoked_at'],
    fields: [
      { key: 'tool_name', label: 'Tool Name', readonly: true },
      { key: 'total_invocations', label: 'Total Invocations (24h)', readonly: true },
      { key: 'success_count', label: 'Success', readonly: true },
      { key: 'error_count', label: 'Errors', readonly: true },
      { key: 'denied_count', label: 'Denied', readonly: true },
      { key: 'avg_duration_ms', label: 'Avg Latency (ms)', readonly: true },
      { key: 'error_rate', label: 'Error Rate', readonly: true },
      { key: 'availability', label: 'Availability', readonly: true },
      { key: 'last_invoked_at', label: 'Last Invoked', readonly: true },
    ],
  },
  'skills': {
    singular: 'Skill', apiPath: 'admin/skills', listKey: 'skills',
    cols: ['name', 'category', 'priority', 'version', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Purpose & Summary (model-facing)', textarea: true, rows: 4 },
      { key: 'category', label: 'Category', options: ['retrieval', 'computation', 'communication', 'data-processing', 'planning', 'analysis', 'code', 'web', 'general'], default: 'general' },
      { key: 'instructions', label: 'Skill Playbook (when to use, when not to use, reasoning, execution, completion)', textarea: true, rows: 10 },
      { key: 'examples', label: 'Examples (JSON array, optional)', textarea: true, rows: 4, save: 'json' },
      { key: 'tool_names', label: 'Allowed Tool Guidance (JSON array, optional)', textarea: true, rows: 3, save: 'json' },
      { key: 'tags', label: 'Semantic Hints (JSON array, optional)', textarea: true, rows: 2, save: 'json' },
      { key: 'trigger_patterns', label: 'Legacy Trigger Hints (optional, semantic activation is primary)', textarea: true, rows: 2, save: 'json' },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'version', label: 'Version', default: '1.0' },
      { key: 'prompt_id', label: 'Prompt ID (optional)' },
      { key: 'prompt_version', label: 'Prompt Version (optional)' },
      { key: 'prompt_strategy', label: 'Prompt Strategy (optional)' },
      { key: 'prompt_variables', label: 'Prompt Variables (JSON object)', textarea: true, rows: 3, save: 'json' },
      { key: 'contract_key', label: 'Contract Key (optional)' },
      { key: 'eval_policy_key', label: 'Eval Policy Key (optional)' },
      { key: 'tool_policy_key', label: 'Tool Policy Key (optional)' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'worker-agents': {
    singular: 'Worker Agent', apiPath: 'admin/worker-agents', listKey: 'workerAgents',
    cols: ['name', 'persona', 'priority', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Detailed Description (model-facing)' },
      { key: 'system_prompt', label: 'System Prompt', textarea: true, rows: 6 },
      { key: 'tool_names', label: 'Tool Names (JSON array)', textarea: true, rows: 3, save: 'json' },
      { key: 'persona', label: 'Persona', options: ['agent_worker', 'agent_researcher', 'agent_supervisor'], default: 'agent_worker' },
      { key: 'trigger_patterns', label: 'Trigger Patterns (JSON array)', textarea: true, rows: 3, save: 'json' },
      { key: 'task_contract_id', label: 'Task Contract ID (optional)' },
      { key: 'max_retries', label: 'Max Retries', type: 'number', save: 'int', default: 0 },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'tool-credentials': {
    singular: 'Tool Credential', apiPath: 'admin/tool-credentials', listKey: 'credentials',
    cols: ['name', 'credential_type', 'env_var_name', 'validation_status', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'credential_type', label: 'Credential Type', options: ['api_key', 'oauth_token', 'basic_auth', 'jwt', 'custom'], default: 'api_key' },
      { key: 'tool_names', label: 'Tool Names (JSON array of tool_key strings)', textarea: true, rows: 2, save: 'json' },
      { key: 'env_var_name', label: 'Env Var Name (holds the secret)' },
      { key: 'config', label: 'Config (JSON: headerName, prefix, etc.)', textarea: true, rows: 3, save: 'json' },
      { key: 'rotation_due_at', label: 'Rotation Due At (ISO datetime, optional)' },
      { key: 'validation_status', label: 'Validation Status', readonly: true },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'tool-simulation': {
    singular: 'Tool Simulation', apiPath: 'admin/tool-simulation', listKey: 'tools',
    cols: ['name', 'source', 'description'],
    fields: [],
    readOnly: true,
    customView: 'tool-simulation',
  },
  'tool-approval-requests': {
    singular: 'Tool Approval Request', apiPath: 'admin/tool-approval-requests', listKey: 'requests',
    readOnly: true,
    customView: 'tool-approval-requests',
    cols: ['tool_name', 'status', 'chat_id', 'skill_key', 'requested_at'],
    fields: [],
  },
};
