import type { AdminTabDef } from '@weaveintel/core';

/**
 * Platform capability tabs (governance, integrations, infra, monitoring, etc.)
 * are isolated to keep the root admin schema file focused on composition.
 */
export const PLATFORM_CAPABILITY_ADMIN_TABS: Record<string, AdminTabDef> = {
  'users': {
    singular: 'User', apiPath: 'admin/users', listKey: 'users',
    cols: ['email', 'name', 'persona', 'tenant_id', 'created_at'],
    fields: [
      { key: 'email', label: 'Email' },
      { key: 'name', label: 'Name' },
      { key: 'persona', label: 'Persona', options: ['platform_admin', 'tenant_admin', 'tenant_user', 'agent_worker', 'agent_researcher', 'agent_supervisor'], default: 'tenant_user' },
      { key: 'tenant_id', label: 'Tenant ID' },
      { key: 'password', label: 'Password (set on create/update)' },
      { key: 'created_at', label: 'Created At', readonly: true },
    ],
  },
  'guardrails': {
    singular: 'Guardrail', apiPath: 'admin/guardrails', listKey: 'guardrails',
    cols: ['name', 'type', 'stage', 'enabled', 'trigger_description'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'type', label: 'Type', options: ['content_filter', 'redaction', 'pii_detection', 'budget', 'factuality', 'cognitive_check', 'topic_guard', 'toxicity', 'custom'] },
      { key: 'stage', label: 'Stage', options: ['pre', 'post', 'both'], default: 'pre' },
      { key: 'config', label: 'Config (JSON)', textarea: true, save: 'json' },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
      { key: 'trigger_description', label: 'Trigger Description (when does this guardrail run?)' },
      { key: 'trigger_preset', label: 'Trigger Preset', options: ['always', 'agent_mode', 'elevated_situation', 'anonymous_user', 'factual_output', 'validation_seeking', 'long_input', 'suspicious_input'], default: 'always' },
      { key: 'trigger_conditions', label: 'Trigger Conditions JSON (advanced — overrides preset)', textarea: true, save: 'json' },
    ],
  },
  'routing': {
    singular: 'Routing Policy', apiPath: 'admin/routing', listKey: 'policies',
    cols: ['name', 'strategy', 'fallback_model', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'strategy', label: 'Strategy', options: ['balanced', 'cost_optimized', 'latency_optimized', 'quality_first', 'custom'], default: 'balanced' },
      { key: 'constraints', label: 'Constraints (JSON)', textarea: true, save: 'json' },
      { key: 'weights', label: 'Weights (JSON)', textarea: true, save: 'json' },
      { key: 'fallback_model', label: 'Fallback Model' },
      { key: 'fallback_provider', label: 'Fallback Provider' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'model-pricing': {
    singular: 'Model Pricing', apiPath: 'admin/model-pricing', listKey: 'pricing',
    cols: ['model_id', 'provider', 'display_name', 'input_cost_per_1m', 'output_cost_per_1m', 'quality_score', 'source', 'enabled'],
    fields: [
      { key: 'model_id', label: 'Model ID' },
      { key: 'provider', label: 'Provider', options: ['openai', 'anthropic'] },
      { key: 'display_name', label: 'Display Name' },
      { key: 'input_cost_per_1m', label: 'Input Cost / 1M tokens', type: 'number', save: 'float' },
      { key: 'output_cost_per_1m', label: 'Output Cost / 1M tokens', type: 'number', save: 'float' },
      { key: 'quality_score', label: 'Quality Score (0-1)', type: 'number', save: 'float', default: 0.5 },
      { key: 'prompt_cache_enabled', label: 'Prompt Caching Enabled', type: 'checkbox', save: 'bool', default: true },
      { key: 'prompt_cache_min_tokens', label: 'Prompt Cache Min Tokens', type: 'number', save: 'int', default: 1024 },
      { key: 'prompt_cache_ttl', label: 'Prompt Cache TTL', options: ['5m', '1h'], default: '5m' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'workflows': {
    singular: 'Workflow', apiPath: 'admin/workflows', listKey: 'workflows',
    cols: ['name', 'version', 'entry_step_id', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'version', label: 'Version', default: '1.0' },
      { key: 'steps', label: 'Steps (JSON)', textarea: true, rows: 4, save: 'json' },
      { key: 'entry_step_id', label: 'Entry Step ID' },
      { key: 'metadata', label: 'Metadata (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'task-policies': {
    singular: 'Task Policy', apiPath: 'admin/task-policies', listKey: 'taskPolicies',
    cols: ['name', 'task_type', 'default_priority', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'trigger', label: 'Trigger' },
      { key: 'task_type', label: 'Task Type', options: ['approval', 'review', 'generation', 'classification'], default: 'approval' },
      { key: 'default_priority', label: 'Priority', options: ['low', 'normal', 'high', 'critical'], default: 'normal' },
      { key: 'sla_hours', label: 'SLA Hours', type: 'number', save: 'float' },
      { key: 'auto_escalate_after_hours', label: 'Auto-escalate (hours)', type: 'number', save: 'float' },
      { key: 'assignment_strategy', label: 'Assignment', options: ['round-robin', 'least-busy', 'manual'], default: 'round-robin' },
      { key: 'assign_to', label: 'Assign To' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'contracts': {
    singular: 'Contract', apiPath: 'admin/contracts', listKey: 'contracts',
    cols: ['name', 'max_attempts', 'min_confidence', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'input_schema', label: 'Input Schema (JSON)', textarea: true },
      { key: 'output_schema', label: 'Output Schema (JSON)', textarea: true },
      { key: 'acceptance_criteria', label: 'Acceptance Criteria (JSON)', textarea: true, default: '[]' },
      { key: 'max_attempts', label: 'Max Attempts', type: 'number', save: 'int' },
      { key: 'timeout_ms', label: 'Timeout (ms)', type: 'number', save: 'int' },
      { key: 'evidence_required', label: 'Evidence Required', textarea: true },
      { key: 'min_confidence', label: 'Min Confidence', type: 'number', save: 'float' },
      { key: 'require_human_review', label: 'Human Review', type: 'checkbox', save: 'bool' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'identity-rules': {
    singular: 'Identity Rule', apiPath: 'admin/identity-rules', listKey: 'identity-rules',
    cols: ['name', 'resource', 'action', 'result', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'resource', label: 'Resource', default: '*' },
      { key: 'action', label: 'Action', default: '*' },
      { key: 'roles', label: 'Roles (JSON)', textarea: true, save: 'json' },
      { key: 'scopes', label: 'Scopes (JSON)', textarea: true, save: 'json' },
      { key: 'result', label: 'Result', options: ['allow', 'deny'], default: 'allow' },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'memory-governance': {
    singular: 'Memory Governance Rule', apiPath: 'admin/memory-governance', listKey: 'memory-governance',
    cols: ['name', 'description', 'max_age', 'max_entries', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description', textarea: true, rows: 2 },
      {
        key: 'memory_types',
        label: 'Memory Types — which types this rule applies to (JSON array, leave blank for all types)',
        save: 'json',
        textarea: true,
        rows: 2,
        placeholder: '["episodic","semantic","entity","procedural","working"]',
        helpText: 'Valid types: episodic · semantic · entity · procedural · working. Leave blank (null) to apply to all types.',
      },
      { key: 'tenant_id', label: 'Tenant ID (optional — blank = global, applies to all tenants)' },
      {
        key: 'block_patterns',
        label: 'Block Patterns — if ANY pattern matches the entry content, shouldStore() returns false and the entry is discarded (JSON regex array)',
        textarea: true, rows: 3, save: 'json',
        placeholder: '["\\\\b\\\\d{3}-\\\\d{2}-\\\\d{4}\\\\b"]',
      },
      {
        key: 'redact_patterns',
        label: 'Redact Patterns — all matches are replaced with [REDACTED] before storing (JSON regex array)',
        textarea: true, rows: 3, save: 'json',
        placeholder: '["(?:password|api_key|secret)\\\\s*[=:]\\\\s*\\\\S+"]',
      },
      {
        key: 'max_age', label: 'Max Age — entries older than this are eligible for purge (ISO 8601 duration)',
        options: ['', 'P7D', 'P30D', 'P90D', 'P180D', 'P1Y'],
        default: '',
        helpText: 'P7D = 7 days · P30D = 30 days · P180D = 180 days · P1Y = 1 year · blank = no age limit',
      },
      { key: 'max_entries', label: 'Max Entries per User — entries beyond this cap are pruned (lowest importance first)', type: 'number', save: 'int' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'memory-extraction-rules': {
    singular: 'Memory Extraction Rule', apiPath: 'admin/memory-extraction-rules', listKey: 'memory-extraction-rules',
    cols: ['name', 'rule_type', 'entity_type', 'priority', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description', textarea: true, rows: 2 },
      { key: 'rule_type', label: 'Rule Type', options: ['self_disclosure', 'entity_extraction'], default: 'entity_extraction' },
      { key: 'entity_type', label: 'Entity Type', options: ['', 'person', 'location', 'organization', 'preference', 'topic', 'general'], default: 'general' },
      { key: 'pattern', label: 'Regex Pattern', textarea: true, rows: 3 },
      { key: 'flags', label: 'Regex Flags (i=case-insensitive, g=global, m=multiline)', options: ['i', 'g', 'gi', 'm'], default: 'i' },
      { key: 'facts_template', label: 'Facts Template (JSON — e.g. {"name": "$1"})', textarea: true, save: 'json', rows: 3 },
      { key: 'priority', label: 'Priority (0–100, higher runs first)', type: 'number', save: 'int', default: 0 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'semantic-memory': {
    singular: 'Semantic Memory Entry', apiPath: 'admin/semantic-memory', listKey: 'semantic-memory',
    readOnly: true,
    cols: ['user_id', 'memory_type', 'source', 'content', 'created_at'],
    fields: [
      { key: 'user_id', label: 'User ID', readonly: true },
      { key: 'chat_id', label: 'Chat ID', readonly: true },
      { key: 'memory_type', label: 'Memory Type', readonly: true },
      { key: 'source', label: 'Source', readonly: true },
      { key: 'content', label: 'Content', textarea: true, rows: 4, readonly: true },
      { key: 'created_at', label: 'Created At', readonly: true },
    ],
  },
  'entity-memory': {
    singular: 'Entity Memory', apiPath: 'admin/entity-memory', listKey: 'entity-memory',
    readOnly: true,
    cols: ['user_id', 'entity_name', 'entity_type', 'confidence', 'updated_at'],
    fields: [
      { key: 'user_id', label: 'User ID', readonly: true },
      { key: 'entity_name', label: 'Entity Name', readonly: true },
      { key: 'entity_type', label: 'Entity Type', readonly: true },
      { key: 'facts', label: 'Facts (JSON)', textarea: true, rows: 4, readonly: true },
      { key: 'confidence', label: 'Confidence', readonly: true },
      { key: 'source', label: 'Source', readonly: true },
      { key: 'updated_at', label: 'Last Updated', readonly: true },
    ],
  },
  'memory-extraction-events': {
    singular: 'Memory Extraction Event', apiPath: 'admin/memory-extraction-events', listKey: 'memory-extraction-events',
    readOnly: true,
    cols: ['user_id', 'self_disclosure', 'regex_entities_count', 'llm_entities_count', 'merged_entities_count', 'created_at'],
    fields: [
      { key: 'user_id', label: 'User ID', readonly: true },
      { key: 'chat_id', label: 'Chat ID', readonly: true },
      { key: 'self_disclosure', label: 'Self-Disclosure Detected', readonly: true },
      { key: 'regex_entities_count', label: 'Regex Entities', readonly: true },
      { key: 'llm_entities_count', label: 'LLM Entities', readonly: true },
      { key: 'merged_entities_count', label: 'Merged Entities', readonly: true },
      { key: 'events', label: 'Events (JSON)', textarea: true, rows: 5, readonly: true },
      { key: 'created_at', label: 'Created At', readonly: true },
    ],
  },
  'episodic-memory': {
    singular: 'Episodic Memory Event', apiPath: 'admin/episodic-memory', listKey: 'episodic-memory',
    readOnly: true,
    cols: ['user_id', 'message_role', 'importance', 'consolidated', 'content', 'created_at'],
    fields: [
      { key: 'user_id', label: 'User ID', readonly: true },
      { key: 'chat_id', label: 'Chat ID', readonly: true },
      { key: 'message_role', label: 'Message Role', readonly: true },
      { key: 'importance', label: 'Importance (0–1)', readonly: true },
      { key: 'consolidated', label: 'Consolidated', readonly: true },
      { key: 'tags', label: 'Tags (JSON)', readonly: true },
      { key: 'content', label: 'Content', textarea: true, rows: 4, readonly: true },
      { key: 'created_at', label: 'Created At', readonly: true },
    ],
  },
  'procedural-memory': {
    singular: 'Procedural Memory Entry', apiPath: 'admin/procedural-memory', listKey: 'procedural-memory',
    cols: ['user_id', 'agent_id', 'status', 'proposed_by', 'confidence', 'created_at'],
    fields: [
      { key: 'user_id', label: 'User ID' },
      { key: 'agent_id', label: 'Agent ID (use "default" for the global agent)', default: 'default' },
      {
        key: 'instruction_delta',
        label: 'Instruction Delta — what the agent should learn (e.g. "User prefers concise bullet-point answers")',
        textarea: true, rows: 4,
      },
      {
        key: 'proposed_by', label: 'Proposed By',
        options: ['admin', 'agent', 'consolidation-curator', 'user-feedback'],
        default: 'admin',
      },
      {
        key: 'status', label: 'Status',
        options: ['proposed', 'approved', 'rejected', 'applied'],
        default: 'proposed',
      },
      { key: 'confidence', label: 'Confidence (0–1)', type: 'number', save: 'float', default: 0.8 },
      { key: 'applied_at', label: 'Applied At', readonly: true },
      { key: 'created_at', label: 'Created At', readonly: true },
    ],
  },
  'working-memory': {
    singular: 'Working Memory Snapshot', apiPath: 'admin/working-memory', listKey: 'working-memory',
    readOnly: true,
    cols: ['user_id', 'agent_id', 'chat_id', 'created_at'],
    fields: [
      { key: 'user_id', label: 'User ID', readonly: true },
      { key: 'chat_id', label: 'Chat ID (the session the agent was running in)', readonly: true },
      { key: 'agent_id', label: 'Agent ID', readonly: true },
      { key: 'content', label: 'Working State (JSON — serialised agent scratch state saved via memory_snapshot tool)', textarea: true, rows: 8, readonly: true },
      { key: 'created_at', label: 'Saved At', readonly: true },
    ],
  },
  'memory-settings': {
    singular: 'Memory Settings', apiPath: 'admin/memory-settings', listKey: 'memory-settings',
    cols: ['tenant_id', 'enable_semantic', 'enable_episodic', 'enable_procedural', 'auto_extract_on_turn', 'consolidation_enabled'],
    fields: [
      {
        key: 'tenant_id',
        label: 'Tenant ID (blank = global default — applies to all tenants without a specific override)',
        default: '',
      },
      {
        key: 'enable_semantic', label: 'Enable Semantic Memory',
        type: 'checkbox', save: 'bool', default: true,
      },
      {
        key: 'enable_entity', label: 'Enable Entity Memory (structured profile facts)',
        type: 'checkbox', save: 'bool', default: true,
      },
      {
        key: 'enable_episodic', label: 'Enable Episodic Memory (per-turn conversation events)',
        type: 'checkbox', save: 'bool', default: true,
      },
      {
        key: 'enable_procedural', label: 'Enable Procedural Memory (agent instruction deltas)',
        type: 'checkbox', save: 'bool', default: true,
      },
      {
        key: 'enable_working', label: 'Enable Working Memory (in-session agent scratch state)',
        type: 'checkbox', save: 'bool', default: true,
      },
      {
        key: 'auto_extract_on_turn', label: 'Auto-Extract on Every Turn (run extraction pipeline after each message)',
        type: 'checkbox', save: 'bool', default: true,
      },
      {
        key: 'consolidation_enabled', label: 'Consolidation Enabled (background episodic → semantic distillation)',
        type: 'checkbox', save: 'bool', default: true,
      },
      {
        key: 'consolidation_interval_min', label: 'Consolidation Interval (minutes)',
        type: 'number', save: 'int', default: 60,
        options: ['15', '30', '60', '120', '360', '720', '1440'],
      },
      { key: 'max_episodic_per_user', label: 'Max Episodic Entries per User', type: 'number', save: 'int', default: 200 },
      { key: 'max_semantic_per_user', label: 'Max Semantic Entries per User', type: 'number', save: 'int', default: 500 },
      { key: 'max_entity_per_user', label: 'Max Entity Entries per User', type: 'number', save: 'int', default: 100 },
      { key: 'updated_at', label: 'Last Updated', readonly: true },
    ],
  },
  'compliance-rules': {
    singular: 'Compliance Rule', apiPath: 'admin/compliance-rules', listKey: 'compliance-rules',
    cols: ['name', 'rule_type', 'target_resource', 'action', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'rule_type', label: 'Rule Type', options: ['retention', 'deletion', 'legal-hold', 'consent', 'residency'], default: 'retention' },
      { key: 'target_resource', label: 'Target Resource', default: '*' },
      { key: 'retention_days', label: 'Retention Days', type: 'number', save: 'int' },
      { key: 'region', label: 'Region' },
      { key: 'consent_purpose', label: 'Consent Purpose' },
      { key: 'action', label: 'Action', options: ['archive', 'delete', 'notify', 'block', 'encrypt'], default: 'notify' },
      { key: 'config', label: 'Config (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'search-providers': {
    singular: 'Search Provider', apiPath: 'admin/search-providers', listKey: 'search-providers',
    cols: ['name', 'provider_type', 'priority', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'provider_type', label: 'Provider Type', options: ['duckduckgo', 'google', 'bing', 'brave', 'custom'], default: 'duckduckgo' },
      { key: 'api_key', label: 'API Key' },
      { key: 'base_url', label: 'Base URL' },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'options', label: 'Options (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'http-endpoints': {
    singular: 'HTTP Endpoint', apiPath: 'admin/http-endpoints', listKey: 'http-endpoints',
    cols: ['name', 'method', 'url', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'url', label: 'URL' },
      { key: 'method', label: 'Method', options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], default: 'GET' },
      { key: 'auth_type', label: 'Auth Type', options: ['none', 'bearer', 'basic', 'api-key', 'oauth'], default: 'none' },
      { key: 'auth_config', label: 'Auth Config (JSON)', textarea: true, save: 'json' },
      { key: 'headers', label: 'Headers (JSON)', textarea: true, save: 'json' },
      { key: 'body_template', label: 'Body Template', textarea: true },
      { key: 'response_transform', label: 'Response Transform', textarea: true },
      { key: 'retry_count', label: 'Retry Count', type: 'number', save: 'int', default: 0 },
      { key: 'rate_limit_rpm', label: 'Rate Limit RPM', type: 'number', save: 'int', default: 60 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'social-accounts': {
    singular: 'Social Account', apiPath: 'admin/social-accounts', listKey: 'social-accounts',
    cols: ['name', 'platform', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'platform', label: 'Platform', options: ['slack', 'discord', 'telegram', 'twitter', 'mastodon', 'linkedin', 'instagram', 'facebook', 'tiktok', 'medium', 'blogger'], default: 'linkedin' },
      { key: 'api_key', label: 'API Key' },
      { key: 'api_secret', label: 'API Secret' },
      { key: 'base_url', label: 'Base URL' },
      { key: 'options', label: 'Options (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'enterprise-connectors': {
    singular: 'Enterprise Connector', apiPath: 'admin/enterprise-connectors', listKey: 'enterprise-connectors',
    cols: ['name', 'connector_type', 'base_url', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'connector_type', label: 'Connector Type', options: ['jira', 'confluence', 'sharepoint', 'salesforce', 'servicenow', 'custom'], default: 'jira' },
      { key: 'base_url', label: 'Base URL' },
      { key: 'auth_type', label: 'Auth Type', options: ['bearer', 'basic', 'oauth', 'api-key'], default: 'bearer' },
      { key: 'auth_config', label: 'Auth Config (JSON)', textarea: true, save: 'json' },
      { key: 'options', label: 'Options (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'trigger-definitions': {
    singular: 'Trigger Definition', apiPath: 'admin/trigger-definitions', listKey: 'trigger-definitions',
    cols: ['name', 'trigger_type', 'status', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'trigger_type', label: 'Trigger Type', options: ['cron', 'webhook', 'event', 'manual'], default: 'cron' },
      { key: 'expression', label: 'Expression' },
      { key: 'config', label: 'Config (JSON)', textarea: true, save: 'json' },
      { key: 'target_workflow', label: 'Target Workflow' },
      { key: 'status', label: 'Status', options: ['active', 'paused', 'disabled'], default: 'active' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'replay-scenarios': {
    singular: 'Replay Scenario', apiPath: 'admin/replay-scenarios', listKey: 'replay-scenarios',
    cols: ['name', 'model', 'provider', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'golden_prompt', label: 'Golden Prompt', textarea: true, rows: 3 },
      { key: 'golden_response', label: 'Golden Response', textarea: true, rows: 3 },
      { key: 'model', label: 'Model' },
      { key: 'provider', label: 'Provider' },
      { key: 'tags', label: 'Tags (JSON)', textarea: true, save: 'json' },
      { key: 'acceptance_criteria', label: 'Acceptance Criteria (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'cache-policies': {
    singular: 'Cache Policy', apiPath: 'admin/cache-policies', listKey: 'cache-policies',
    cols: ['name', 'scope', 'ttl_ms', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'scope', label: 'Scope', options: ['global', 'tenant', 'user', 'session', 'agent'], default: 'global' },
      { key: 'ttl_ms', label: 'TTL (ms)', type: 'number', save: 'int', default: 300000 },
      { key: 'max_entries', label: 'Max Entries', type: 'number', save: 'int', default: 1000 },
      { key: 'max_bytes', label: 'Max Bytes (0 = off)', type: 'number', save: 'int', default: 0 },
      { key: 'key_hashing', label: 'Key Hashing', options: ['sha256', 'none'], default: 'sha256' },
      { key: 'tenant_isolation', label: 'Tenant Isolation', type: 'checkbox', save: 'bool', default: true },
      { key: 'cache_temperature_gate', label: 'Temperature Gate (cache when temp ≤)', type: 'number', save: 'float', default: 0 },
      { key: 'bypass_patterns', label: 'Bypass Patterns — prompt (JSON)', textarea: true, save: 'json' },
      { key: 'output_bypass_patterns', label: 'Bypass Patterns — response (JSON)', textarea: true, save: 'json' },
      { key: 'invalidate_on', label: 'Invalidate On (JSON)', textarea: true, save: 'json' },
      { key: 'swr_ms', label: 'Stale-While-Revalidate (ms, 0 = off)', type: 'number', save: 'int', default: 0 },
      { key: 'negative_ttl_ms', label: 'Negative TTL (ms, cache misses/errors, 0 = off)', type: 'number', save: 'int', default: 0 },
      { key: 'eviction_policy', label: 'Eviction Policy', options: ['lru', 'lfu', 'fifo', 'tinylfu', 'gdsf'], default: 'lru' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'cache-settings': {
    singular: 'Cache Settings', apiPath: 'admin/cache-settings', listKey: 'cache-settings',
    cols: ['stampede_protection', 'l1_eviction_policy', 'l1_max_entries', 'l2_enabled'],
    fields: [
      { key: 'stampede_protection', label: 'Stampede Protection (coalesce identical requests)', type: 'checkbox', save: 'bool', default: true },
      { key: 'l1_eviction_policy', label: 'L1 Eviction Policy', options: ['lru', 'lfu', 'fifo', 'tinylfu', 'gdsf'], default: 'lru' },
      { key: 'l1_negative_ttl_ms', label: 'Global Negative TTL (ms)', type: 'number', save: 'int', default: 0 },
      { key: 'l1_max_entries', label: 'L1 Max Entries', type: 'number', save: 'int', default: 5000 },
      { key: 'l1_max_bytes', label: 'L1 Max Bytes (0 = off)', type: 'number', save: 'int', default: 0 },
      { key: 'l1_ttl_ms', label: 'L1 Staleness Cap (ms)', type: 'number', save: 'int', default: 30000 },
      { key: 'l2_enabled', label: 'L2 (Redis) Enabled', type: 'checkbox', save: 'bool', default: false },
      { key: 'l2_provider', label: 'L2 Provider', options: ['none', 'redis'], default: 'none' },
      { key: 'key_namespace', label: 'Redis Key Prefix', default: 'weave:cache' },
      { key: 'global_version_token', label: 'Global Version Token (bump to invalidate all)', default: 'v1' },
      { key: 'metrics_enabled', label: 'Metrics Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'cache-invalidation-rules': {
    singular: 'Cache Invalidation Rule', apiPath: 'admin/cache-invalidation-rules', listKey: 'cache-invalidation-rules',
    cols: ['name', 'trigger', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'trigger', label: 'Trigger Event', options: ['model_change', 'prompt_update', 'knowledge_update', 'session_end', 'preference_change', 'manual'], default: 'prompt_update' },
      { key: 'pattern', label: 'Payload Pattern (regex, optional)' },
      { key: 'config', label: 'Config (JSON: clearAll / prefix / prefixFromPayload / scope)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'tool-cache-policies': {
    singular: 'Tool Cache Policy', apiPath: 'admin/tool-cache-policies', listKey: 'tool-cache-policies',
    cols: ['tool_name', 'cacheable', 'ttl_ms', 'enabled'],
    fields: [
      { key: 'tool_name', label: 'Tool Name' },
      { key: 'cacheable', label: 'Cacheable', type: 'checkbox', save: 'bool', default: true },
      { key: 'ttl_ms', label: 'TTL (ms)', type: 'number', save: 'int', default: 300000 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'agent-plan-cache-config': {
    singular: 'Agent Plan Cache Config', apiPath: 'admin/agent-plan-cache-config', listKey: 'agent-plan-cache-config',
    cols: ['enabled', 'similarity_threshold', 'min_steps', 'scope', 'ttl_ms'],
    fields: [
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
      { key: 'similarity_threshold', label: 'Reuse Threshold (0–1)', type: 'number', save: 'float', default: 0.86 },
      { key: 'min_steps', label: 'Min Steps to Cache a Plan', type: 'number', save: 'int', default: 2 },
      { key: 'max_entries', label: 'Max Entries', type: 'number', save: 'int', default: 1000 },
      { key: 'ttl_ms', label: 'TTL (ms)', type: 'number', save: 'int', default: 86400000 },
      { key: 'scope', label: 'Isolation Scope', options: ['global', 'tenant', 'user', 'session'], default: 'user' },
      { key: 'embedding_model', label: 'Embedding Model', default: 'text-embedding-3-small' },
    ],
  },
  'semantic-cache-config': {
    singular: 'Semantic Cache Config', apiPath: 'admin/semantic-cache-config', listKey: 'semantic-cache-config',
    cols: ['enabled', 'embedding_model', 'similarity_threshold', 'scope', 'ttl_ms', 'max_entries'],
    fields: [
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
      { key: 'embedding_model', label: 'Embedding Model', default: 'text-embedding-3-small' },
      { key: 'embedding_version', label: 'Embedding Version', default: 'v1' },
      { key: 'similarity_threshold', label: 'Similarity Threshold (0–1)', type: 'number', save: 'float', default: 0.92 },
      { key: 'invalidation_radius', label: 'Invalidation Radius (0–1)', type: 'number', save: 'float', default: 0.95 },
      { key: 'max_entries', label: 'Max Entries', type: 'number', save: 'int', default: 1000 },
      { key: 'ttl_ms', label: 'TTL (ms)', type: 'number', save: 'int', default: 600000 },
      { key: 'scope', label: 'Isolation Scope', options: ['global', 'tenant', 'user', 'session'], default: 'user' },
      { key: 'bypass_patterns', label: 'Bypass Patterns — time-sensitive (JSON)', textarea: true, save: 'json' },
      { key: 'verified_bounds', label: 'Verified Bounds (vCache)', type: 'checkbox', save: 'bool', default: false },
    ],
  },
  'run-stream-config': {
    singular: 'Run Stream Config', apiPath: 'admin/run-stream-config', listKey: 'run-stream-config',
    cols: ['enabled', 'heartbeat_ms', 'max_reconnects', 'stall_timeout_ms', 'journal_retention_hours', 'journal_max_events'],
    fields: [
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
      { key: 'heartbeat_ms', label: 'SSE Keepalive (ms)', type: 'number', save: 'int', default: 15000 },
      { key: 'max_reconnects', label: 'Max Client Reconnects', type: 'number', save: 'int', default: 8 },
      { key: 'backoff_ms', label: 'Reconnect Backoff (JSON ms array)', textarea: true, save: 'json' },
      { key: 'stall_timeout_ms', label: 'Stall Timeout (ms)', type: 'number', save: 'int', default: 60000 },
      { key: 'throttle_ms', label: 'Client UI Throttle (ms)', type: 'number', save: 'int', default: 50 },
      { key: 'journal_retention_hours', label: 'Journal Retention (hours)', type: 'number', save: 'int', default: 24 },
      { key: 'journal_max_events', label: 'Journal Max Events / Run', type: 'number', save: 'int', default: 2000 },
      { key: 'resume_window_seconds', label: 'Resume Window (seconds)', type: 'number', save: 'int', default: 900 },
    ],
  },
  'weavenotes-settings': {
    singular: 'weaveNotes Settings', plural: 'weaveNotes Settings', apiPath: 'admin/weavenotes-settings', listKey: 'weavenotes-settings',
    cols: ['default_theme', 'ai_suggestions_require_approval', 'activity_tracking_enabled', 'activity_retention_days', 'max_ai_tokens_per_edit', 'ai_rate_per_min_per_user'],
    fields: [
      { key: 'default_theme', label: 'Default theme', options: ['pro', 'creative'], default: 'pro' },
      { key: 'agency_color_enabled', label: 'Colour encodes agency (AI = mint, human ink = coral)', type: 'checkbox', save: 'bool', default: true },
      { key: 'ai_suggestions_require_approval', label: 'AI changes need your approval (track-changes)', type: 'checkbox', save: 'bool', default: true },
      { key: 'activity_tracking_enabled', label: 'Keep a note activity log (so the AI knows what changed)', type: 'checkbox', save: 'bool', default: true },
      { key: 'activity_retention_days', label: 'Activity kept for (days)', type: 'number', save: 'int', default: 90 },
      { key: 'max_ai_tokens_per_edit', label: 'Cap per AI edit (tokens)', type: 'number', save: 'int', default: 4000 },
      { key: 'ai_rate_per_min_per_user', label: 'Max AI actions per person, per minute (abuse + cost guard; over it → 429)', type: 'number', save: 'int', default: 30 },
      { key: 'local_model_for_sensitive', label: 'Use a local model for sensitive notes', type: 'checkbox', save: 'bool', default: false },
      { key: 'live_cursors_enabled', label: 'Show live collaborator cursors (coloured carets + names)', type: 'checkbox', save: 'bool', default: true },
      { key: 'ai_presence_enabled', label: 'Show the AI as a live participant while it edits', type: 'checkbox', save: 'bool', default: true },
      { key: 'diagrams_enabled', label: 'AI can draw diagrams (flow / mind-map / process / block)', type: 'checkbox', save: 'bool', default: true },
      { key: 'ink_enabled', label: 'AI can draw freehand ink (underline / arrow / sketch)', type: 'checkbox', save: 'bool', default: true },
      { key: 'illustration_enabled', label: 'AI can author SVG illustrations (vector art)', type: 'checkbox', save: 'bool', default: true },
      { key: 'image_generation_enabled', label: 'AI can GENERATE images (realistic raster — costs money)', type: 'checkbox', save: 'bool', default: false },
      { key: 'image_model', label: 'Image model (when image generation is on)', default: 'gpt-image-1', placeholder: 'gpt-image-1' },
      { key: 'visual_verify_enabled', label: 'Check an AI diagram against the request and redraw if it is wrong (quality verify loop)', type: 'checkbox', save: 'bool', default: true },
      { key: 'visual_verify_threshold', label: 'Accept a diagram at this 0–1 structural score (lower = more lenient)', type: 'number', save: 'float', default: 0.7 },
      { key: 'visual_verify_max_retries', label: 'Redraw a too-low diagram at most this many times', type: 'number', save: 'int', default: 2 },
      { key: 'image_verify_enabled', label: 'A vision model confirms a FOUND image really depicts the subject before inserting', type: 'checkbox', save: 'bool', default: true },
      { key: 'image_verify_min_confidence', label: 'Accept a found image at this 0–1 vision confidence (and good quality + safe)', type: 'number', save: 'float', default: 0.7 },
      { key: 'citations_enabled', label: 'Ask-your-workspace answers cite the EXACT line from each note (verified, click-to-highlight)', type: 'checkbox', save: 'bool', default: true },
      { key: 'citation_max_sources', label: 'How many notes a cited answer may draw on', type: 'number', save: 'int', default: 6 },
      { key: 'query_expansion_enabled', label: 'Smarter workspace search — rephrase the question + try a hypothetical answer (HyDE) to find more relevant notes', type: 'checkbox', save: 'bool', default: true },
      { key: 'query_expansion_variants', label: 'How many alternative phrasings to try when smarter search is on (2–4)', type: 'number', save: 'int', default: 3 },
      { key: 'flashcards_enabled', label: 'AI can make flashcards + schedule reviews (spaced repetition)', type: 'checkbox', save: 'bool', default: true },
      { key: 'daily_new_card_limit', label: 'New flashcards introduced per study session', type: 'number', save: 'int', default: 20 },
      { key: 'fsrs_enabled', label: 'Schedule reviews with FSRS (the accurate memory-model scheduler used by modern Anki) instead of classic SM-2', type: 'checkbox', save: 'bool', default: true },
      { key: 'fsrs_target_retention', label: 'Recall chance to aim for at review time (0.70–0.97; higher = review more often, remember more)', type: 'number', save: 'float', default: 0.9 },
      { key: 'translate_enabled', label: 'AI can translate a note into another language (saved as a new note; code, links and layout preserved)', type: 'checkbox', save: 'bool', default: true },
      { key: 'db_autofill_web_search', label: 'Database auto-fill may search the WEB for a value (off → uses only the row + its related rows)', type: 'checkbox', save: 'bool', default: true },
      { key: 'db_autofill_redact_pii', label: 'Scrub personal data (emails, phone numbers, card/SSN-like numbers) out of database auto-fill web searches', type: 'checkbox', save: 'bool', default: true },
      { key: 'image_provenance_enabled', label: 'Embed licence + provenance “Content Credentials” with AI/web images (source + licence, or AI generator + prompt)', type: 'checkbox', save: 'bool', default: true },
      { key: 'scheduled_agents_enabled', label: 'Users can set up SCHEDULED workspace agents (recurring AI tasks over their own notes)', type: 'checkbox', save: 'bool', default: true },
      { key: 'scheduled_agent_max_token_budget', label: 'Hard cap on a scheduled-agent run’s token budget (anti-runaway)', type: 'number', save: 'int', default: 20000 },
      { key: 'scheduled_agent_max_per_user', label: 'How many scheduled agents each user may create', type: 'number', save: 'int', default: 10 },
      { key: 'mcp_notes_enabled', label: 'Expose notes over MCP — let external apps (Claude/ChatGPT) connect to a user’s notes with a personal token', type: 'checkbox', save: 'bool', default: true },
      { key: 'mcp_notes_allow_writes', label: 'Allow MCP clients to create/append notes (off → the MCP connection is read-only)', type: 'checkbox', save: 'bool', default: true },
      { key: 'proactive_linking_enabled', label: 'Suggest links as you write — surface notes you mentioned (or that are related) for one-click [[linking]]', type: 'checkbox', save: 'bool', default: true },
      { key: 'entity_resolution_enabled', label: 'Entity disambiguation — fold spelling variants ("OpenAI"/"OpenAI, Inc.") into one knowledge-graph node', type: 'checkbox', save: 'bool', default: true },
      { key: 'embedding_batch_size', label: 'Notes embedded per model call during a workspace re-index (batched; 1–64)', type: 'number', save: 'int', default: 16 },
      { key: 'voice_capture_enabled', label: 'Voice / meeting capture — record → transcribe → structured note with clickable transcript citations', type: 'checkbox', save: 'bool', default: true },
      { key: 'store_audio', label: 'Keep the raw audio after transcribing (off = privacy: only the transcript is stored, audio discarded)', type: 'checkbox', save: 'bool', default: false },
      { key: 'transcription_language', label: 'Force a transcription language (ISO code like "en", or blank to auto-detect)', default: '', placeholder: 'en' },
      { key: 'transcription_model', label: 'Speech-to-text model (e.g. whisper-1)', default: 'whisper-1', placeholder: 'whisper-1' },
      { key: 'max_recording_seconds', label: 'Longest single recording allowed, in seconds', type: 'number', save: 'int', default: 3600 },
      { key: 'mobile_offline_enabled', label: 'Mobile app can edit notes offline + sync later', type: 'checkbox', save: 'bool', default: true },
      { key: 'mobile_ink_enabled', label: 'Mobile app can draw freehand ink on notes', type: 'checkbox', save: 'bool', default: true },
      { key: 'mobile_offline_note_limit', label: 'Notes cached on a phone for offline use', type: 'number', save: 'int', default: 200 },
      { key: 'desktop_offline_enabled', label: 'Desktop app works offline + reopens your last note', type: 'checkbox', save: 'bool', default: true },
      { key: 'quick_capture_enabled', label: 'Global quick-capture hotkey (jot a note from anywhere)', type: 'checkbox', save: 'bool', default: true },
      { key: 'desktop_offline_note_limit', label: 'Notes cached on the desktop for offline use', type: 'number', save: 'int', default: 500 },
      { key: 'export_enabled', label: 'People can export / download a note', type: 'checkbox', save: 'bool', default: true },
      { key: 'allowed_export_formats', label: 'Export formats offered (JSON array: markdown/html/word/json)', textarea: true, save: 'json', rows: 2 },
      { key: 'image_search_enabled', label: 'AI can SOURCE a real free-to-use image from the web (with attribution)', type: 'checkbox', save: 'bool', default: true },
      { key: 'image_search_provider', label: 'Image provider to search first', options: ['openverse', 'wikimedia', 'unsplash', 'pexels', 'pixabay'], default: 'openverse' },
      { key: 'image_search_allowed_licenses', label: 'Allowed "free to use" licences (JSON array: cc0/pdm/by/by-sa/unsplash/pexels/pixabay — NC/ND excluded)', textarea: true, save: 'json', rows: 2 },
      { key: 'image_search_require_attribution', label: 'Show the attribution + licence caption under sourced images (required for CC-BY/BY-SA)', type: 'checkbox', save: 'bool', default: true },
      { key: 'enabled_ai_tools', label: 'Note AI tools the editor may use (JSON array)', textarea: true, save: 'json', rows: 3 },
    ],
  },
  'note-action-modes': {
    singular: 'Note Action Routing', plural: 'Note Action Routing', apiPath: 'admin/note-action-modes', listKey: 'note-action-modes',
    cols: ['tenant_id', 'action_key', 'mode', 'updated_at'],
    fields: [
      { key: 'tenant_id', label: 'Tenant ID (blank = global default for this action)' },
      { key: 'action_key', label: 'Note action', options: ['diagram', 'ink', 'illustration', 'visual', 'restructure', 'find_image'], default: 'diagram' },
      { key: 'mode', label: 'How it runs', options: ['direct', 'agent', 'supervisor'], default: 'direct' },
      { key: 'updated_at', label: 'Updated At', readonly: true },
    ],
  },
  // Phase 0-B — the weaveNotes Activity / Audit feed: a read-only, tenant-scoped record of every note
  // action (who/what/when, by a person or the AI). Keyset-paginated + CSV/JSON/JSONL export via
  // /api/admin/note-activity. The same log the AI reads to understand "what changed" before it edits.
  'note-activity': {
    singular: 'Note Activity', plural: 'Note Activity', apiPath: 'admin/note-activity', listKey: 'note-activity',
    readOnly: true,
    cols: ['created_at', 'actor', 'action', 'note_title', 'summary', 'user_id'],
    fields: [
      { key: 'created_at', label: 'When', readonly: true },
      { key: 'actor', label: 'Who (user / ai)', readonly: true },
      { key: 'action', label: 'What', readonly: true },
      { key: 'note_title', label: 'Note', readonly: true },
      { key: 'summary', label: 'Summary', readonly: true, textarea: true, rows: 2 },
      { key: 'user_id', label: 'User', readonly: true },
      { key: 'note_id', label: 'Note ID', readonly: true },
      { key: 'id', label: 'Event ID', readonly: true },
    ],
  },
  'cache-metrics': {
    singular: 'Cache Metric', apiPath: 'admin/cache-metrics', listKey: 'cache-metrics',
    readOnly: true,
    cols: ['window_start', 'response_hits', 'response_misses', 'prompt_cache_read_tokens', 'prompt_cache_write_tokens', 'cost_saved_usd'],
    fields: [
      { key: 'window_start', label: 'Window (hour, UTC)' },
      { key: 'response_hits', label: 'Response Cache Hits', type: 'number' },
      { key: 'response_misses', label: 'Response Cache Misses', type: 'number' },
      { key: 'prompt_cache_read_tokens', label: 'Prompt Cache Read Tokens', type: 'number' },
      { key: 'prompt_cache_write_tokens', label: 'Prompt Cache Write Tokens', type: 'number' },
      { key: 'cost_saved_usd', label: 'Cost Saved (USD)', type: 'number' },
    ],
  },
  'reliability-policies': {
    singular: 'Reliability Policy', apiPath: 'admin/reliability-policies', listKey: 'reliability-policies',
    cols: ['name', 'policy_type', 'max_retries', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'policy_type', label: 'Policy Type', options: ['retry', 'circuit-breaker', 'bulkhead', 'timeout', 'fallback'], default: 'retry' },
      { key: 'max_retries', label: 'Max Retries', type: 'number', save: 'int' },
      { key: 'initial_delay_ms', label: 'Initial Delay (ms)', type: 'number', save: 'int' },
      { key: 'max_delay_ms', label: 'Max Delay (ms)', type: 'number', save: 'int' },
      { key: 'backoff_multiplier', label: 'Backoff Multiplier', type: 'number', save: 'float' },
      { key: 'max_concurrent', label: 'Max Concurrent', type: 'number', save: 'int' },
      { key: 'queue_size', label: 'Queue Size', type: 'number', save: 'int' },
      { key: 'strategy', label: 'Strategy' },
      { key: 'ttl_ms', label: 'TTL (ms)', type: 'number', save: 'int' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'sandbox-policies': {
    singular: 'Sandbox Policy', apiPath: 'admin/sandbox-policies', listKey: 'sandbox-policies',
    cols: ['name', 'max_duration_ms', 'filesystem_access', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'max_cpu_ms', label: 'Max CPU (ms)', type: 'number', save: 'int' },
      { key: 'max_memory_mb', label: 'Max Memory (MB)', type: 'number', save: 'int' },
      { key: 'max_duration_ms', label: 'Max Duration (ms)', type: 'number', save: 'int', default: 30000 },
      { key: 'max_output_bytes', label: 'Max Output Bytes', type: 'number', save: 'int' },
      { key: 'allowed_modules', label: 'Allowed Modules (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'denied_modules', label: 'Denied Modules (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'network_access', label: 'Network Access', type: 'checkbox', save: 'intBool' },
      { key: 'filesystem_access', label: 'Filesystem Access', options: ['none', 'readonly', 'readwrite'], default: 'none' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'extraction-pipelines': {
    singular: 'Extraction Pipeline', apiPath: 'admin/extraction-pipelines', listKey: 'extraction-pipelines',
    cols: ['name', 'max_input_size_bytes', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'stages', label: 'Stages (JSON)', textarea: true, rows: 4, save: 'jsonStr' },
      { key: 'input_mime_types', label: 'Input MIME Types (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'max_input_size_bytes', label: 'Max Input Size (bytes)', type: 'number', save: 'int' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'artifact-policies': {
    singular: 'Artifact Policy', apiPath: 'admin/artifact-policies', listKey: 'artifact-policies',
    cols: ['name', 'max_size_bytes', 'retention_days', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'max_size_bytes', label: 'Max Size (bytes)', type: 'number', save: 'int' },
      { key: 'allowed_types', label: 'Allowed Types (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'retention_days', label: 'Retention Days', type: 'number', save: 'int' },
      { key: 'require_versioning', label: 'Require Versioning', type: 'checkbox', save: 'intBool' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'artifacts': {
    singular: 'Artifact', apiPath: 'admin/artifacts', listKey: 'artifacts',
    readOnly: true, customRecordView: 'readonly-detail',
    cols: ['name', 'type', 'scope', 'size_bytes', 'version', 'session_id', 'created_at'],
    fields: [
      { key: 'id',         label: 'ID',          readonly: true },
      { key: 'name',       label: 'Name',         readonly: true },
      { key: 'type',       label: 'Type',         readonly: true },
      { key: 'mime_type',  label: 'MIME Type',    readonly: true },
      { key: 'scope',      label: 'Scope',        readonly: true },
      { key: 'session_id', label: 'Session',      readonly: true },
      { key: 'user_id',    label: 'User',         readonly: true },
      { key: 'agent_id',   label: 'Agent',        readonly: true },
      { key: 'run_id',     label: 'Run',          readonly: true },
      { key: 'version',    label: 'Version',      readonly: true },
      { key: 'size_bytes', label: 'Size (bytes)',  readonly: true },
      { key: 'tags',       label: 'Tags (JSON)',   readonly: true, textarea: true, rows: 2 },
      { key: 'policy_id',  label: 'Policy',       readonly: true },
      { key: 'created_at', label: 'Created',      readonly: true },
      { key: 'updated_at', label: 'Updated',      readonly: true },
    ],
  },

  'tenant-artifact-settings': {
    singular: 'Tenant Artifact Settings', apiPath: 'admin/tenant-artifact-settings', listKey: 'settings',
    cols: ['tenant_id', 'emit_enabled', 'preview_enabled', 'sandbox_html'],
    fields: [
      { key: 'tenant_id',      label: 'Tenant ID (use "default" for global)',   readonly: false },
      { key: 'allowed_types',  label: 'Allowed Types (JSON array or null for all)', textarea: true, rows: 4, save: 'jsonStr' },
      { key: 'max_size_bytes', label: 'Max Size (bytes, null = inherit)',  type: 'number', save: 'int' },
      { key: 'require_policy', label: 'Require Policy',    type: 'checkbox', save: 'bool' },
      { key: 'preview_enabled',label: 'Preview Enabled',   type: 'checkbox', save: 'bool', default: true },
      { key: 'sandbox_html',   label: 'Sandbox HTML/React Preview', type: 'checkbox', save: 'bool', default: true },
      { key: 'emit_enabled',   label: 'Emit Enabled (agents can emit artifacts)', type: 'checkbox', save: 'bool', default: true },
      { key: 'created_at',     label: 'Created',   readonly: true },
      { key: 'updated_at',     label: 'Updated',   readonly: true },
    ],
  },

  'tenant-governance': {
    singular: 'Tenant Governance', apiPath: 'admin/tenant-governance', listKey: 'tenants',
    cols: ['tenant_id', 'data_residency', 'controls', 'legal_hold'],
    fields: [
      { key: 'tenant_id', label: 'Tenant ID', readonly: false },
      { key: 'data_residency', label: 'Data residency (region the data must stay in)', options: ['unrestricted', 'us', 'eu', 'uk', 'apac', 'canada', 'australia'], default: 'unrestricted' },
      { key: 'allow_model_training', label: 'Allow using this tenant’s data for model training (off = no-training)', type: 'checkbox', save: 'bool', default: true },
      { key: 'allow_analytics', label: 'Allow product analytics for this tenant', type: 'checkbox', save: 'bool', default: true },
      { key: 'sso_required', label: 'Enforce single sign-on (SSO) for this tenant', type: 'checkbox', save: 'bool', default: false },
      { key: 'sso_protocol', label: 'SSO protocol', options: ['none', 'saml', 'oidc'], default: 'none' },
      { key: 'scim_enabled', label: 'SCIM user provisioning enabled', type: 'checkbox', save: 'bool', default: false },
      { key: 'activity_retention_days', label: 'Activity-log retention (days; 0 = keep forever)', type: 'number', save: 'int', default: 0 },
      { key: 'audit_retention_days', label: 'Audit retention (days; 0 = keep forever)', type: 'number', save: 'int', default: 365 },
      { key: 'legal_hold', label: 'Legal hold (suspend all auto-deletion)', type: 'checkbox', save: 'bool', default: false },
      { key: 'byok_active', label: 'BYOK active (read-only; from encryption config)', type: 'checkbox', save: 'bool', readonly: true },
      { key: 'encryption_at_rest', label: 'Encryption at rest (read-only; from encryption policy)', type: 'checkbox', save: 'bool', readonly: true },
      { key: 'controls', label: 'Enterprise controls on', readonly: true },
    ],
  },

  'tenant-configs': {
    singular: 'Tenant Config', apiPath: 'admin/tenant-configs', listKey: 'tenant-configs',
    cols: ['name', 'tenant_id', 'scope', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'tenant_id', label: 'Tenant ID' },
      { key: 'scope', label: 'Scope', options: ['tenant', 'user', 'team'], default: 'tenant' },
      { key: 'allowed_models', label: 'Allowed Models (JSON)', textarea: true, save: 'json' },
      { key: 'denied_models', label: 'Denied Models (JSON)', textarea: true, save: 'json' },
      { key: 'allowed_tools', label: 'Allowed Tools (JSON)', textarea: true, save: 'json' },
      { key: 'max_tokens_daily', label: 'Max Tokens/Day', type: 'number', save: 'int' },
      { key: 'max_cost_daily', label: 'Max Cost/Day', type: 'number', save: 'float' },
      { key: 'max_tokens_monthly', label: 'Max Tokens/Month', type: 'number', save: 'int' },
      { key: 'max_cost_monthly', label: 'Max Cost/Month', type: 'number', save: 'float' },
      { key: 'features', label: 'Features (JSON)', textarea: true, save: 'json' },
      { key: 'config_overrides', label: 'Config Overrides (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'collaboration-sessions': {
    singular: 'Collaboration Session', apiPath: 'admin/collaboration-sessions', listKey: 'collaboration-sessions',
    cols: ['name', 'session_type', 'max_participants', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'session_type', label: 'Session Type', options: ['pair', 'team', 'broadcast', 'review'], default: 'team' },
      { key: 'max_participants', label: 'Max Participants', type: 'number', save: 'int', default: 10 },
      { key: 'presence_ttl_ms', label: 'Presence TTL (ms)', type: 'number', save: 'int', default: 30000 },
      { key: 'auto_close_idle_ms', label: 'Auto Close Idle (ms)', type: 'number', save: 'int' },
      { key: 'handoff_enabled', label: 'Handoff Enabled', type: 'checkbox', save: 'bool', default: true },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'graph-configs': {
    singular: 'Graph Config', apiPath: 'admin/graph-configs', listKey: 'graph-configs',
    cols: ['name', 'graph_type', 'max_depth', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'graph_type', label: 'Graph Type', options: ['entity', 'timeline', 'knowledge', 'dependency'], default: 'entity' },
      { key: 'max_depth', label: 'Max Depth', type: 'number', save: 'int', default: 3 },
      { key: 'entity_types', label: 'Entity Types (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'relationship_types', label: 'Relationship Types (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'auto_link', label: 'Auto Link', type: 'checkbox', save: 'bool', default: true },
      { key: 'scoring_weights', label: 'Scoring Weights (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'plugin-configs': {
    singular: 'Plugin Config', apiPath: 'admin/plugin-configs', listKey: 'plugin-configs',
    cols: ['name', 'plugin_type', 'version', 'trust_level', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'plugin_type', label: 'Plugin Type', options: ['core', 'community', 'private', 'enterprise'], default: 'community' },
      { key: 'package_name', label: 'Package Name', default: 'unknown' },
      { key: 'version', label: 'Version', default: '1.0.0' },
      { key: 'capabilities', label: 'Capabilities (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'trust_level', label: 'Trust Level', options: ['trusted', 'community', 'sandboxed'], default: 'community' },
      { key: 'auto_update', label: 'Auto Update', type: 'checkbox', save: 'bool' },
      { key: 'config', label: 'Config (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'scaffold-templates': {
    singular: 'Scaffold Template', apiPath: 'admin/scaffold-templates', listKey: 'scaffold-templates',
    cols: ['name', 'template_type', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'template_type', label: 'Template Type', options: ['basic-agent', 'tool-calling-agent', 'rag-pipeline', 'workflow', 'multi-agent', 'mcp-server', 'full-stack'], default: 'basic-agent' },
      { key: 'files', label: 'Files (JSON)', textarea: true, rows: 6, save: 'jsonStr' },
      { key: 'dependencies', label: 'Dependencies (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'dev_dependencies', label: 'Dev Dependencies (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'variables', label: 'Variables (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'post_install', label: 'Post Install Command' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'recipe-configs': {
    singular: 'Recipe Config', apiPath: 'admin/recipe-configs', listKey: 'recipe-configs',
    cols: ['name', 'recipe_type', 'model', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'recipe_type', label: 'Recipe Type', options: ['workflow', 'governed', 'approval', 'acl-rag', 'multi-tenant', 'eval-routed', 'memory', 'event-driven', 'safe-exec'], default: 'workflow' },
      { key: 'model', label: 'Model' },
      { key: 'provider', label: 'Provider' },
      { key: 'system_prompt', label: 'System Prompt', textarea: true, rows: 3 },
      { key: 'tools', label: 'Tools (JSON)', textarea: true, save: 'json' },
      { key: 'guardrails', label: 'Guardrails (JSON)', textarea: true, save: 'json' },
      { key: 'max_steps', label: 'Max Steps', type: 'number', save: 'int', default: 10 },
      { key: 'options', label: 'Options (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'widget-configs': {
    singular: 'Widget Config', apiPath: 'admin/widget-configs', listKey: 'widget-configs',
    cols: ['name', 'widget_type', 'max_data_points', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'widget_type', label: 'Widget Type', options: ['table', 'chart', 'form', 'code', 'timeline', 'image'], default: 'table' },
      { key: 'default_options', label: 'Default Options (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'allowed_contexts', label: 'Allowed Contexts (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'max_data_points', label: 'Max Data Points', type: 'number', save: 'int' },
      { key: 'refresh_interval_ms', label: 'Refresh Interval (ms)', type: 'number', save: 'int' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'validation-rules': {
    singular: 'Validation Rule', apiPath: 'admin/validation-rules', listKey: 'validation-rules',
    cols: ['name', 'rule_type', 'target', 'severity', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'rule_type', label: 'Rule Type', options: ['required', 'range', 'pattern', 'custom'], default: 'required' },
      { key: 'target', label: 'Target', options: ['agent-config', 'workflow-config', 'tool-config'], default: 'agent-config' },
      { key: 'condition', label: 'Condition (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'severity', label: 'Severity', options: ['error', 'warning', 'info'], default: 'error' },
      { key: 'message', label: 'Message' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'workflow-runs': {
    singular: 'Workflow Run', apiPath: 'workflow-runs', listKey: 'runs',
    cols: ['id', 'workflow_id', 'status', 'cost_total', 'started_at', 'completed_at'],
    fields: [
      { key: 'id', label: 'Run ID', readonly: true },
      { key: 'workflow_id', label: 'Workflow ID', readonly: true },
      { key: 'status', label: 'Status', readonly: true },
      { key: 'cost_total', label: 'Cost (USD)', readonly: true },
      { key: 'state', label: 'State (JSON)', textarea: true, rows: 6, readonly: true },
      { key: 'input', label: 'Input (JSON)', textarea: true, rows: 4, readonly: true },
      { key: 'error', label: 'Error', readonly: true },
      { key: 'started_at', label: 'Started At', readonly: true },
      { key: 'completed_at', label: 'Completed At', readonly: true },
    ],
    readOnly: true,
  },
  'capability-policy-bindings': {
    singular: 'Capability Policy Binding',
    apiPath: 'admin/capability-policy-bindings',
    listKey: 'bindings',
    cols: ['binding_kind', 'binding_ref', 'policy_kind', 'policy_ref', 'precedence', 'enabled'],
    fields: [
      { key: 'binding_kind', label: 'Binding Kind (agent | mesh | workflow | tenant)' },
      { key: 'binding_ref', label: 'Binding Ref (id matching binding_kind; for tenant use the tenantId)' },
      { key: 'policy_kind', label: 'Policy Kind (tool_policy | guardrail | routing | memory | sandbox | cost_policy)' },
      { key: 'policy_ref', label: 'Policy Ref (id of the policy row)' },
      { key: 'precedence', label: 'Precedence (agent=100 / mesh=50 / workflow=10 / tenant=5)', type: 'number', save: 'int', default: 10 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'cost-policies': {
    singular: 'Cost Policy',
    apiPath: 'admin/cost-policies',
    listKey: 'policies',
    cols: ['key', 'tier', 'enabled', 'description'],
    fields: [
      { key: 'key', label: 'Key (unique, e.g. tenant.economy)' },
      { key: 'tier', label: 'Tier (economy | balanced | performance | max | custom)', default: 'balanced' },
      { key: 'description', label: 'Description', textarea: true, rows: 2 },
      { key: 'levers_json', label: 'Levers JSON (partial CostPolicy override merged on top of tier)', textarea: true, rows: 8 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'tenant-encryption-policies': {
    singular: 'Tenant Encryption Policy',
    apiPath: 'admin/tenant-encryption-policies',
    listKey: 'policies',
    cols: ['tenant_id', 'enabled', 'kms_provider_id', 'rotation_schedule', 'active_dek_id', 'shred_completed_at'],
    fields: [
      { key: 'tenant_id', label: 'Tenant ID (unique; FK to tenants table)' },
      { key: 'kms_provider_id', label: 'KMS Provider (local | aws-kms | gcp-kms | azure-kv | vault)', default: 'local' },
      { key: 'kms_config', label: 'KMS Config JSON (provider-specific, e.g. {"keyArn":"arn:aws:kms:..."})', textarea: true, rows: 4 },
      { key: 'rotation_schedule', label: 'Rotation Schedule (manual | monthly | quarterly | annual)', default: 'manual' },
      { key: 'blind_index_enabled', label: 'Blind Index Enabled (HMAC-SHA-256 sibling columns for equality search)', type: 'checkbox', save: 'bool', default: false },
      { key: 'field_policy', label: 'Field Policy JSON (which (table,column) pairs to encrypt)', textarea: true, rows: 8 },
      { key: 'enabled', label: 'Enabled (flipping false\u2192true auto-bootstraps KEK + DEK + BIK)', type: 'checkbox', save: 'bool', default: false },
    ],
  },
  'capability-packs': {
    singular: 'Capability Pack',
    apiPath: 'admin/capability-packs',
    listKey: 'packs',
    cols: ['pack_key', 'version', 'status', 'name', 'installed_at'],
    fields: [
      { key: 'pack_key', label: 'Pack Key (e.g. acme.support)' },
      { key: 'version', label: 'Version (semver, e.g. 1.0.0)' },
      { key: 'status', label: 'Status (draft | published | retired)', default: 'draft' },
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description', textarea: true, rows: 3 },
      { key: 'authored_by', label: 'Authored By' },
      { key: 'manifest', label: 'Manifest (JSON: { meta, contents, dependencies?, preconditions? })', textarea: true, rows: 12 },
    ],
  },
  'capability-pack-installations': {
    singular: 'Capability Pack Installation',
    apiPath: 'admin/capability-pack-installations',
    listKey: 'installations',
    cols: ['pack_key', 'pack_version', 'installed_by', 'installed_at', 'uninstalled_at'],
    fields: [
      { key: 'pack_key', label: 'Pack Key', readonly: true },
      { key: 'pack_version', label: 'Pack Version', readonly: true },
      { key: 'installed_by', label: 'Installed By', readonly: true },
      { key: 'installed_at', label: 'Installed At', readonly: true },
      { key: 'uninstalled_at', label: 'Uninstalled At', readonly: true },
      { key: 'ledger', label: 'Ledger (JSON)', textarea: true, rows: 8, readonly: true },
    ],
    readOnly: true,
  },
  'guardrail-evals': {
    singular: 'Guardrail Eval', apiPath: 'guardrail-evals', listKey: 'evals',
    cols: ['id', 'stage', 'overall_decision', 'created_at'],
    fields: [],
    readOnly: true,
  },
};
