import type { AdminTabDef } from '@weaveintel/core';

/**
 * Platform capability tabs (governance, integrations, infra, monitoring, etc.)
 * are isolated to keep the root admin schema file focused on composition.
 */
export const PLATFORM_CAPABILITY_ADMIN_TABS: Record<string, AdminTabDef> = {
  'users': {
    singular: 'User', apiPath: 'admin/users', listKey: 'users',
    cols: ['email', 'name', 'persona', 'tenant_id', 'created_at'],
    fields: [
      { key: 'email', label: 'Email' },
      { key: 'name', label: 'Name' },
      { key: 'persona', label: 'Persona', options: ['platform_admin', 'tenant_admin', 'tenant_user', 'agent_worker', 'agent_researcher', 'agent_supervisor'], default: 'tenant_user' },
      { key: 'tenant_id', label: 'Tenant ID' },
      { key: 'password', label: 'Password (set on create/update)' },
      { key: 'created_at', label: 'Created At', readonly: true },
    ],
  },
  'guardrails': {
    singular: 'Guardrail', apiPath: 'admin/guardrails', listKey: 'guardrails',
    cols: ['name', 'type', 'stage', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'type', label: 'Type', options: ['content_filter', 'redaction', 'pii_detection', 'budget', 'factuality', 'cognitive_check', 'topic_guard', 'toxicity', 'custom'] },
      { key: 'stage', label: 'Stage', options: ['pre', 'post', 'both'], default: 'pre' },
      { key: 'config', label: 'Config (JSON)', textarea: true, save: 'json' },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'routing': {
    singular: 'Routing Policy', apiPath: 'admin/routing', listKey: 'policies',
    cols: ['name', 'strategy', 'fallback_model', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'strategy', label: 'Strategy', options: ['balanced', 'cost_optimized', 'latency_optimized', 'quality_first', 'custom'], default: 'balanced' },
      { key: 'constraints', label: 'Constraints (JSON)', textarea: true, save: 'json' },
      { key: 'weights', label: 'Weights (JSON)', textarea: true, save: 'json' },
      { key: 'fallback_model', label: 'Fallback Model' },
      { key: 'fallback_provider', label: 'Fallback Provider' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'model-pricing': {
    singular: 'Model Pricing', apiPath: 'admin/model-pricing', listKey: 'pricing',
    cols: ['model_id', 'provider', 'display_name', 'input_cost_per_1m', 'output_cost_per_1m', 'quality_score', 'source', 'enabled'],
    fields: [
      { key: 'model_id', label: 'Model ID' },
      { key: 'provider', label: 'Provider', options: ['openai', 'anthropic'] },
      { key: 'display_name', label: 'Display Name' },
      { key: 'input_cost_per_1m', label: 'Input Cost / 1M tokens', type: 'number', save: 'float' },
      { key: 'output_cost_per_1m', label: 'Output Cost / 1M tokens', type: 'number', save: 'float' },
      { key: 'quality_score', label: 'Quality Score (0-1)', type: 'number', save: 'float', default: 0.5 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'workflows': {
    singular: 'Workflow', apiPath: 'admin/workflows', listKey: 'workflows',
    cols: ['name', 'version', 'entry_step_id', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'version', label: 'Version', default: '1.0' },
      { key: 'steps', label: 'Steps (JSON)', textarea: true, rows: 4, save: 'json' },
      { key: 'entry_step_id', label: 'Entry Step ID' },
      { key: 'metadata', label: 'Metadata (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'task-policies': {
    singular: 'Task Policy', apiPath: 'admin/task-policies', listKey: 'taskPolicies',
    cols: ['name', 'task_type', 'default_priority', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'trigger', label: 'Trigger' },
      { key: 'task_type', label: 'Task Type', options: ['approval', 'review', 'generation', 'classification'], default: 'approval' },
      { key: 'default_priority', label: 'Priority', options: ['low', 'normal', 'high', 'critical'], default: 'normal' },
      { key: 'sla_hours', label: 'SLA Hours', type: 'number', save: 'float' },
      { key: 'auto_escalate_after_hours', label: 'Auto-escalate (hours)', type: 'number', save: 'float' },
      { key: 'assignment_strategy', label: 'Assignment', options: ['round-robin', 'least-busy', 'manual'], default: 'round-robin' },
      { key: 'assign_to', label: 'Assign To' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'contracts': {
    singular: 'Contract', apiPath: 'admin/contracts', listKey: 'contracts',
    cols: ['name', 'max_attempts', 'min_confidence', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'input_schema', label: 'Input Schema (JSON)', textarea: true },
      { key: 'output_schema', label: 'Output Schema (JSON)', textarea: true },
      { key: 'acceptance_criteria', label: 'Acceptance Criteria (JSON)', textarea: true, default: '[]' },
      { key: 'max_attempts', label: 'Max Attempts', type: 'number', save: 'int' },
      { key: 'timeout_ms', label: 'Timeout (ms)', type: 'number', save: 'int' },
      { key: 'evidence_required', label: 'Evidence Required', textarea: true },
      { key: 'min_confidence', label: 'Min Confidence', type: 'number', save: 'float' },
      { key: 'require_human_review', label: 'Human Review', type: 'checkbox', save: 'bool' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'identity-rules': {
    singular: 'Identity Rule', apiPath: 'admin/identity-rules', listKey: 'identity-rules',
    cols: ['name', 'resource', 'action', 'result', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'resource', label: 'Resource', default: '*' },
      { key: 'action', label: 'Action', default: '*' },
      { key: 'roles', label: 'Roles (JSON)', textarea: true, save: 'json' },
      { key: 'scopes', label: 'Scopes (JSON)', textarea: true, save: 'json' },
      { key: 'result', label: 'Result', options: ['allow', 'deny'], default: 'allow' },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'memory-governance': {
    singular: 'Memory Governance Rule', apiPath: 'admin/memory-governance', listKey: 'memory-governance',
    cols: ['name', 'tenant_id', 'max_age', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'memory_types', label: 'Memory Types (JSON)', textarea: true, save: 'json' },
      { key: 'tenant_id', label: 'Tenant ID' },
      { key: 'block_patterns', label: 'Block Patterns (JSON)', textarea: true, save: 'json' },
      { key: 'redact_patterns', label: 'Redact Patterns (JSON)', textarea: true, save: 'json' },
      { key: 'max_age', label: 'Max Age' },
      { key: 'max_entries', label: 'Max Entries', type: 'number', save: 'int' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'memory-extraction-rules': {
    singular: 'Memory Extraction Rule', apiPath: 'admin/memory-extraction-rules', listKey: 'memory-extraction-rules',
    cols: ['name', 'rule_type', 'entity_type', 'priority', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'rule_type', label: 'Rule Type', options: ['self_disclosure', 'entity_extraction'], default: 'entity_extraction' },
      { key: 'entity_type', label: 'Entity Type', options: ['', 'person', 'location', 'organization', 'preference', 'topic', 'general'] },
      { key: 'pattern', label: 'Regex Pattern', textarea: true, rows: 3 },
      { key: 'flags', label: 'Regex Flags', default: 'i' },
      { key: 'facts_template', label: 'Facts Template (JSON)', textarea: true, save: 'json' },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'compliance-rules': {
    singular: 'Compliance Rule', apiPath: 'admin/compliance-rules', listKey: 'compliance-rules',
    cols: ['name', 'rule_type', 'target_resource', 'action', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'rule_type', label: 'Rule Type', options: ['retention', 'deletion', 'legal-hold', 'consent', 'residency'], default: 'retention' },
      { key: 'target_resource', label: 'Target Resource', default: '*' },
      { key: 'retention_days', label: 'Retention Days', type: 'number', save: 'int' },
      { key: 'region', label: 'Region' },
      { key: 'consent_purpose', label: 'Consent Purpose' },
      { key: 'action', label: 'Action', options: ['archive', 'delete', 'notify', 'block', 'encrypt'], default: 'notify' },
      { key: 'config', label: 'Config (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'search-providers': {
    singular: 'Search Provider', apiPath: 'admin/search-providers', listKey: 'search-providers',
    cols: ['name', 'provider_type', 'priority', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'provider_type', label: 'Provider Type', options: ['duckduckgo', 'google', 'bing', 'brave', 'custom'], default: 'duckduckgo' },
      { key: 'api_key', label: 'API Key' },
      { key: 'base_url', label: 'Base URL' },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'options', label: 'Options (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'http-endpoints': {
    singular: 'HTTP Endpoint', apiPath: 'admin/http-endpoints', listKey: 'http-endpoints',
    cols: ['name', 'method', 'url', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'url', label: 'URL' },
      { key: 'method', label: 'Method', options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], default: 'GET' },
      { key: 'auth_type', label: 'Auth Type', options: ['none', 'bearer', 'basic', 'api-key', 'oauth'], default: 'none' },
      { key: 'auth_config', label: 'Auth Config (JSON)', textarea: true, save: 'json' },
      { key: 'headers', label: 'Headers (JSON)', textarea: true, save: 'json' },
      { key: 'body_template', label: 'Body Template', textarea: true },
      { key: 'response_transform', label: 'Response Transform', textarea: true },
      { key: 'retry_count', label: 'Retry Count', type: 'number', save: 'int', default: 0 },
      { key: 'rate_limit_rpm', label: 'Rate Limit RPM', type: 'number', save: 'int', default: 60 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'social-accounts': {
    singular: 'Social Account', apiPath: 'admin/social-accounts', listKey: 'social-accounts',
    cols: ['name', 'platform', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'platform', label: 'Platform', options: ['slack', 'discord', 'telegram', 'twitter', 'mastodon', 'linkedin', 'instagram', 'facebook', 'tiktok', 'medium', 'blogger'], default: 'linkedin' },
      { key: 'api_key', label: 'API Key' },
      { key: 'api_secret', label: 'API Secret' },
      { key: 'base_url', label: 'Base URL' },
      { key: 'options', label: 'Options (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'enterprise-connectors': {
    singular: 'Enterprise Connector', apiPath: 'admin/enterprise-connectors', listKey: 'enterprise-connectors',
    cols: ['name', 'connector_type', 'base_url', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'connector_type', label: 'Connector Type', options: ['jira', 'confluence', 'sharepoint', 'salesforce', 'servicenow', 'custom'], default: 'jira' },
      { key: 'base_url', label: 'Base URL' },
      { key: 'auth_type', label: 'Auth Type', options: ['bearer', 'basic', 'oauth', 'api-key'], default: 'bearer' },
      { key: 'auth_config', label: 'Auth Config (JSON)', textarea: true, save: 'json' },
      { key: 'options', label: 'Options (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'trigger-definitions': {
    singular: 'Trigger Definition', apiPath: 'admin/trigger-definitions', listKey: 'trigger-definitions',
    cols: ['name', 'trigger_type', 'status', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'trigger_type', label: 'Trigger Type', options: ['cron', 'webhook', 'event', 'manual'], default: 'cron' },
      { key: 'expression', label: 'Expression' },
      { key: 'config', label: 'Config (JSON)', textarea: true, save: 'json' },
      { key: 'target_workflow', label: 'Target Workflow' },
      { key: 'status', label: 'Status', options: ['active', 'paused', 'disabled'], default: 'active' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'replay-scenarios': {
    singular: 'Replay Scenario', apiPath: 'admin/replay-scenarios', listKey: 'replay-scenarios',
    cols: ['name', 'model', 'provider', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'golden_prompt', label: 'Golden Prompt', textarea: true, rows: 3 },
      { key: 'golden_response', label: 'Golden Response', textarea: true, rows: 3 },
      { key: 'model', label: 'Model' },
      { key: 'provider', label: 'Provider' },
      { key: 'tags', label: 'Tags (JSON)', textarea: true, save: 'json' },
      { key: 'acceptance_criteria', label: 'Acceptance Criteria (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'cache-policies': {
    singular: 'Cache Policy', apiPath: 'admin/cache-policies', listKey: 'cache-policies',
    cols: ['name', 'scope', 'ttl_ms', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'scope', label: 'Scope', options: ['global', 'model', 'prompt', 'user'], default: 'global' },
      { key: 'ttl_ms', label: 'TTL (ms)', type: 'number', save: 'int', default: 300000 },
      { key: 'max_entries', label: 'Max Entries', type: 'number', save: 'int', default: 1000 },
      { key: 'bypass_patterns', label: 'Bypass Patterns (JSON)', textarea: true, save: 'json' },
      { key: 'invalidate_on', label: 'Invalidate On (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'reliability-policies': {
    singular: 'Reliability Policy', apiPath: 'admin/reliability-policies', listKey: 'reliability-policies',
    cols: ['name', 'policy_type', 'max_retries', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'policy_type', label: 'Policy Type', options: ['retry', 'circuit-breaker', 'bulkhead', 'timeout', 'fallback'], default: 'retry' },
      { key: 'max_retries', label: 'Max Retries', type: 'number', save: 'int' },
      { key: 'initial_delay_ms', label: 'Initial Delay (ms)', type: 'number', save: 'int' },
      { key: 'max_delay_ms', label: 'Max Delay (ms)', type: 'number', save: 'int' },
      { key: 'backoff_multiplier', label: 'Backoff Multiplier', type: 'number', save: 'float' },
      { key: 'max_concurrent', label: 'Max Concurrent', type: 'number', save: 'int' },
      { key: 'queue_size', label: 'Queue Size', type: 'number', save: 'int' },
      { key: 'strategy', label: 'Strategy' },
      { key: 'ttl_ms', label: 'TTL (ms)', type: 'number', save: 'int' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'sandbox-policies': {
    singular: 'Sandbox Policy', apiPath: 'admin/sandbox-policies', listKey: 'sandbox-policies',
    cols: ['name', 'max_duration_ms', 'filesystem_access', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'max_cpu_ms', label: 'Max CPU (ms)', type: 'number', save: 'int' },
      { key: 'max_memory_mb', label: 'Max Memory (MB)', type: 'number', save: 'int' },
      { key: 'max_duration_ms', label: 'Max Duration (ms)', type: 'number', save: 'int', default: 30000 },
      { key: 'max_output_bytes', label: 'Max Output Bytes', type: 'number', save: 'int' },
      { key: 'allowed_modules', label: 'Allowed Modules (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'denied_modules', label: 'Denied Modules (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'network_access', label: 'Network Access', type: 'checkbox', save: 'intBool' },
      { key: 'filesystem_access', label: 'Filesystem Access', options: ['none', 'readonly', 'readwrite'], default: 'none' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'extraction-pipelines': {
    singular: 'Extraction Pipeline', apiPath: 'admin/extraction-pipelines', listKey: 'extraction-pipelines',
    cols: ['name', 'max_input_size_bytes', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'stages', label: 'Stages (JSON)', textarea: true, rows: 4, save: 'jsonStr' },
      { key: 'input_mime_types', label: 'Input MIME Types (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'max_input_size_bytes', label: 'Max Input Size (bytes)', type: 'number', save: 'int' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'artifact-policies': {
    singular: 'Artifact Policy', apiPath: 'admin/artifact-policies', listKey: 'artifact-policies',
    cols: ['name', 'max_size_bytes', 'retention_days', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'max_size_bytes', label: 'Max Size (bytes)', type: 'number', save: 'int' },
      { key: 'allowed_types', label: 'Allowed Types (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'retention_days', label: 'Retention Days', type: 'number', save: 'int' },
      { key: 'require_versioning', label: 'Require Versioning', type: 'checkbox', save: 'intBool' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'tenant-configs': {
    singular: 'Tenant Config', apiPath: 'admin/tenant-configs', listKey: 'tenant-configs',
    cols: ['name', 'tenant_id', 'scope', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'tenant_id', label: 'Tenant ID' },
      { key: 'scope', label: 'Scope', options: ['tenant', 'user', 'team'], default: 'tenant' },
      { key: 'allowed_models', label: 'Allowed Models (JSON)', textarea: true, save: 'json' },
      { key: 'denied_models', label: 'Denied Models (JSON)', textarea: true, save: 'json' },
      { key: 'allowed_tools', label: 'Allowed Tools (JSON)', textarea: true, save: 'json' },
      { key: 'max_tokens_daily', label: 'Max Tokens/Day', type: 'number', save: 'int' },
      { key: 'max_cost_daily', label: 'Max Cost/Day', type: 'number', save: 'float' },
      { key: 'max_tokens_monthly', label: 'Max Tokens/Month', type: 'number', save: 'int' },
      { key: 'max_cost_monthly', label: 'Max Cost/Month', type: 'number', save: 'float' },
      { key: 'features', label: 'Features (JSON)', textarea: true, save: 'json' },
      { key: 'config_overrides', label: 'Config Overrides (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'collaboration-sessions': {
    singular: 'Collaboration Session', apiPath: 'admin/collaboration-sessions', listKey: 'collaboration-sessions',
    cols: ['name', 'session_type', 'max_participants', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'session_type', label: 'Session Type', options: ['pair', 'team', 'broadcast', 'review'], default: 'team' },
      { key: 'max_participants', label: 'Max Participants', type: 'number', save: 'int', default: 10 },
      { key: 'presence_ttl_ms', label: 'Presence TTL (ms)', type: 'number', save: 'int', default: 30000 },
      { key: 'auto_close_idle_ms', label: 'Auto Close Idle (ms)', type: 'number', save: 'int' },
      { key: 'handoff_enabled', label: 'Handoff Enabled', type: 'checkbox', save: 'bool', default: true },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'graph-configs': {
    singular: 'Graph Config', apiPath: 'admin/graph-configs', listKey: 'graph-configs',
    cols: ['name', 'graph_type', 'max_depth', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'graph_type', label: 'Graph Type', options: ['entity', 'timeline', 'knowledge', 'dependency'], default: 'entity' },
      { key: 'max_depth', label: 'Max Depth', type: 'number', save: 'int', default: 3 },
      { key: 'entity_types', label: 'Entity Types (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'relationship_types', label: 'Relationship Types (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'auto_link', label: 'Auto Link', type: 'checkbox', save: 'bool', default: true },
      { key: 'scoring_weights', label: 'Scoring Weights (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'plugin-configs': {
    singular: 'Plugin Config', apiPath: 'admin/plugin-configs', listKey: 'plugin-configs',
    cols: ['name', 'plugin_type', 'version', 'trust_level', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'plugin_type', label: 'Plugin Type', options: ['core', 'community', 'private', 'enterprise'], default: 'community' },
      { key: 'package_name', label: 'Package Name', default: 'unknown' },
      { key: 'version', label: 'Version', default: '1.0.0' },
      { key: 'capabilities', label: 'Capabilities (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'trust_level', label: 'Trust Level', options: ['trusted', 'community', 'sandboxed'], default: 'community' },
      { key: 'auto_update', label: 'Auto Update', type: 'checkbox', save: 'bool' },
      { key: 'config', label: 'Config (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'scaffold-templates': {
    singular: 'Scaffold Template', apiPath: 'admin/scaffold-templates', listKey: 'scaffold-templates',
    cols: ['name', 'template_type', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'template_type', label: 'Template Type', options: ['basic-agent', 'tool-calling-agent', 'rag-pipeline', 'workflow', 'multi-agent', 'mcp-server', 'full-stack'], default: 'basic-agent' },
      { key: 'files', label: 'Files (JSON)', textarea: true, rows: 6, save: 'jsonStr' },
      { key: 'dependencies', label: 'Dependencies (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'dev_dependencies', label: 'Dev Dependencies (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'variables', label: 'Variables (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'post_install', label: 'Post Install Command' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'recipe-configs': {
    singular: 'Recipe Config', apiPath: 'admin/recipe-configs', listKey: 'recipe-configs',
    cols: ['name', 'recipe_type', 'model', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'recipe_type', label: 'Recipe Type', options: ['workflow', 'governed', 'approval', 'acl-rag', 'multi-tenant', 'eval-routed', 'memory', 'event-driven', 'safe-exec'], default: 'workflow' },
      { key: 'model', label: 'Model' },
      { key: 'provider', label: 'Provider' },
      { key: 'system_prompt', label: 'System Prompt', textarea: true, rows: 3 },
      { key: 'tools', label: 'Tools (JSON)', textarea: true, save: 'json' },
      { key: 'guardrails', label: 'Guardrails (JSON)', textarea: true, save: 'json' },
      { key: 'max_steps', label: 'Max Steps', type: 'number', save: 'int', default: 10 },
      { key: 'options', label: 'Options (JSON)', textarea: true, save: 'json' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'widget-configs': {
    singular: 'Widget Config', apiPath: 'admin/widget-configs', listKey: 'widget-configs',
    cols: ['name', 'widget_type', 'max_data_points', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'widget_type', label: 'Widget Type', options: ['table', 'chart', 'form', 'code', 'timeline', 'image'], default: 'table' },
      { key: 'default_options', label: 'Default Options (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'allowed_contexts', label: 'Allowed Contexts (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'max_data_points', label: 'Max Data Points', type: 'number', save: 'int' },
      { key: 'refresh_interval_ms', label: 'Refresh Interval (ms)', type: 'number', save: 'int' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'validation-rules': {
    singular: 'Validation Rule', apiPath: 'admin/validation-rules', listKey: 'validation-rules',
    cols: ['name', 'rule_type', 'target', 'severity', 'enabled'],
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'rule_type', label: 'Rule Type', options: ['required', 'range', 'pattern', 'custom'], default: 'required' },
      { key: 'target', label: 'Target', options: ['agent-config', 'workflow-config', 'tool-config'], default: 'agent-config' },
      { key: 'condition', label: 'Condition (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'severity', label: 'Severity', options: ['error', 'warning', 'info'], default: 'error' },
      { key: 'message', label: 'Message' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },

  'sg-brands': {
    singular: 'SG Brand', apiPath: 'admin/sg-brands', listKey: 'sg-brands',
    cols: ['name', 'slug', 'enabled'],
    fields: [
      { key: 'name', label: 'Brand Name' },
      { key: 'slug', label: 'Brand Slug' },
      { key: 'description', label: 'Description' },
      { key: 'voice', label: 'Brand Voice', textarea: true },
      { key: 'website_url', label: 'Website URL' },
      { key: 'goals_json', label: 'Goals (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-channels': {
    singular: 'SG Channel', apiPath: 'admin/sg-channels', listKey: 'sg-channels',
    cols: ['platform', 'handle', 'status', 'enabled'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'platform', label: 'Platform', options: ['linkedin', 'instagram', 'facebook', 'tiktok', 'medium', 'blogger', 'x', 'youtube'], default: 'linkedin' },
      { key: 'handle', label: 'Handle' },
      { key: 'account_ref', label: 'Account Ref' },
      { key: 'posting_timezone', label: 'Posting Timezone', default: 'UTC' },
      { key: 'cadence_json', label: 'Cadence (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'status', label: 'Status', options: ['active', 'paused', 'archived'], default: 'active' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-campaigns': {
    singular: 'SG Campaign', apiPath: 'admin/sg-campaigns', listKey: 'sg-campaigns',
    cols: ['name', 'objective', 'status', 'enabled'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'name', label: 'Campaign Name' },
      { key: 'objective', label: 'Objective' },
      { key: 'target_audience', label: 'Target Audience' },
      { key: 'start_date', label: 'Start Date' },
      { key: 'end_date', label: 'End Date' },
      { key: 'budget_json', label: 'Budget (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'status', label: 'Status', options: ['planning', 'active', 'completed', 'paused'], default: 'planning' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-content-pillars': {
    singular: 'SG Content Pillar', apiPath: 'admin/sg-content-pillars', listKey: 'sg-content-pillars',
    cols: ['name', 'weight', 'enabled'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'name', label: 'Pillar Name' },
      { key: 'description', label: 'Description' },
      { key: 'weight', label: 'Weight', type: 'number', save: 'float', default: 1 },
      { key: 'themes_json', label: 'Themes (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-content-queue': {
    singular: 'SG Content Item', apiPath: 'admin/sg-content-queue', listKey: 'sg-content-queue',
    cols: ['title', 'format', 'status', 'scheduled_for', 'updated_at'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'campaign_id', label: 'Campaign ID' },
      { key: 'channel_id', label: 'Channel ID' },
      { key: 'title', label: 'Title' },
      { key: 'brief', label: 'Brief', textarea: true },
      { key: 'content_text', label: 'Generated Content', textarea: true, rows: 8 },
      { key: 'format', label: 'Format', options: ['text', 'carousel', 'video', 'reel', 'article', 'thread'], default: 'text' },
      { key: 'status', label: 'Status', options: ['draft', 'ready', 'approved', 'scheduled', 'published', 'failed'], default: 'draft' },
      { key: 'scheduled_for', label: 'Scheduled For (ISO)' },
      { key: 'asset_urls_json', label: 'Asset URLs (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'metadata_json', label: 'Metadata (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-growth-experiments': {
    singular: 'SG Growth Experiment', apiPath: 'admin/sg-growth-experiments', listKey: 'sg-growth-experiments',
    cols: ['hypothesis', 'success_metric', 'status', 'enabled'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'campaign_id', label: 'Campaign ID' },
      { key: 'hypothesis', label: 'Hypothesis', textarea: true },
      { key: 'variant_a_json', label: 'Variant A (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'variant_b_json', label: 'Variant B (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'success_metric', label: 'Success Metric' },
      { key: 'status', label: 'Status', options: ['draft', 'running', 'paused', 'completed', 'failed'], default: 'draft' },
      { key: 'result_summary', label: 'Result Summary', textarea: true },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-kpi-snapshots': {
    singular: 'SG KPI Snapshot', apiPath: 'admin/sg-kpi-snapshots', listKey: 'sg-kpi-snapshots',
    cols: ['snapshot_date', 'source'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'channel_id', label: 'Channel ID' },
      { key: 'snapshot_date', label: 'Snapshot Date' },
      { key: 'metrics_json', label: 'Metrics (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'source', label: 'Source' },
    ],
  },
  'sg-agent-profiles': {
    singular: 'SG Agent Profile', apiPath: 'admin/sg-agent-profiles', listKey: 'sg-agent-profiles',
    cols: ['name', 'role', 'policy_key', 'enabled'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'name', label: 'Agent Name' },
      { key: 'role', label: 'Role' },
      { key: 'instructions', label: 'Instructions', textarea: true },
      { key: 'tool_names', label: 'Tool Names (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'policy_key', label: 'Policy Key' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-workflow-templates': {
    singular: 'SG Workflow Template', apiPath: 'admin/sg-workflow-templates', listKey: 'sg-workflow-templates',
    cols: ['name', 'trigger_type', 'enabled'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'name', label: 'Template Name' },
      { key: 'description', label: 'Description' },
      { key: 'step_graph_json', label: 'Step Graph (JSON)', textarea: true, rows: 6, save: 'jsonStr' },
      { key: 'trigger_type', label: 'Trigger Type', options: ['schedule', 'webhook', 'manual', 'event'], default: 'manual' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-tool-bindings': {
    singular: 'SG Tool Binding', apiPath: 'admin/sg-tool-bindings', listKey: 'sg-tool-bindings',
    cols: ['tool_name', 'provider', 'enabled'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'channel_id', label: 'Channel ID' },
      { key: 'tool_name', label: 'Tool Name' },
      { key: 'provider', label: 'Provider' },
      { key: 'config_json', label: 'Config (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-strategy-settings': {
    singular: 'SG Strategy Setting', apiPath: 'admin/sg-strategy-settings', listKey: 'sg-strategy-settings',
    cols: ['key', 'enabled'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'key', label: 'Setting Key' },
      { key: 'value_json', label: 'Value (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sg-prompt-variants': {
    singular: 'SG Prompt Variant', apiPath: 'admin/sg-prompt-variants', listKey: 'sg-prompt-variants',
    cols: ['key', 'name', 'version', 'is_active', 'enabled'],
    fields: [
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'key', label: 'Prompt Key' },
      { key: 'name', label: 'Name' },
      { key: 'template', label: 'Template', textarea: true, rows: 5 },
      { key: 'variables', label: 'Variables (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'version', label: 'Version', default: '1.0' },
      { key: 'is_active', label: 'Is Active', type: 'checkbox', save: 'bool', default: false },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sgap-agents': {
    singular: 'SGAP Agent', apiPath: 'admin/sgap-agents', listKey: 'sgap-agents',
    cols: ['display_name', 'role', 'authority_level', 'enabled'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'name', label: 'Name' },
      { key: 'display_name', label: 'Display Name' },
      { key: 'role', label: 'Role' },
      { key: 'description', label: 'Description', textarea: true },
      { key: 'system_prompt', label: 'System Prompt', textarea: true, rows: 6 },
      { key: 'tool_names', label: 'Tool Names (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'authority_level', label: 'Authority Level', options: ['create_draft', 'recommend', 'final_approval', 'veto'], default: 'recommend' },
      { key: 'skill_key', label: 'Skill Key' },
      { key: 'worker_agent_id', label: 'Worker Agent ID' },
      { key: 'priority', label: 'Priority', type: 'number', save: 'int', default: 0 },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sgap-workflow-runs': {
    singular: 'SGAP Workflow Run', apiPath: 'admin/sgap-workflow-runs', listKey: 'sgap-workflow-runs',
    cols: ['brand_id', 'workflow_template_id', 'status', 'current_stage', 'created_at'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'workflow_template_id', label: 'Workflow Template ID' },
      { key: 'status', label: 'Status', options: ['pending', 'running', 'blocked', 'completed', 'failed', 'cancelled'], default: 'pending' },
      { key: 'current_stage', label: 'Current Stage' },
      { key: 'current_agent_id', label: 'Current Agent ID' },
      { key: 'input_json', label: 'Input (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'state_json', label: 'State (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'error_message', label: 'Error Message', textarea: true },
      { key: 'completed_at', label: 'Completed At' },
    ],
  },
  'sgap-agent-threads': {
    singular: 'SGAP Agent Thread', apiPath: 'admin/sgap-agent-threads', listKey: 'sgap-agent-threads',
    cols: ['workflow_run_id', 'stage', 'created_at'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'workflow_run_id', label: 'Workflow Run ID' },
      { key: 'stage', label: 'Stage' },
    ],
  },
  'sgap-agent-messages': {
    singular: 'SGAP Agent Message', apiPath: 'admin/sgap-agent-messages', listKey: 'sgap-agent-messages',
    cols: ['thread_id', 'from_agent_id', 'to_agent_id', 'message_type', 'responded'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'thread_id', label: 'Thread ID' },
      { key: 'from_agent_id', label: 'From Agent ID' },
      { key: 'to_agent_id', label: 'To Agent ID' },
      { key: 'message_type', label: 'Message Type', options: ['instruction', 'draft', 'feedback', 'approval_request', 'approval_response', 'handoff', 'metric_update'], default: 'instruction' },
      { key: 'content_json', label: 'Content (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'requires_response', label: 'Requires Response', type: 'checkbox', save: 'bool', default: false },
      { key: 'responded', label: 'Responded', type: 'checkbox', save: 'bool', default: false },
      { key: 'response_message_id', label: 'Response Message ID' },
      { key: 'response_json', label: 'Response (JSON)', textarea: true, save: 'jsonStr' },
    ],
  },
  'sgap-approvals': {
    singular: 'SGAP Approval', apiPath: 'admin/sgap-approvals', listKey: 'sgap-approvals',
    cols: ['workflow_run_id', 'required_by_agent_id', 'status', 'created_at'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'workflow_run_id', label: 'Workflow Run ID' },
      { key: 'content_item_id', label: 'Content Item ID' },
      { key: 'required_by_agent_id', label: 'Required By Agent ID' },
      { key: 'approval_from_agent_id', label: 'Approval From Agent ID' },
      { key: 'status', label: 'Status', options: ['pending', 'approved', 'rejected', 'escalated'], default: 'pending' },
      { key: 'feedback_json', label: 'Feedback (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'resolved_by_agent_id', label: 'Resolved By Agent ID' },
    ],
  },
  'sgap-audit-log': {
    singular: 'SGAP Audit Event', apiPath: 'admin/sgap-audit-log', listKey: 'sgap-audit-log',
    cols: ['workflow_run_id', 'agent_id', 'action', 'created_at'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'workflow_run_id', label: 'Workflow Run ID' },
      { key: 'agent_id', label: 'Agent ID' },
      { key: 'action', label: 'Action' },
      { key: 'details_json', label: 'Details (JSON)', textarea: true, save: 'jsonStr' },
    ],
  },
  'sgap-skills': {
    singular: 'SGAP Skill Mapping', apiPath: 'admin/sgap-skills', listKey: 'sgap-skills',
    cols: ['agent_role', 'skill_id', 'tool_policy_key', 'enabled'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'agent_role', label: 'Agent Role' },
      { key: 'skill_id', label: 'Skill ID' },
      { key: 'tool_policy_key', label: 'Tool Policy Key' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sgap-social-media-tools': {
    singular: 'SGAP Social Tool', apiPath: 'admin/sgap-social-media-tools', listKey: 'sgap-social-media-tools',
    cols: ['platform', 'auth_type', 'rate_limit_per_min', 'enabled'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'platform', label: 'Platform' },
      { key: 'api_base_url', label: 'API Base URL' },
      { key: 'api_version', label: 'API Version', default: '1.0' },
      { key: 'auth_type', label: 'Auth Type', options: ['oauth2', 'bearer', 'api_key', 'oauth1'], default: 'oauth2' },
      { key: 'rate_limit_per_min', label: 'Rate Limit / Min', type: 'number', save: 'int', default: 100 },
      { key: 'supports_scheduling', label: 'Supports Scheduling', type: 'checkbox', save: 'bool', default: false },
      { key: 'supports_video', label: 'Supports Video', type: 'checkbox', save: 'bool', default: false },
      { key: 'supports_images', label: 'Supports Images', type: 'checkbox', save: 'bool', default: false },
      { key: 'supports_analytics', label: 'Supports Analytics', type: 'checkbox', save: 'bool', default: true },
      { key: 'max_characters', label: 'Max Characters', type: 'number', save: 'int' },
      { key: 'config_json', label: 'Config (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sgap-content-performance': {
    singular: 'SGAP Content Performance', apiPath: 'admin/sgap-content-performance', listKey: 'sgap-content-performance',
    cols: ['content_item_id', 'platform', 'views', 'engagement', 'published_at'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'content_item_id', label: 'Content Item ID' },
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'platform', label: 'Platform' },
      { key: 'published_at', label: 'Published At' },
      { key: 'views', label: 'Views', type: 'number', save: 'int', default: 0 },
      { key: 'engagement', label: 'Engagement', type: 'number', save: 'int', default: 0 },
      { key: 'reach', label: 'Reach', type: 'number', save: 'int', default: 0 },
      { key: 'impressions', label: 'Impressions', type: 'number', save: 'int', default: 0 },
      { key: 'clicks', label: 'Clicks', type: 'number', save: 'int', default: 0 },
      { key: 'conversions', label: 'Conversions', type: 'number', save: 'int', default: 0 },
      { key: 'metadata_json', label: 'Metadata (JSON)', textarea: true, save: 'jsonStr' },
      { key: 'synced_at', label: 'Synced At' },
    ],
  },
  'sgap-phase2-configs': {
    singular: 'SGAP Phase 2 Config', apiPath: 'admin/sgap-phase2-configs', listKey: 'sgap-phase2-configs',
    cols: ['brand_id', 'workflow_template_id', 'max_feedback_rounds', 'min_research_confidence', 'enabled'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'brand_id', label: 'Brand ID' },
      { key: 'workflow_template_id', label: 'Workflow Template ID' },
      { key: 'writer_agent_id', label: 'Writer Agent ID' },
      { key: 'researcher_agent_id', label: 'Researcher Agent ID' },
      { key: 'editor_agent_id', label: 'Editor Agent ID' },
      { key: 'max_feedback_rounds', label: 'Max Feedback Rounds', type: 'number', save: 'int', default: 2 },
      { key: 'min_research_confidence', label: 'Min Research Confidence', type: 'number', save: 'float', default: 0.7 },
      { key: 'require_research_citations', label: 'Require Citations', type: 'checkbox', save: 'bool', default: true },
      { key: 'auto_escalate_to_compliance', label: 'Auto Escalate to Compliance', type: 'checkbox', save: 'bool', default: true },
      { key: 'output_format', label: 'Output Format', options: ['markdown', 'json'], default: 'markdown' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'sgap-content-revisions': {
    singular: 'SGAP Content Revision', apiPath: 'admin/sgap-content-revisions', listKey: 'sgap-content-revisions',
    cols: ['workflow_run_id', 'content_item_id', 'stage', 'revision_index', 'created_at'],
    fields: [
      { key: 'application_scope', label: 'Scope', default: 'sgap' },
      { key: 'workflow_run_id', label: 'Workflow Run ID' },
      { key: 'content_item_id', label: 'Content Item ID' },
      { key: 'agent_id', label: 'Agent ID' },
      { key: 'stage', label: 'Stage', options: ['writer', 'researcher', 'editor'], default: 'writer' },
      { key: 'revision_index', label: 'Revision Index', type: 'number', save: 'int', default: 1 },
      { key: 'content_text', label: 'Content Text', textarea: true, rows: 8 },
      { key: 'notes_json', label: 'Notes (JSON)', textarea: true, save: 'jsonStr' },
    ],
  },

  'workflow-runs': {
    singular: 'Workflow Run', apiPath: 'workflow-runs', listKey: 'runs',
    cols: ['id', 'workflow_id', 'status', 'started_at'],
    fields: [],
    readOnly: true,
  },
  'guardrail-evals': {
    singular: 'Guardrail Eval', apiPath: 'guardrail-evals', listKey: 'evals',
    cols: ['id', 'stage', 'overall_decision', 'created_at'],
    fields: [],
    readOnly: true,
  },
  'memory-extraction-events': {
    singular: 'Memory Extraction Event', apiPath: 'memory-extraction-events', listKey: 'events',
    cols: ['id', 'self_disclosure', 'regex_entities_count', 'llm_entities_count', 'merged_entities_count', 'created_at'],
    fields: [],
    readOnly: true,
  },
};
