import type { AdminTabDef } from '@weaveintel/core';

/**
 * Prompt capability tabs are isolated in a dedicated module so the monolithic
 * admin schema file stays maintainable as prompt features expand.
 */
export const PROMPT_CAPABILITY_ADMIN_TABS: Record<string, AdminTabDef> = {
  'prompts': {
    singular: 'Prompt', apiPath: 'admin/prompts', listKey: 'prompts',
    cols: ['name', 'prompt_type', 'status', 'version', 'enabled'],
    fields: [
      { key: 'key', label: 'Key' },
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Detailed Description (model-facing)' },
      { key: 'category', label: 'Category' },
      { key: 'prompt_type', label: 'Prompt Type', options: ['template', 'structured', 'fewShot', 'chain', 'router', 'judge', 'optimizer', 'modalityPreset'], default: 'template' },
      { key: 'owner', label: 'Owner' },
      { key: 'status', label: 'Status', options: ['draft', 'published', 'retired'], default: 'published' },
      { key: 'tags', label: 'Tags (JSON array)', textarea: true, rows: 2, save: 'json' },
      { key: 'template', label: 'Template', textarea: true, rows: 8 },
      { key: 'variables', label: 'Variables (JSON array or comma-separated)', textarea: true, rows: 4 },
      { key: 'model_compatibility', label: 'Model Compatibility (JSON)', textarea: true, rows: 3, save: 'json' },
      { key: 'execution_defaults', label: 'Execution Defaults (JSON)', textarea: true, rows: 3, save: 'json' },
      { key: 'framework', label: 'Framework (JSON)', textarea: true, rows: 3, save: 'json' },
      { key: 'metadata', label: 'Metadata (JSON)', textarea: true, rows: 3, save: 'json' },
      { key: 'version', label: 'Version', default: '1.0' },
      { key: 'is_default', label: 'Default', type: 'checkbox', save: 'bool' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'prompt-versions': {
    singular: 'Prompt Version', apiPath: 'admin/prompt-versions', listKey: 'versions',
    cols: ['prompt_id', 'version', 'status', 'is_active', 'enabled'],
    fields: [
      { key: 'prompt_id', label: 'Prompt ID (from prompts table)' },
      { key: 'version', label: 'Version (semantic, e.g. 1.0, 1.1)' },
      { key: 'status', label: 'Status', options: ['draft', 'published', 'retired'], default: 'draft' },
      { key: 'template', label: 'Template', textarea: true, rows: 8 },
      { key: 'variables', label: 'Variables (JSON array or comma-separated)', textarea: true, rows: 4 },
      { key: 'model_compatibility', label: 'Model Compatibility (JSON)', textarea: true, rows: 3, save: 'json' },
      { key: 'execution_defaults', label: 'Execution Defaults (JSON)', textarea: true, rows: 3, save: 'json' },
      { key: 'framework', label: 'Framework (JSON)', textarea: true, rows: 3, save: 'json' },
      { key: 'metadata', label: 'Metadata (JSON)', textarea: true, rows: 3, save: 'json' },
      { key: 'is_active', label: 'Active Version', type: 'checkbox', save: 'bool', default: false },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'prompt-experiments': {
    singular: 'Prompt Experiment', apiPath: 'admin/prompt-experiments', listKey: 'experiments',
    cols: ['prompt_id', 'name', 'status', 'enabled'],
    fields: [
      { key: 'prompt_id', label: 'Prompt ID (from prompts table)' },
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description (operator and model-facing)' },
      { key: 'status', label: 'Status', options: ['draft', 'active', 'completed'], default: 'draft' },
      { key: 'variants_json', label: 'Variants (JSON array: [{version,weight,label}])', textarea: true, rows: 6, save: 'jsonStr' },
      { key: 'assignment_key_template', label: 'Assignment Key Template (optional)' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'prompt-eval-datasets': {
    singular: 'Prompt Eval Dataset', apiPath: 'admin/prompt-eval-datasets', listKey: 'datasets',
    cols: ['prompt_id', 'name', 'prompt_version', 'status', 'enabled'],
    fields: [
      { key: 'prompt_id', label: 'Prompt ID (from prompts table)' },
      { key: 'name', label: 'Dataset Name' },
      { key: 'description', label: 'Description (evaluation intent and coverage)' },
      { key: 'prompt_version', label: 'Prompt Version (optional pin)' },
      { key: 'status', label: 'Status', options: ['draft', 'active', 'archived'], default: 'draft' },
      { key: 'pass_threshold', label: 'Pass Threshold (0-1)', type: 'number', default: 0.75 },
      { key: 'cases_json', label: 'Cases (JSON array of eval cases)', textarea: true, rows: 8, save: 'jsonStr' },
      { key: 'rubric_json', label: 'Rubric (JSON array of criteria)', textarea: true, rows: 6, save: 'jsonStr' },
      { key: 'metadata', label: 'Metadata (JSON)', textarea: true, rows: 4, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'prompt-eval-runs': {
    singular: 'Prompt Eval Run', apiPath: 'admin/prompt-eval-runs', listKey: 'runs',
    cols: ['dataset_id', 'prompt_version', 'avg_score', 'status', 'created_at'],
    fields: [
      { key: 'dataset_id', label: 'Dataset ID (from prompt eval datasets)' },
      { key: 'prompt_id', label: 'Prompt ID' },
      { key: 'prompt_version', label: 'Prompt Version Evaluated' },
      { key: 'status', label: 'Status', options: ['completed', 'failed'], default: 'completed' },
      { key: 'avg_score', label: 'Average Score', type: 'number', default: 0 },
      { key: 'passed_cases', label: 'Passed Cases', type: 'number', save: 'int', default: 0 },
      { key: 'failed_cases', label: 'Failed Cases', type: 'number', save: 'int', default: 0 },
      { key: 'total_cases', label: 'Total Cases', type: 'number', save: 'int', default: 0 },
      { key: 'results_json', label: 'Results (JSON array)', textarea: true, rows: 8, save: 'jsonStr' },
      { key: 'summary_json', label: 'Summary (JSON object)', textarea: true, rows: 4, save: 'jsonStr' },
      { key: 'metadata', label: 'Metadata (JSON)', textarea: true, rows: 3, save: 'jsonStr' },
      { key: 'completed_at', label: 'Completed At (ISO datetime, optional)' },
    ],
  },
  'prompt-optimizers': {
    singular: 'Prompt Optimizer', apiPath: 'admin/prompt-optimizers', listKey: 'optimizers',
    cols: ['key', 'name', 'implementation_kind', 'enabled'],
    fields: [
      { key: 'key', label: 'Key (optimizer selector key)' },
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Detailed Description (model-facing)' },
      { key: 'implementation_kind', label: 'Implementation Kind', options: ['rule', 'llm', 'hybrid'], default: 'rule' },
      { key: 'config', label: 'Config (JSON)', textarea: true, rows: 6, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'prompt-optimization-runs': {
    singular: 'Prompt Optimization Run', apiPath: 'admin/prompt-optimization-runs', listKey: 'runs',
    cols: ['prompt_id', 'source_version', 'candidate_version', 'status', 'created_at'],
    fields: [
      { key: 'prompt_id', label: 'Prompt ID (from prompts table)' },
      { key: 'source_version', label: 'Source Version' },
      { key: 'candidate_version', label: 'Candidate Version' },
      { key: 'optimizer_id', label: 'Optimizer ID (optional)' },
      { key: 'objective', label: 'Optimization Objective' },
      { key: 'source_template', label: 'Source Template Snapshot', textarea: true, rows: 6 },
      { key: 'candidate_template', label: 'Candidate Template Snapshot', textarea: true, rows: 6 },
      { key: 'diff_json', label: 'Diff Metadata (JSON)', textarea: true, rows: 6, save: 'jsonStr' },
      { key: 'eval_baseline_json', label: 'Baseline Eval (JSON)', textarea: true, rows: 4, save: 'jsonStr' },
      { key: 'eval_candidate_json', label: 'Candidate Eval (JSON)', textarea: true, rows: 4, save: 'jsonStr' },
      { key: 'status', label: 'Status', options: ['completed', 'failed'], default: 'completed' },
      { key: 'metadata', label: 'Metadata (JSON)', textarea: true, rows: 3, save: 'jsonStr' },
    ],
  },
  'prompt-frameworks': {
    singular: 'Prompt Framework', apiPath: 'admin/prompt-frameworks', listKey: 'frameworks',
    cols: ['key', 'name', 'enabled'],
    fields: [
      { key: 'key', label: 'Key (unique short identifier, e.g. rtce)' },
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description (shown to users and agents)' },
      { key: 'sections', label: 'Sections (JSON array of PromptFrameworkSectionDef)', textarea: true, rows: 8, save: 'json' },
      { key: 'section_separator', label: 'Section Separator', default: '\n\n' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'prompt-fragments': {
    singular: 'Prompt Fragment', apiPath: 'admin/prompt-fragments', listKey: 'fragments',
    cols: ['key', 'name', 'category', 'version', 'enabled'],
    fields: [
      { key: 'key', label: 'Key (referenced in templates as {{>key}})' },
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description (shown to users and agents)' },
      { key: 'category', label: 'Category (e.g. safety, personas, output)' },
      { key: 'content', label: 'Fragment Content', textarea: true, rows: 6 },
      { key: 'variables', label: 'Variables (JSON array)', textarea: true, rows: 3, save: 'json' },
      { key: 'tags', label: 'Tags (JSON array)', textarea: true, rows: 2, save: 'json' },
      { key: 'version', label: 'Version', default: '1.0' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'prompt-contracts': {
    singular: 'Prompt Output Contract', apiPath: 'admin/prompt-contracts', listKey: 'contracts',
    cols: ['key', 'name', 'contract_type', 'enabled'],
    fields: [
      { key: 'key', label: 'Key (unique contract identifier)' },
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Detailed Description (model-facing)' },
      { key: 'contract_type', label: 'Contract Type', options: ['json', 'markdown', 'code', 'max_length', 'forbidden_content', 'structured'] },
      { key: 'schema', label: 'Schema (JSON)', textarea: true, rows: 6, save: 'jsonStr' },
      { key: 'config', label: 'Config (JSON)', textarea: true, rows: 6, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
  'prompt-strategies': {
    singular: 'Prompt Strategy', apiPath: 'admin/prompt-strategies', listKey: 'strategies',
    cols: ['key', 'name', 'enabled'],
    fields: [
      { key: 'key', label: 'Key (execution_defaults.strategy reference)' },
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Detailed Description (model-facing)' },
      { key: 'instruction_prefix', label: 'Instruction Prefix', textarea: true, rows: 4 },
      { key: 'instruction_suffix', label: 'Instruction Suffix', textarea: true, rows: 4 },
      { key: 'config', label: 'Config (JSON)', textarea: true, rows: 4, save: 'jsonStr' },
      { key: 'enabled', label: 'Enabled', type: 'checkbox', save: 'bool', default: true },
    ],
  },
};
