import type { Tool } from "@weaveintel/core";
import type { EnterpriseConnectorConfig } from "../types.js";
import type { ServiceNowProvider } from "../connectors/servicenow.js";
import { bt, ok, s, n, o, b } from "./servicenow-tool-helpers.js";

/* ================================================================
 *  PHASE 7 — Performance Analytics, Reporting, Dashboards
 * ================================================================ */
export function phase7(px: string, cfg: EnterpriseConnectorConfig, p: ServiceNowProvider): Tool[] { return [
  bt({ name: `${px}.paGetScorecard`, desc: 'Get Performance Analytics scorecard for an indicator. Returns current score, target, trend direction, breakdown data, and historical values.',
    params: { type: 'object', properties: { indicatorId: { type: 'string', description: 'sys_id of the PA indicator' } }, required: ['indicatorId'] },
    fn: async (_c, inp) => ok(await p.paGetScorecard(s(inp,'indicatorId'), cfg)) }),
  bt({ name: `${px}.paListIndicators`, desc: 'List Performance Analytics indicators (KPIs). Returns indicator name, frequency, direction (maximize/minimize), current value, unit, and associated widget.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "frequency=Daily", "active=true"' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.paListIndicators(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.paGetIndicatorScores`, desc: 'Get historical scores for a PA indicator over time. Returns data points with date and value for trend analysis.',
    params: { type: 'object', properties: { indicatorId: { type: 'string', description: 'sys_id of the PA indicator' }, periods: { type: 'number', description: 'Number of periods to retrieve (default: 12)' } }, required: ['indicatorId'] },
    fn: async (_c, inp) => ok(await p.paGetIndicatorScores(s(inp,'indicatorId'), cfg, n(inp,'periods',12))) }),
  bt({ name: `${px}.paGetBreakdown`, desc: 'Get breakdown data for a PA indicator by a breakdown element (e.g. by priority, by assignment group). Useful for segmented analysis.',
    params: { type: 'object', properties: { indicatorId: { type: 'string', description: 'sys_id of the PA indicator' }, breakdownId: { type: 'string', description: 'sys_id of the breakdown definition' } }, required: ['indicatorId', 'breakdownId'] },
    fn: async (_c, inp) => ok(await p.paGetBreakdown(s(inp,'indicatorId'), s(inp,'breakdownId'), cfg)) }),
  bt({ name: `${px}.listReports`, desc: 'List saved reports in ServiceNow. Returns report title, type (bar, pie, list, etc.), table, filter, owner.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listReports(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.getReport`, desc: 'Get a specific report definition by sys_id.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the report' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getReport(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.runReport`, desc: 'Execute a saved report and return the results. Returns rendered report data (tabular/chart data).',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the report to run' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.runReport(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.listDashboards`, desc: 'List ServiceNow dashboards (pa_dashboards). Returns dashboard name, description, owner, shared status.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listDashboards(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.getDashboard`, desc: 'Get a specific dashboard by sys_id. Returns widgets, layout, filters.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the dashboard' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getDashboard(s(inp,'id'), cfg)) }),
]; }

/* ================================================================
 *  PHASE 8 — Flow Designer, Integration Hub, Orchestration
 * ================================================================ */
export function phase8(px: string, cfg: EnterpriseConnectorConfig, p: ServiceNowProvider): Tool[] { return [
  bt({ name: `${px}.listFlows`, desc: 'List Flow Designer flows. Flows are low-code automation definitions with triggers, actions, and decisions. Returns flow name, table, active status, trigger type.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "active=true", "table=incident"' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listFlows(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.getFlow`, desc: 'Get a specific Flow Designer flow by sys_id. Returns full flow definition including trigger, conditions, actions, and subflows.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the flow' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getFlow(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.triggerFlow`, desc: 'Manually trigger a Flow Designer flow with input values. Starts an execution and returns the execution record with tracking ID.',
    params: { type: 'object', properties: { flowId: { type: 'string', description: 'sys_id of the flow to trigger' }, inputs: { type: 'object', description: 'Flow input values as key-value pairs matching the flow input variables' } }, required: ['flowId', 'inputs'] },
    fn: async (_c, inp) => ok(await p.triggerFlow(s(inp,'flowId'), o(inp,'inputs'), cfg)) }),
  bt({ name: `${px}.getFlowExecution`, desc: 'Get the status and output of a flow execution. Returns state (waiting, running, complete, error), outputs, duration, error details.',
    params: { type: 'object', properties: { executionId: { type: 'string', description: 'Execution ID returned by triggerFlow' } }, required: ['executionId'] },
    fn: async (_c, inp) => ok(await p.getFlowExecution(s(inp,'executionId'), cfg)) }),
  bt({ name: `${px}.listFlowExecutions`, desc: 'List recent flow executions. Returns execution ID, flow name, state, started_at, duration, triggered_by.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "state=complete", "flow.name=My Flow"' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listFlowExecutions(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.listActions`, desc: 'List available Flow Designer / Integration Hub actions. Actions are reusable building blocks for flows — includes spokes (ServiceNow, Slack, Teams, Jira, AWS, Azure, etc.).',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "sys_scope.name=Global"' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listActions(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.executeAction`, desc: 'Execute a standalone action (outside a flow). Useful for one-off integrations — e.g. send Slack message, create Jira ticket, run PowerShell script.',
    params: { type: 'object', properties: { actionId: { type: 'string', description: 'sys_id of the action to execute' }, inputs: { type: 'object', description: 'Action input values as key-value pairs' } }, required: ['actionId', 'inputs'] },
    fn: async (_c, inp) => ok(await p.executeAction(s(inp,'actionId'), o(inp,'inputs'), cfg)) }),
  bt({ name: `${px}.getActionExecution`, desc: 'Get the result of a standalone action execution.',
    params: { type: 'object', properties: { executionId: { type: 'string', description: 'Execution ID from executeAction' } }, required: ['executionId'] },
    fn: async (_c, inp) => ok(await p.getActionExecution(s(inp,'executionId'), cfg)) }),
  bt({ name: `${px}.listMidServers`, desc: 'List MID Servers in the instance. MID Servers are Java applications that facilitate communication between ServiceNow and external resources (for Discovery, Orchestration, IntegrationHub).',
    params: { type: 'object', properties: {} },
    fn: async (_c, _inp) => ok(await p.listMidServers(cfg)) }),
  bt({ name: `${px}.getMidServer`, desc: 'Get details of a specific MID Server. Returns name, status (Up/Down), IP address, host_name, version, validated, last_refreshed.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the MID Server' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getMidServer(s(inp,'id'), cfg)) }),
]; }

/* ================================================================
 *  PHASE 9 — Incident Lifecycle, CSM, HR, Interactions
 * ================================================================ */
export function phase9(px: string, cfg: EnterpriseConnectorConfig, p: ServiceNowProvider): Tool[] { return [
  bt({ name: `${px}.resolveIncident`, desc: 'Resolve an incident. Sets state to Resolved (6) and requires resolution information. Fields: close_code (Solved Permanently, Solved Workaround, Not Solved, Duplicate), close_notes.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the incident' }, resolution: { type: 'object', description: '{ close_code: "Solved (Permanently)"|"Solved (Workaround Provided)"|"Not Solved"|"Closed/Resolved by Caller", close_notes: string }' } }, required: ['id', 'resolution'] },
    fn: async (_c, inp) => ok(await p.resolveIncident(s(inp,'id'), o(inp,'resolution'), cfg)) }),
  bt({ name: `${px}.closeIncident`, desc: 'Close an incident. Moves from Resolved to Closed (7). Can only be done after resolution.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the incident' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.closeIncident(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.reassignIncident`, desc: 'Reassign an incident to a different group and/or individual. Updates assignment_group and assigned_to fields.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the incident' }, assignmentGroup: { type: 'string', description: 'sys_id of the new assignment group' }, assignedTo: { type: 'string', description: 'sys_id of the new assigned individual' } }, required: ['id', 'assignmentGroup', 'assignedTo'] },
    fn: async (_c, inp) => ok(await p.reassignIncident(s(inp,'id'), s(inp,'assignmentGroup'), s(inp,'assignedTo'), cfg)) }),
  bt({ name: `${px}.escalateIncident`, desc: 'Escalate an incident by changing its priority. Triggers escalation notifications and SLA recalculation.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the incident' }, newPriority: { type: 'string', description: 'New priority value: 1 (Critical), 2 (High), 3 (Moderate), 4 (Low), 5 (Planning)' } }, required: ['id', 'newPriority'] },
    fn: async (_c, inp) => ok(await p.escalateIncident(s(inp,'id'), s(inp,'newPriority'), cfg)) }),
  bt({ name: `${px}.listIncidentTasks`, desc: 'List tasks associated with an incident. Incident tasks are sub-activities needed to resolve the parent incident.',
    params: { type: 'object', properties: { incidentId: { type: 'string', description: 'sys_id of the parent incident' } }, required: ['incidentId'] },
    fn: async (_c, inp) => ok(await p.listIncidentTasks(s(inp,'incidentId'), cfg)) }),
  bt({ name: `${px}.createIncidentTask`, desc: 'Create a task under an incident. Fields: short_description (required), assignment_group, assigned_to, priority.',
    params: { type: 'object', properties: { incidentId: { type: 'string', description: 'sys_id of the parent incident' }, data: { type: 'object', description: 'Task fields: short_description (required), assignment_group, assigned_to, priority, description' } }, required: ['incidentId', 'data'] },
    fn: async (_c, inp) => ok(await p.createIncidentTask(s(inp,'incidentId'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.listCases`, desc: 'List Customer Service Management (CSM) cases. Cases track customer issues across channels. Returns case number, state, priority, contact, account.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Encoded query filter' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listCases(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.getCase`, desc: 'Get a specific CSM case by sys_id.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the case' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getCase(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.createCase`, desc: 'Create a new CSM case. Fields: short_description (required), contact, account, priority, description, channel (phone, email, web, chat).',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Case fields: short_description (required), contact, account, priority, description, channel' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createCase(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateCase`, desc: 'Update a CSM case. Common updates: state, priority, assigned_to, work_notes, resolution_code.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the case' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateCase(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.listHRCases`, desc: 'List HR Service Delivery cases (sn_hr_core_case). Tracks employee requests: benefits, payroll, leave, onboarding.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Encoded query filter' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listHRCases(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.getHRCase`, desc: 'Get a specific HR case by sys_id.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the HR case' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getHRCase(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.createHRCase`, desc: 'Create a new HR case. Fields: short_description (required), hr_service, subject_person, opened_for, priority.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'HR case fields: short_description (required), hr_service, subject_person, opened_for, priority, description' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createHRCase(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.createInteraction`, desc: 'Create an agent-facing interaction record. Interactions represent live contacts (phone, chat, walk-up) and can spawn incidents, cases, or catalog requests.',
    params: { type: 'object', properties: { data: { type: 'object', description: '{ type: "phone"|"chat"|"walk-up"|"email", short_description: string, opened_for: string (user sys_id) }' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createInteraction(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.getInteraction`, desc: 'Get a specific interaction record by sys_id.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the interaction' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getInteraction(s(inp,'id'), cfg)) }),
]; }

/* ================================================================
 *  PHASE 10 — DevOps, CI/CD, Update Sets, App Repository
 * ================================================================ */
export function phase10(px: string, cfg: EnterpriseConnectorConfig, p: ServiceNowProvider): Tool[] { return [
  bt({ name: `${px}.devopsListPipelines`, desc: 'List DevOps pipelines. Pipelines represent CI/CD workflows connecting external tools (Jenkins, Azure DevOps, GitHub Actions) with ServiceNow change management.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.devopsListPipelines(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.devopsGetPipeline`, desc: 'Get a specific DevOps pipeline definition by sys_id.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the pipeline' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.devopsGetPipeline(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.devopsCreateChangeFromPipeline`, desc: 'Create a change request from a DevOps pipeline execution. Automates change management for CI/CD deployments.',
    params: { type: 'object', properties: { pipelineId: { type: 'string', description: 'sys_id of the pipeline' }, data: { type: 'object', description: 'Change data: short_description, justification, implementation_plan, backout_plan, test_plan' } }, required: ['pipelineId', 'data'] },
    fn: async (_c, inp) => ok(await p.devopsCreateChangeFromPipeline(s(inp,'pipelineId'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.devopsGetArtifact`, desc: 'Get a DevOps artifact (build/release output) by sys_id.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the artifact' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.devopsGetArtifact(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.devopsListArtifactVersions`, desc: 'List versions of a DevOps artifact. Returns version numbers, build info, and deployment history.',
    params: { type: 'object', properties: { artifactId: { type: 'string', description: 'sys_id of the artifact' } }, required: ['artifactId'] },
    fn: async (_c, inp) => ok(await p.devopsListArtifactVersions(s(inp,'artifactId'), cfg)) }),
  bt({ name: `${px}.appRepoListApps`, desc: 'List applications from the ServiceNow App Repository (Store). Returns app name, version, vendor, description, install status.',
    params: { type: 'object', properties: {} },
    fn: async (_c, _inp) => ok(await p.appRepoListApps(cfg)) }),
  bt({ name: `${px}.appRepoInstall`, desc: 'Install an application from the ServiceNow Store. Triggers background installation job.',
    params: { type: 'object', properties: { appId: { type: 'string', description: 'sys_id of the app to install' } }, required: ['appId'] },
    fn: async (_c, inp) => ok(await p.appRepoInstall(s(inp,'appId'), cfg)) }),
  bt({ name: `${px}.appRepoGetAvailableUpdates`, desc: 'Check for available updates to installed applications.',
    params: { type: 'object', properties: {} },
    fn: async (_c, _inp) => ok(await p.appRepoGetAvailableUpdates(cfg)) }),
  bt({ name: `${px}.appRepoRollback`, desc: 'Rollback an application to a previous version. Reverts application files to the specified version.',
    params: { type: 'object', properties: { appId: { type: 'string', description: 'sys_id of the app' }, version: { type: 'string', description: 'Target version to rollback to, e.g. "1.2.0"' } }, required: ['appId', 'version'] },
    fn: async (_c, inp) => ok(await p.appRepoRollback(s(inp,'appId'), s(inp,'version'), cfg)) }),
  bt({ name: `${px}.listUpdateSets`, desc: 'List Update Sets (sys_update_set). Update Sets track configuration changes for migration between instances (Dev → Test → Prod).',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "state=in progress", "application=Global"' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listUpdateSets(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.getUpdateSet`, desc: 'Get a specific Update Set by sys_id. Returns name, state, application, description, customer updates count.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the update set' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getUpdateSet(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.createUpdateSet`, desc: 'Create a new Update Set. All subsequent configuration changes will be captured in this set until another is made current.',
    params: { type: 'object', properties: { name: { type: 'string', description: 'Update Set name' }, description: { type: 'string', description: 'Description of what this update set contains' } }, required: ['name', 'description'] },
    fn: async (_c, inp) => ok(await p.createUpdateSet(s(inp,'name'), s(inp,'description'), cfg)) }),
  bt({ name: `${px}.commitUpdateSet`, desc: 'Complete/commit an Update Set. Changes state from "in progress" to "complete". A completed update set can be exported for migration.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the update set to commit' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.commitUpdateSet(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.retrieveUpdateSet`, desc: 'Retrieve a remote Update Set from another instance by URL. Downloads the update set XML for import.',
    params: { type: 'object', properties: { url: { type: 'string', description: 'URL of the remote instance update set endpoint' } }, required: ['url'] },
    fn: async (_c, inp) => ok(await p.retrieveUpdateSet(s(inp,'url'), cfg)) }),
  bt({ name: `${px}.previewUpdateSet`, desc: 'Preview a retrieved Update Set. Identifies conflicts, collisions, and potential issues before applying. Essential step in the migration pipeline.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the retrieved update set' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.previewUpdateSet(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.applyUpdateSet`, desc: 'Apply/commit a retrieved Update Set to the current instance. Applies all configuration changes from the update set. THIS IS A DESTRUCTIVE OPERATION — preview first.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the update set to apply' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.applyUpdateSet(s(inp,'id'), cfg)) }),
]; }

/* ================================================================
 *  PHASE 11 — NLU, Virtual Agent, Predictive Intelligence
 * ================================================================ */
export function phase11(px: string, cfg: EnterpriseConnectorConfig, p: ServiceNowProvider): Tool[] { return [
  bt({ name: `${px}.nluPredict`, desc: 'Run NLU prediction on text. Returns detected intent, entities, and confidence scores. Uses a trained NLU model.',
    params: { type: 'object', properties: { text: { type: 'string', description: 'User utterance to classify, e.g. "I need to reset my password"' }, modelId: { type: 'string', description: 'sys_id of the NLU model' } }, required: ['text', 'modelId'] },
    fn: async (_c, inp) => ok(await p.nluPredict(s(inp,'text'), s(inp,'modelId'), cfg)) }),
  bt({ name: `${px}.nluListModels`, desc: 'List trained NLU models. Returns model name, language, intent count, entity count, last trained date, accuracy score.',
    params: { type: 'object', properties: {} },
    fn: async (_c, _inp) => ok(await p.nluListModels(cfg)) }),
  bt({ name: `${px}.nluGetModel`, desc: 'Get details of a specific NLU model. Returns intents, entities, training data stats, vocabulary size.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the NLU model' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.nluGetModel(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.nluAddTrainingData`, desc: 'Add a training utterance to an NLU model. Associates the utterance text with a specific intent for model retraining.',
    params: { type: 'object', properties: { modelId: { type: 'string', description: 'sys_id of the NLU model' }, utterance: { type: 'string', description: 'Training utterance text, e.g. "How do I change my password?"' }, intentId: { type: 'string', description: 'sys_id of the intent to associate with' } }, required: ['modelId', 'utterance', 'intentId'] },
    fn: async (_c, inp) => ok(await p.nluAddTrainingData(s(inp,'modelId'), s(inp,'utterance'), s(inp,'intentId'), cfg)) }),
  bt({ name: `${px}.vaListTopics`, desc: 'List Virtual Agent topics. Topics define conversation flows for the chatbot — each topic handles a specific user intent (e.g. "Reset Password", "Check Ticket Status").',
    params: { type: 'object', properties: {} },
    fn: async (_c, _inp) => ok(await p.vaListTopics(cfg)) }),
  bt({ name: `${px}.vaStartConversation`, desc: 'Start a Virtual Agent conversation with a specific topic. Returns a conversation ID and the first bot response/prompt.',
    params: { type: 'object', properties: { topicId: { type: 'string', description: 'sys_id of the VA topic to start' } }, required: ['topicId'] },
    fn: async (_c, inp) => ok(await p.vaStartConversation(s(inp,'topicId'), cfg)) }),
  bt({ name: `${px}.vaSendMessage`, desc: 'Send a message in an active Virtual Agent conversation. Returns the bot\'s response, suggested actions, and conversation state.',
    params: { type: 'object', properties: { conversationId: { type: 'string', description: 'Conversation ID from vaStartConversation' }, message: { type: 'string', description: 'User message text' } }, required: ['conversationId', 'message'] },
    fn: async (_c, inp) => ok(await p.vaSendMessage(s(inp,'conversationId'), s(inp,'message'), cfg)) }),
  bt({ name: `${px}.piClassify`, desc: 'Run Predictive Intelligence classification on a record. Returns predicted field values (e.g. predicted category, assignment_group) with confidence scores.',
    params: { type: 'object', properties: { table: { type: 'string', description: 'Table name, e.g. incident' }, recordId: { type: 'string', description: 'sys_id of the record to classify' } }, required: ['table', 'recordId'] },
    fn: async (_c, inp) => ok(await p.piClassify(s(inp,'table'), s(inp,'recordId'), cfg)) }),
  bt({ name: `${px}.piSimilarity`, desc: 'Find similar records using Predictive Intelligence. Returns records ranked by similarity score. Useful for finding related incidents, known errors, or knowledge articles.',
    params: { type: 'object', properties: { table: { type: 'string', description: 'Table name, e.g. incident' }, recordId: { type: 'string', description: 'sys_id of the reference record' }, limit: { type: 'number', description: 'Max similar records (default: 10)' } }, required: ['table', 'recordId'] },
    fn: async (_c, inp) => ok(await p.piSimilarity(s(inp,'table'), s(inp,'recordId'), cfg, n(inp,'limit',10))) }),
  bt({ name: `${px}.piGetSolution`, desc: 'Get AI-suggested solution for a specific record using Predictive Intelligence. Returns recommended knowledge articles, past resolutions, and suggested actions.',
    params: { type: 'object', properties: { table: { type: 'string', description: 'Table name, e.g. incident' }, recordId: { type: 'string', description: 'sys_id of the record' } }, required: ['table', 'recordId'] },
    fn: async (_c, inp) => ok(await p.piGetSolution(s(inp,'table'), s(inp,'recordId'), cfg)) }),
]; }

/* ================================================================
 *  PHASE 12 — System Admin, Governance, Platform
 * ================================================================ */
export function phase12(px: string, cfg: EnterpriseConnectorConfig, p: ServiceNowProvider): Tool[] { return [
  bt({ name: `${px}.getProperty`, desc: 'Get a ServiceNow system property by name. System properties control platform behavior — e.g. glide.ui.date_format, glide.email.smtp.active.',
    params: { type: 'object', properties: { name: { type: 'string', description: 'Property name, e.g. "glide.ui.date_format", "glide.email.smtp.active"' } }, required: ['name'] },
    fn: async (_c, inp) => ok(await p.getProperty(s(inp,'name'), cfg)) }),
  bt({ name: `${px}.setProperty`, desc: 'Set a system property value. WARNING: Changing system properties can affect instance behavior. Use with caution in production.',
    params: { type: 'object', properties: { name: { type: 'string', description: 'Property name' }, value: { type: 'string', description: 'New property value' } }, required: ['name', 'value'] },
    fn: async (_c, inp) => ok(await p.setProperty(s(inp,'name'), s(inp,'value'), cfg)) }),
  bt({ name: `${px}.listProperties`, desc: 'List system properties. Returns name, value, description, type, is_private flag.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "nameSTARTSWITHglide.email"' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listProperties(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.listACLs`, desc: 'List Access Control Lists (ACLs). ACLs define who can read, write, create, delete records on tables and fields. Returns type, operation, role requirements, script conditions.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "name=incident.*", "operation=write"' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listACLs(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.getACL`, desc: 'Get a specific ACL record by sys_id. Returns full rule details including conditions, roles, and scripts.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the ACL' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getACL(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.createACL`, desc: 'Create a new ACL rule. Fields: name (table.field pattern), operation (read/write/create/delete), type, roles, condition, script. REQUIRES APPROVAL in configuration-first approach.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'ACL fields: name (e.g. "incident.priority"), operation (read/write/create/delete), type (record/field), admin_overrides, roles, condition, script' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createACL(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.listScheduledJobs`, desc: 'List scheduled jobs (sysauto). Returns job name, run_type (Daily/Weekly/Monthly/Periodically), next_action, active status, script.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listScheduledJobs(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.getScheduledJob`, desc: 'Get a specific scheduled job by sys_id.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the scheduled job' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getScheduledJob(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.createScheduledJob`, desc: 'Create a new scheduled job. Fields: name (required), run_type (Daily/Weekly/Monthly/Once/Periodically), active, script, run_as, conditional.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Job fields: name (required), run_type, time, run_dayofweek, run_dayofmonth, script, active (default true)' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createScheduledJob(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.toggleScheduledJob`, desc: 'Enable or disable a scheduled job.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the scheduled job' }, active: { type: 'boolean', description: 'true to enable, false to disable' } }, required: ['id', 'active'] },
    fn: async (_c, inp) => ok(await p.toggleScheduledJob(s(inp,'id'), b(inp,'active'), cfg)) }),
  bt({ name: `${px}.listAuditLogs`, desc: 'List audit log entries (sys_audit). Shows who changed what, when, on which record. Essential for compliance and troubleshooting.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "tablename=incident^fieldname=state^sys_created_on>=javascript:gs.daysAgoStart(7)"' }, limit: { type: 'number', description: 'Max results (default: 100)' } } },
    fn: async (_c, inp) => ok(await p.listAuditLogs(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',100))) }),
  bt({ name: `${px}.listSystemLogs`, desc: 'List system log entries (syslog). Application and platform logs for debugging — includes source, level (Error/Warning/Info), message, created_on.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "level=Error^sys_created_on>=javascript:gs.minutesAgoStart(60)"' }, limit: { type: 'number', description: 'Max results (default: 100)' } } },
    fn: async (_c, inp) => ok(await p.listSystemLogs(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',100))) }),
  bt({ name: `${px}.listTransactionLogs`, desc: 'List transaction logs (syslog_transaction). Shows HTTP transactions with URL, method, response_time, status, user. Useful for performance analysis.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "response_time>5000", "status=500"' }, limit: { type: 'number', description: 'Max results (default: 100)' } } },
    fn: async (_c, inp) => ok(await p.listTransactionLogs(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',100))) }),
  bt({ name: `${px}.listPlugins`, desc: 'List ServiceNow plugins. Returns plugin ID, name, version, active status. Plugins add major platform capabilities.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "active=true", "nameSTARTSWITHcom.snc"' }, limit: { type: 'number', description: 'Max results (default: 100)' } } },
    fn: async (_c, inp) => ok(await p.listPlugins(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',100))) }),
  bt({ name: `${px}.activatePlugin`, desc: 'Activate/install a ServiceNow plugin. WARNING: Plugin activation can change system behavior and takes several minutes. Requires admin role.',
    params: { type: 'object', properties: { pluginId: { type: 'string', description: 'Plugin ID, e.g. "com.snc.change_management"' } }, required: ['pluginId'] },
    fn: async (_c, inp) => ok(await p.activatePlugin(s(inp,'pluginId'), cfg)) }),
]; }

/* ================================================================
 *  PHASE 13 — Development & Configuration
 *  Configuration First, Customization with Approval
 * ================================================================ */
export function phase13(px: string, cfg: EnterpriseConnectorConfig, p: ServiceNowProvider): Tool[] { return [
  /* --- Catalog Item Admin --- */
  bt({ name: `${px}.createCatalogItemRecord`, desc: 'Create a new Service Catalog item (sc_cat_item) via the Table API. This is admin/developer configuration — NOT ordering. Fields: name (required), short_description, category, sc_catalogs, active, delivery_plan, workflow.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Catalog item fields: name (required), short_description, description, category (sys_id), sc_catalogs (sys_id), active (true/false), delivery_plan, workflow, price, recurring_price, delivery_time' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createCatalogItemRecord(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateCatalogItemRecord`, desc: 'Update a catalog item configuration. Can modify name, description, category, active status, delivery plan, workflow, variables, etc.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the catalog item' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateCatalogItemRecord(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.deleteCatalogItemRecord`, desc: 'Delete a catalog item from the system. WARNING: Irreversible. Prefer setting active=false instead.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the catalog item to delete' } }, required: ['id'] },
    fn: async (_c, inp) => { await p.deleteCatalogItemRecord(s(inp,'id'), cfg); return ok({ success: true }); } }),
  bt({ name: `${px}.cloneCatalogItemRecord`, desc: 'Clone an existing catalog item to create a similar one. Copies the item definition, variables, variable sets, and UI policies. Saves significant setup time.',
    params: { type: 'object', properties: { sourceId: { type: 'string', description: 'sys_id of the catalog item to clone' }, newName: { type: 'string', description: 'Name for the cloned item' } }, required: ['sourceId', 'newName'] },
    fn: async (_c, inp) => ok(await p.cloneCatalogItemRecord(s(inp,'sourceId'), s(inp,'newName'), cfg)) }),

  /* --- Catalog Variables (Admin) --- */
  bt({ name: `${px}.listCatalogVariablesAdmin`, desc: 'List all variables (form fields) defined on a catalog item — admin view. Returns variable name, type, label, order, mandatory, default_value, reference table, choice list.',
    params: { type: 'object', properties: { catItemId: { type: 'string', description: 'sys_id of the catalog item' } }, required: ['catItemId'] },
    fn: async (_c, inp) => ok(await p.listCatalogVariablesAdmin(s(inp,'catItemId'), cfg)) }),
  bt({ name: `${px}.createCatalogVariable`, desc: 'Add a new variable (form field) to a catalog item. Variable types: String, Integer, Boolean, Reference, Select Box, Multi-line Text, Date, CheckBox, Lookup Select Box, List Collector, etc.',
    params: { type: 'object', properties: { catItemId: { type: 'string', description: 'sys_id of the catalog item' }, data: { type: 'object', description: 'Variable fields: name (required), question_text (label, required), type (string/integer/boolean/reference/select_box/etc.), mandatory (true/false), default_value, order (display order), reference (table name for Reference type), choice_table, choice_field' } }, required: ['catItemId', 'data'] },
    fn: async (_c, inp) => ok(await p.createCatalogVariable(s(inp,'catItemId'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateCatalogVariable`, desc: 'Update a catalog variable definition. Change label, type, mandatory flag, default value, order, etc.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the variable (item_option_new)' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateCatalogVariable(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.deleteCatalogVariable`, desc: 'Delete a variable from a catalog item. WARNING: Irreversible — existing requested items referencing this variable may lose data.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the variable' } }, required: ['id'] },
    fn: async (_c, inp) => { await p.deleteCatalogVariable(s(inp,'id'), cfg); return ok({ success: true }); } }),
  bt({ name: `${px}.reorderCatalogVariables`, desc: 'Reorder variables on a catalog item. Changes the display order of form fields.',
    params: { type: 'object', properties: { items: { type: 'array', description: 'Array of { id: variable_sys_id, order: new_order_number }' } }, required: ['items'] },
    fn: async (_c, inp) => ok(await p.reorderCatalogVariables(inp.arguments['items'] as Array<{id:string;order:number}>, cfg)) }),

  /* --- Variable Sets --- */
  bt({ name: `${px}.listVariableSets`, desc: 'List reusable Variable Sets. A variable set is a group of variables shared across multiple catalog items (e.g. "Approval Info", "Delivery Location").',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listVariableSets(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createVariableSet`, desc: 'Create a new Variable Set (io_set_item). Fields: name (required), description, type (single_row/multi_row), display_title.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Variable set fields: name (required), description, type, display_title' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createVariableSet(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.addVariableToSet`, desc: 'Add a variable to a Variable Set. Same variable types as catalog variables but scoped to the set.',
    params: { type: 'object', properties: { setId: { type: 'string', description: 'sys_id of the variable set' }, data: { type: 'object', description: 'Variable fields: name, question_text, type, mandatory, default_value, order' } }, required: ['setId', 'data'] },
    fn: async (_c, inp) => ok(await p.addVariableToSet(s(inp,'setId'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.attachVariableSet`, desc: 'Attach a Variable Set to a catalog item. All variables in the set become available on the item.',
    params: { type: 'object', properties: { catItemId: { type: 'string', description: 'sys_id of the catalog item' }, variableSetId: { type: 'string', description: 'sys_id of the variable set to attach' } }, required: ['catItemId', 'variableSetId'] },
    fn: async (_c, inp) => ok(await p.attachVariableSet(s(inp,'catItemId'), s(inp,'variableSetId'), cfg)) }),
  bt({ name: `${px}.detachVariableSet`, desc: 'Detach a Variable Set from a catalog item.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the io_set_item_cat_item M2M record' } }, required: ['id'] },
    fn: async (_c, inp) => { await p.detachVariableSet(s(inp,'id'), cfg); return ok({ success: true }); } }),

  /* --- Record Producers --- */
  bt({ name: `${px}.listRecordProducers`, desc: 'List Record Producers. Record Producers appear in the Service Catalog but create records directly in a target table (e.g. incident, request) rather than creating sc_req_item.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listRecordProducers(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createRecordProducer`, desc: 'Create a new Record Producer. Fields: name (required), table_name (target table), short_description, category, sc_catalogs, script, template.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Record producer fields: name (required), table_name (required, e.g. "incident"), short_description, category, sc_catalogs, script (for value mapping), template (default values)' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createRecordProducer(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateRecordProducer`, desc: 'Update a Record Producer configuration.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the record producer' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateRecordProducer(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.deleteRecordProducer`, desc: 'Delete a Record Producer.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the record producer' } }, required: ['id'] },
    fn: async (_c, inp) => { await p.deleteRecordProducer(s(inp,'id'), cfg); return ok({ success: true }); } }),

  /* --- Flow Designer (Development) --- */
  bt({ name: `${px}.createFlowRecord`, desc: 'Create a new Flow Designer flow definition via Table API. The flow is created inactive. Add actions with addFlowAction, then activate with activateFlow.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Flow fields: name (required), description, table, trigger_type, active (default false)' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createFlowRecord(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateFlowRecord`, desc: 'Update a flow definition. Can modify name, description, trigger configuration.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the flow' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateFlowRecord(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.activateFlow`, desc: 'Activate a flow definition. Makes it live — the flow will execute when its trigger conditions are met.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the flow to activate' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.activateFlow(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.deactivateFlow`, desc: 'Deactivate a flow. Stops it from executing. Existing in-progress executions may or may not complete depending on configuration.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the flow to deactivate' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.deactivateFlow(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.getFlowDefinition`, desc: 'Get the full design-time definition of a flow. Returns trigger, actions, conditions, data pills, and subflow references.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the flow' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getFlowDefinition(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.addFlowAction`, desc: 'Add an action step to a flow definition. Actions include: Create Record, Update Record, Send Email, Call REST, Run Script, If/Else, Loop, Wait, Approval, etc.',
    params: { type: 'object', properties: { flowId: { type: 'string', description: 'sys_id of the parent flow' }, data: { type: 'object', description: 'Action definition: action_type, order, inputs, name' } }, required: ['flowId', 'data'] },
    fn: async (_c, inp) => ok(await p.addFlowAction(s(inp,'flowId'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.removeFlowAction`, desc: 'Remove an action step from a flow definition.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the flow action to remove' } }, required: ['id'] },
    fn: async (_c, inp) => { await p.removeFlowAction(s(inp,'id'), cfg); return ok({ success: true }); } }),
  bt({ name: `${px}.listSubflows`, desc: 'List available subflows. Subflows are reusable flow components that can be called from other flows.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' } } },
    fn: async (_c, inp) => ok(await p.listSubflows(cfg, inp.arguments['query'] as string ?? '')) }),
  bt({ name: `${px}.createSubflow`, desc: 'Create a new subflow definition.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Subflow fields: name (required), description, inputs, outputs' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createSubflow(o(inp,'data'), cfg)) }),

  /* --- Notifications --- */
  bt({ name: `${px}.listNotifications`, desc: 'List email notification definitions (sysevent_email_action). Notifications are triggered by events/conditions on records. Returns name, table, event, recipients, active status.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "collection=incident", "active=true"' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listNotifications(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createNotification`, desc: 'Create a new email notification rule. Fields: name (required), collection (table), event_name OR conditions, subject, message_html, recipients (users/groups/email).',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Notification fields: name (required), collection (table e.g. "incident"), action_insert/action_update/action_delete (true/false), event_name, condition, subject, message_html, recipient_users, recipient_groups, send_self (true/false), active' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createNotification(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateNotification`, desc: 'Update a notification rule. Common changes: conditions, recipients, subject/body, enable/disable.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the notification' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateNotification(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.deleteNotification`, desc: 'Delete a notification rule.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the notification' } }, required: ['id'] },
    fn: async (_c, inp) => { await p.deleteNotification(s(inp,'id'), cfg); return ok({ success: true }); } }),
  bt({ name: `${px}.testNotification`, desc: 'Send a test notification to verify it works correctly before activating.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the notification to test' }, recipientEmail: { type: 'string', description: 'Email address to send the test to' } }, required: ['id', 'recipientEmail'] },
    fn: async (_c, inp) => ok(await p.testNotification(s(inp,'id'), s(inp,'recipientEmail'), cfg)) }),

  /* --- Business Rules --- */
  bt({ name: `${px}.listBusinessRules`, desc: 'List Business Rules. Business Rules are server-side scripts that execute when records are displayed, inserted, updated, deleted, or queried. Returns name, table, when (before/after/display/async), active.',
    params: { type: 'object', properties: { tableName: { type: 'string', description: 'Filter by table, e.g. "incident"' }, query: { type: 'string', description: 'Additional filter' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listBusinessRules(cfg, inp.arguments['tableName'] as string ?? '', inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createBusinessRule`, desc: 'Create a new Business Rule. REQUIRES APPROVAL — Business Rules execute server-side code and can affect data integrity. Fields: name, collection (table), when (before/after/async/display), action_insert/update/delete/query, script.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Business Rule fields: name (required), collection (table, required), when (before/after/async/display), action_insert/action_update/action_delete/action_query (true/false), script (GlideRecord-based), filter_condition, order, active' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createBusinessRule(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateBusinessRule`, desc: 'Update a Business Rule. Can modify script, conditions, when/order, active status.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the business rule' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateBusinessRule(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.toggleBusinessRule`, desc: 'Enable or disable a Business Rule.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the business rule' }, active: { type: 'boolean', description: 'true to enable, false to disable' } }, required: ['id', 'active'] },
    fn: async (_c, inp) => ok(await p.toggleBusinessRule(s(inp,'id'), b(inp,'active'), cfg)) }),

  /* --- Client Scripts --- */
  bt({ name: `${px}.listClientScripts`, desc: 'List Client Scripts. Client Scripts run in the browser when forms load, change, or submit. Types: onLoad, onChange, onSubmit, onCellEdit.',
    params: { type: 'object', properties: { tableName: { type: 'string', description: 'Filter by table' }, query: { type: 'string', description: 'Additional filter' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listClientScripts(cfg, inp.arguments['tableName'] as string ?? '', inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createClientScript`, desc: 'Create a new Client Script. REQUIRES APPROVAL — Client Scripts run in user browsers. Fields: name, table, type (onLoad/onChange/onSubmit/onCellEdit), script, field_name (for onChange), ui_type (Desktop/Mobile/Both).',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Client Script fields: name (required), table (required), type (onLoad/onChange/onSubmit/onCellEdit), script (JavaScript), field_name (for onChange), ui_type, active, messages (for getMessage)' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createClientScript(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateClientScript`, desc: 'Update a Client Script.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the client script' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateClientScript(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.toggleClientScript`, desc: 'Enable or disable a Client Script.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the client script' }, active: { type: 'boolean', description: 'true to enable, false to disable' } }, required: ['id', 'active'] },
    fn: async (_c, inp) => ok(await p.toggleClientScript(s(inp,'id'), b(inp,'active'), cfg)) }),

  /* --- UI Policies --- */
  bt({ name: `${px}.listUIPolicies`, desc: 'List UI Policies. UI Policies dynamically change form behavior — make fields mandatory, read-only, or visible/hidden based on conditions. No scripting needed (configuration-first).',
    params: { type: 'object', properties: { tableName: { type: 'string', description: 'Filter by table' }, query: { type: 'string', description: 'Additional filter' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listUIPolicies(cfg, inp.arguments['tableName'] as string ?? '', inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createUIPolicy`, desc: 'Create a new UI Policy. Configuration-first approach — no code needed. Fields: short_description (required), table (required), conditions, on_load (true/false), reverse_if_false, order.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'UI Policy fields: short_description (required), table (required), conditions (encoded query), on_load (true/false), reverse_if_false (true/false), inherit, order, active, global (true/false)' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createUIPolicy(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateUIPolicy`, desc: 'Update a UI Policy definition.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the UI policy' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateUIPolicy(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.addUIPolicyAction`, desc: 'Add an action to a UI Policy. Actions specify what happens to form fields: mandatory (true/false), visible (true/false), disabled/read_only (true/false).',
    params: { type: 'object', properties: { policyId: { type: 'string', description: 'sys_id of the parent UI policy' }, data: { type: 'object', description: '{ field: "field_name", mandatory: "true"|"false"|"ignore", visible: "true"|"false"|"ignore", disabled: "true"|"false"|"ignore" }' } }, required: ['policyId', 'data'] },
    fn: async (_c, inp) => ok(await p.addUIPolicyAction(s(inp,'policyId'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.toggleUIPolicy`, desc: 'Enable or disable a UI Policy.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the UI policy' }, active: { type: 'boolean', description: 'true to enable, false to disable' } }, required: ['id', 'active'] },
    fn: async (_c, inp) => ok(await p.toggleUIPolicy(s(inp,'id'), b(inp,'active'), cfg)) }),

  /* --- Data Policies --- */
  bt({ name: `${px}.listDataPolicies`, desc: 'List Data Policies. Data Policies enforce data quality rules at the server level — e.g. require "category" on all incidents. Unlike UI Policies, these apply to ALL data entry methods (API, import, web).',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listDataPolicies(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createDataPolicy`, desc: 'Create a new Data Policy. Fields: model_table (required), short_description, conditions, apply_to (All, REST, Import).',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Data Policy fields: model_table (table, required), short_description, conditions, active, inherit' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createDataPolicy(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateDataPolicy`, desc: 'Update a Data Policy.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the data policy' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateDataPolicy(s(inp,'id'), o(inp,'data'), cfg)) }),

  /* --- Script Includes --- */
  bt({ name: `${px}.listScriptIncludes`, desc: 'List Script Includes. Script Includes are reusable server-side JavaScript classes/functions. They are called by Business Rules, Scheduled Jobs, and other server scripts.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listScriptIncludes(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createScriptInclude`, desc: 'Create a new Script Include. REQUIRES APPROVAL — executes server-side code. Fields: name (required), api_name, script (class definition), client_callable, active.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Script Include fields: name (required), api_name, script (JavaScript class definition), client_callable (true allows browser access via GlideAjax), active, description' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createScriptInclude(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateScriptInclude`, desc: 'Update a Script Include.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the script include' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateScriptInclude(s(inp,'id'), o(inp,'data'), cfg)) }),

  /* --- Scheduled Scripts --- */
  bt({ name: `${px}.listScheduledScripts`, desc: 'List Scheduled Script Executions (sysauto_script). These run GlideRecord scripts on a schedule for maintenance, data cleanup, integrations.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listScheduledScripts(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createScheduledScript`, desc: 'Create a Scheduled Script Execution. Fields: name (required), run_type, script, run_as, conditional, condition.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Scheduled script fields: name (required), run_type (Daily/Weekly/Monthly/Once/Periodically), script, run_as, conditional, condition, active' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createScheduledScript(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateScheduledScript`, desc: 'Update a Scheduled Script.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the scheduled script' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateScheduledScript(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.toggleScheduledScript`, desc: 'Enable or disable a Scheduled Script.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the scheduled script' }, active: { type: 'boolean', description: 'true to enable, false to disable' } }, required: ['id', 'active'] },
    fn: async (_c, inp) => ok(await p.toggleScheduledScript(s(inp,'id'), b(inp,'active'), cfg)) }),

  /* --- UI Actions --- */
  bt({ name: `${px}.listUIActions`, desc: 'List UI Actions. UI Actions add buttons, links, and context menus to forms and lists. They execute client-side or server-side scripts on click.',
    params: { type: 'object', properties: { tableName: { type: 'string', description: 'Filter by table' }, query: { type: 'string', description: 'Additional filter' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listUIActions(cfg, inp.arguments['tableName'] as string ?? '', inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createUIAction`, desc: 'Create a new UI Action (button/link/menu item). REQUIRES APPROVAL. Fields: name (required), table (required), script, client (true=client-side), form_button/form_link/form_context_menu, condition.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'UI Action fields: name (required), table (required), script (JavaScript), client (true/false), form_button/form_link/form_context_menu/list_button/list_context_menu (true/false), condition, order, active, hint (tooltip)' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createUIAction(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateUIAction`, desc: 'Update a UI Action.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the UI action' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateUIAction(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.toggleUIAction`, desc: 'Enable or disable a UI Action.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the UI action' }, active: { type: 'boolean', description: 'true to enable, false to disable' } }, required: ['id', 'active'] },
    fn: async (_c, inp) => ok(await p.toggleUIAction(s(inp,'id'), b(inp,'active'), cfg)) }),

  /* --- Workflows (Legacy) --- */
  bt({ name: `${px}.listWorkflows`, desc: 'List Workflow definitions (legacy workflow engine — prefer Flow Designer for new work). Returns workflow name, table, published version, active status.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listWorkflows(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.getWorkflow`, desc: 'Get a specific Workflow definition by sys_id.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the workflow' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.getWorkflow(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.createWorkflow`, desc: 'Create a new Workflow definition.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Workflow fields: name (required), table, description' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createWorkflow(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.publishWorkflow`, desc: 'Publish a Workflow to make it executable. Creates a published version from the current design.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the workflow to publish' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.publishWorkflow(s(inp,'id'), cfg)) }),

  /* --- Approval & Assignment Rules --- */
  bt({ name: `${px}.listApprovalRules`, desc: 'List approval rules (sysrule_approver). Approval rules auto-assign approvers based on conditions — e.g. manager approval for change requests over $10K.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listApprovalRules(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createApprovalRule`, desc: 'Create an approval rule. Fields: name (required), table, condition, approval_type (anyone/everyone), approver_source (field/group/user/script).',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Approval rule fields: name (required), table, condition, approval_type (anyone/everyone), approval (user/group/script), source_table, order, active' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createApprovalRule(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateApprovalRule`, desc: 'Update an approval rule.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the approval rule' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateApprovalRule(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.listAssignmentRules`, desc: 'List assignment rules (sysrule_assignment). Auto-assign incidents/changes/etc. to groups/users based on conditions (e.g. category, location, priority).',
    params: { type: 'object', properties: { tableName: { type: 'string', description: 'Filter by table' }, query: { type: 'string', description: 'Additional filter' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listAssignmentRules(cfg, inp.arguments['tableName'] as string ?? '', inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createAssignmentRule`, desc: 'Create an assignment rule. Fields: name (required), table, condition, group, user, order, active.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Assignment rule fields: name (required), table (required), condition, group (sys_id), user (sys_id), order, active, script' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createAssignmentRule(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateAssignmentRule`, desc: 'Update an assignment rule.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the assignment rule' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateAssignmentRule(s(inp,'id'), o(inp,'data'), cfg)) }),

  /* --- SLA Definitions --- */
  bt({ name: `${px}.listSLADefinitions`, desc: 'List SLA definitions (contract_sla). SLA definitions set response/resolution time targets by priority, category, or other conditions.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listSLADefinitions(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createSLADefinition`, desc: 'Create a new SLA definition. Fields: name (required), table, target (duration), start_condition, stop_condition, pause_condition, retroactive.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'SLA definition fields: name (required), collection (table), duration, start_condition, stop_condition, pause_condition, retroactive (true/false), active' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createSLADefinition(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateSLADefinition`, desc: 'Update an SLA definition.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the SLA definition' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateSLADefinition(s(inp,'id'), o(inp,'data'), cfg)) }),

  /* --- Inbound Email Actions --- */
  bt({ name: `${px}.listInboundEmailActions`, desc: 'List inbound email actions (sysevent_in_email_action). These process incoming emails to auto-create/update incidents, cases, or execute scripts.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listInboundEmailActions(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createInboundEmailAction`, desc: 'Create an inbound email action. Fields: name (required), target_table, condition, action_type (Reply, Forward, Create, Update), template, script.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Inbound email action fields: name (required), target_table, condition, action (Reply/Forward), template, script, stop_processing, order, active' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createInboundEmailAction(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateInboundEmailAction`, desc: 'Update an inbound email action.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the inbound email action' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateInboundEmailAction(s(inp,'id'), o(inp,'data'), cfg)) }),

  /* --- Table/Dictionary Management --- */
  bt({ name: `${px}.listTables`, desc: 'List tables (sys_db_object) in the instance. Returns table name, label, super_class, is_extendable, number_ref. Use to discover the data model.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter, e.g. "nameSTARTSWITHu_", "super_class.name=task"' }, limit: { type: 'number', description: 'Max results (default: 100)' } } },
    fn: async (_c, inp) => ok(await p.listTables(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',100))) }),
  bt({ name: `${px}.getTableSchema`, desc: 'Get the schema (dictionary) for a table. Returns all columns with name, type, max_length, mandatory, reference, default_value, choice_set. Essential for understanding data structure.',
    params: { type: 'object', properties: { tableName: { type: 'string', description: 'Table name, e.g. incident, sc_cat_item' } }, required: ['tableName'] },
    fn: async (_c, inp) => ok(await p.getTableSchema(s(inp,'tableName'), cfg)) }),
  bt({ name: `${px}.createTable`, desc: 'Create a new table in ServiceNow. REQUIRES APPROVAL. Fields: name (required, e.g. u_custom_table), label, super_class (extends), is_extendable, number_ref.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Table fields: name (required, must start with u_ for custom), label, super_class (parent table), is_extendable, number_ref (auto-number config)' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createTableRecord(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.addColumn`, desc: 'Add a column (field) to a table. Creates a sys_dictionary record. Field types: string, integer, boolean, reference, date, datetime, choice, journal, etc.',
    params: { type: 'object', properties: { tableName: { type: 'string', description: 'Table to add the column to' }, data: { type: 'object', description: 'Column definition: element (field name, required), column_label, internal_type (string/integer/boolean/reference/date/etc.), max_length, mandatory, reference (target table for Reference type), default_value' } }, required: ['tableName', 'data'] },
    fn: async (_c, inp) => ok(await p.addColumn(s(inp,'tableName'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateColumn`, desc: 'Update a column/field definition. Can change label, mandatory flag, default value, max_length, etc.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the sys_dictionary record' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateColumn(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.listChoices`, desc: 'List choice values for a dropdown field. Returns label, value, sequence, dependent_value.',
    params: { type: 'object', properties: { tableName: { type: 'string', description: 'Table name, e.g. incident' }, element: { type: 'string', description: 'Field name, e.g. category, state' } }, required: ['tableName', 'element'] },
    fn: async (_c, inp) => ok(await p.listChoices(s(inp,'tableName'), s(inp,'element'), cfg)) }),
  bt({ name: `${px}.addChoice`, desc: 'Add a choice value to a dropdown field. Fields: value (required), label (required), sequence (display order), dependent_value.',
    params: { type: 'object', properties: { tableName: { type: 'string', description: 'Table name' }, element: { type: 'string', description: 'Field name' }, data: { type: 'object', description: '{ value: string (stored value), label: string (display text), sequence: number }' } }, required: ['tableName', 'element', 'data'] },
    fn: async (_c, inp) => ok(await p.addChoice(s(inp,'tableName'), s(inp,'element'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateChoice`, desc: 'Update a choice value.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the choice record' }, data: { type: 'object', description: 'Fields to update: label, value, sequence' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateChoice(s(inp,'id'), o(inp,'data'), cfg)) }),

  /* --- App Scopes & Modules --- */
  bt({ name: `${px}.listAppScopes`, desc: 'List application scopes (sys_scope). Scopes isolate customizations into named containers — essential for ALM (Application Lifecycle Management).',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listAppScopes(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createAppScope`, desc: 'Create a new application scope. Fields: name (required), scope (namespace), short_description, version.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'App scope fields: name (required), scope (namespace, e.g. x_myco_myapp), short_description, version' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createAppScope(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.listModules`, desc: 'List navigation modules (sys_app_module). Modules define menu items in the application navigator.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listModules(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createModule`, desc: 'Create a navigation module. Fields: title (required), application (menu), link_type (list/new/url/separator), table, filter, roles, order.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Module fields: title (required), application (menu sys_id), link_type, table, filter, roles, order, active' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createModule(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateModule`, desc: 'Update a navigation module.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the module' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateModule(s(inp,'id'), o(inp,'data'), cfg)) }),

  /* --- Service Portal --- */
  bt({ name: `${px}.listPortalPages`, desc: 'List Service Portal pages (sp_page). Returns page ID (url_suffix), title, internal, documentation.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listPortalPages(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createPortalPage`, desc: 'Create a new Service Portal page.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Page fields: title (required), id (url path), category, internal (true/false)' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createPortalPage(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.listWidgets`, desc: 'List Service Portal widgets (sp_widget). Widgets are reusable UI components with HTML, CSS, client script, and server script.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listWidgets(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createWidget`, desc: 'Create a Service Portal widget. Fields: name (required), id, template (HTML), css, client_script, server_script, demo_data.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Widget fields: name (required), id, template (HTML), css, client_script (AngularJS), server_script (GlideRecord), demo_data (JSON)' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createWidget(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateWidget`, desc: 'Update a Service Portal widget.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the widget' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateWidget(s(inp,'id'), o(inp,'data'), cfg)) }),

  /* --- Knowledge Management --- */
  bt({ name: `${px}.listKnowledgeBases`, desc: 'List Knowledge Bases (kb_knowledge_base). Knowledge Bases are containers that organize articles by topic/audience.',
    params: { type: 'object', properties: { query: { type: 'string', description: 'Filter query' }, limit: { type: 'number', description: 'Max results (default: 50)' } } },
    fn: async (_c, inp) => ok(await p.listKnowledgeBases(cfg, inp.arguments['query'] as string ?? '', n(inp,'limit',50))) }),
  bt({ name: `${px}.createKnowledgeBase`, desc: 'Create a new Knowledge Base. Fields: title (required), description, owner, kb_version (2/3), disable_commenting, disable_suggesting.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Knowledge base fields: title (required), description, owner, kb_version, disable_commenting' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createKnowledgeBase(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.createKnowledgeArticle`, desc: 'Create a new Knowledge Article. Fields: short_description (required), kb_knowledge_base (required), text (HTML body), category, workflow_state (draft/published), author, article_type.',
    params: { type: 'object', properties: { data: { type: 'object', description: 'Article fields: short_description (required), kb_knowledge_base (sys_id, required), text (HTML body), category, workflow_state (draft), author, article_type (text/html/wiki), keywords' } }, required: ['data'] },
    fn: async (_c, inp) => ok(await p.createKnowledgeArticle(o(inp,'data'), cfg)) }),
  bt({ name: `${px}.updateKnowledgeArticle`, desc: 'Update a Knowledge Article. Can modify text, category, workflow_state.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the article' }, data: { type: 'object', description: 'Fields to update' } }, required: ['id', 'data'] },
    fn: async (_c, inp) => ok(await p.updateKnowledgeArticle(s(inp,'id'), o(inp,'data'), cfg)) }),
  bt({ name: `${px}.publishKnowledgeArticle`, desc: 'Publish a draft Knowledge Article. Changes workflow_state to "published" and makes it available in searches.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the article to publish' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.publishKnowledgeArticle(s(inp,'id'), cfg)) }),
  bt({ name: `${px}.retireKnowledgeArticle`, desc: 'Retire a published Knowledge Article. Removes it from search results and marks it as outdated.',
    params: { type: 'object', properties: { id: { type: 'string', description: 'sys_id of the article to retire' } }, required: ['id'] },
    fn: async (_c, inp) => ok(await p.retireKnowledgeArticle(s(inp,'id'), cfg)) }),
]; }

/* ================================================================
 *  PUBLIC EXPORT — All extended tools combined
 * ================================================================ */
