export {
  registerModelProvider as weaveRegisterModel,
  getModelProvider as weaveGetModel,
  createModel as weaveModel,
  registerEmbeddingProvider as weaveRegisterEmbedding,
  getEmbeddingProvider as weaveGetEmbedding,
  createEmbeddingModel as weaveEmbeddingModel,
  modelObservabilityMiddleware as weaveModelObservability,
  streamObservabilityMiddleware as weaveStreamObservability,
  selectModelByCapability as weaveSelectModel,
  selectEmbeddingByCapability as weaveSelectEmbedding,
  type CreateModelOptions,
  type CreateEmbeddingModelOptions,
  type ModelFactory,
  type EmbeddingModelFactory,
} from './router.js';
